#!/usr/bin/env python3
"""Write `tests/<area>.rs` from the catalogue.  Generated; never hand-edited.

One file per area, one `#[test] #[ignore]` function per entry still owed,
carrying the entry's citations and given/when/then as its doc comment and a
`todo!()` body, so `cargo test -- --ignored` fails on exactly the tests not yet
implemented.  An entry whose id is marked `acceptance: XXX-NN` on a real test
elsewhere in the workspace gets no stub.

Usage: gen_stubs.py [out_dir]   (default: the crate's tests/ directory)
"""
import os, re, sys
from catalogue import *   # noqa

out_dir = sys.argv[1] if len(sys.argv) > 1 else TESTS_DIR
entries = sorted(load(), key=lambda e: e["id"])
impl = implemented_ids()


def slug(s, n=48):
    s = re.sub(r"[^a-z0-9]+", "_", s.lower()).strip("_")
    return s[:n].rstrip("_")


def doc(lines):
    return "\n".join("/// " + l if l else "///" for l in lines)


files = {}
for e in entries:
    if e["id"] in impl or e["kind"] == "withdrawn":
        continue
    area = e["area"].replace("-", "_")
    name = f"{e['id'].lower().replace('-', '_')}_{slug(e['title'])}"
    body = [e["title"], "", "Spec: " + "; ".join(e["spec"]),
            f"Milestone: {e['milestone']}.  Kind: {e['kind']}.  Oracle: {e['oracle']}.", ""]
    for r in e["rule"]:
        body.append(f"Rule ({r['where']}): \"{r['text']}\"")
    body += ["", "Given: " + e["given"], "When: " + e["when"], "Then: " + e["then"]]
    if e.get("interpretation"):
        body += ["", "Interpretation: " + e["interpretation"]]
    reason = f"acceptance {e['id']}: owed at milestone {e['milestone']}"
    files.setdefault(area, []).append(
        doc(body) + "\n#[test]\n#[ignore = \"" + reason + "\"]\n"
        f"fn {name}() {{\n    todo!(\"{e['id']}: {e['title'].replace(chr(34), chr(39))}\")\n}}\n")

os.makedirs(out_dir, exist_ok=True)
for old in os.listdir(out_dir):
    if old.endswith(".rs"):
        os.remove(os.path.join(out_dir, old))
for area, fns in sorted(files.items()):
    with open(os.path.join(out_dir, area + ".rs"), "w", encoding="utf-8") as f:
        f.write("//! GENERATED by tools/gen_stubs.py from acceptance.json.  Do not edit;\n"
                "//! change the catalogue and regenerate.  Each stub is one acceptance test\n"
                "//! still owed for this area.\n\n" + "\n".join(fns))
print(f"wrote {sum(len(v) for v in files.values())} stubs in {len(files)} files to {out_dir}")
