//! Make and examine identities.
//!
//! An identity is a classical and a post-quantum key with one keyhash over
//! both (design §5.1, `wire-format.md` §1.1). This mints one, prints a
//! public identity's keyhash and key material, and reproduces the corpus
//! seed recipe so a vector can be regenerated by hand.

use rhtn_crypto::{Identity, SigningIdentity};
use std::path::Path;

/// The two seeds an identity is derived from, in order, as `rhtn-daemon`
/// reads them: the classical one and the post-quantum one.  Sixty-four
/// bytes and no framing, because a key file is read by one program.
pub const IDENTITY_BYTES: usize = 64;

/// Mint an identity into `path`.
///
/// **It refuses to overwrite.** A key file replaced in place is an
/// identity nobody can reach any more, and the node serving under the old
/// one is the operator's own. The file is written readable by its owner
/// alone, which is what the daemon insists on before it will start.
///
/// **Minting a key is not becoming a participant.** A key becomes one by
/// being adopted, which takes two parties present to each other and
/// cannot be done from a terminal (design §6, §7).
pub fn mint(path: &Path, seeds: [[u8; 32]; 2]) -> Result<Identity, String> {
    if path.exists() {
        return Err(format!(
            "{} exists, and a key file is never replaced in place",
            path.display()
        ));
    }
    let mut bytes = seeds[0].to_vec();
    bytes.extend_from_slice(&seeds[1]);
    write_private(path, &bytes)?;
    Ok(SigningIdentity::from_seeds(&seeds[0], &seeds[1]).public)
}

fn write_private(path: &Path, bytes: &[u8]) -> Result<(), String> {
    std::fs::write(path, bytes).map_err(|e| format!("{}: {e}", path.display()))?;
    #[cfg(unix)]
    {
        use std::os::unix::fs::PermissionsExt;
        std::fs::set_permissions(path, std::fs::Permissions::from_mode(0o600))
            .map_err(|e| format!("{}: {e}", path.display()))?;
    }
    Ok(())
}

/// Read an identity file and describe its public half.  The private half
/// is never printed: a tool that writes a signing key to a terminal has
/// published it.
pub fn describe(path: &Path) -> Result<String, String> {
    let bytes = std::fs::read(path).map_err(|e| format!("{}: {e}", path.display()))?;
    if bytes.len() != IDENTITY_BYTES {
        return Err(format!(
            "{} is {} bytes, not {IDENTITY_BYTES}",
            path.display(),
            bytes.len()
        ));
    }
    let (ed, pq): ([u8; 32], [u8; 32]) = (
        bytes[..32].try_into().unwrap(),
        bytes[32..].try_into().unwrap(),
    );
    Ok(public_lines(&SigningIdentity::from_seeds(&ed, &pq).public))
}

/// What a peers file carries and what a keyhash is over: the material
/// itself, since a keyhash alone cannot be pinned (`wire-format.md` §2.2).
pub fn public_lines(id: &Identity) -> String {
    let km = id.key_material();
    format!(
        "keyhash   {}\nmaterial  {}\n",
        crate::inspect::hex(&id.keyhash),
        crate::inspect::hex(&km)
    )
}

/// The seeds `test-vectors/keys.md` derives for a named test identity.
///
/// Reproduced here so a mismatch between the reference and the vectors is
/// visible from one command. **These are test identities and are not
/// secret**: anyone can derive them from the name, which is the point.
pub fn test_seeds(name: &str) -> [[u8; 32]; 2] {
    [
        rhtn_codec::cose::sha256(format!("rhtn-test-vectors:{name}:ed25519-seed").as_bytes()),
        rhtn_codec::cose::sha256(format!("rhtn-test-vectors:{name}:ml-dsa-65-seed").as_bytes()),
    ]
}
