//! GENERATED by tools/gen_stubs.py from acceptance.json.  Do not edit;
//! change the catalogue and regenerate.  Each stub is one acceptance test
//! still owed for this area.  tests/rustfmt.toml keeps rustfmt off
//! this directory: the titles are the catalogue's, not hand-laid code.

/// Carry the operator's provider credential in the backup envelope and never in the archive
///
/// Spec: light-client-requirements.md §2
/// Milestone: after-5.  Kind: positive.  Oracle: behaviour.
///
/// Rule (light-client-requirements.md §2): "An operator's backup carries their provider credential too."
/// Rule (light-client-requirements.md §2): "not in the archive"
///
/// Given: An operator's client holding a provider credential.
/// When: It exports a backup and a sibling replicates its archive.
/// Then: The envelope's contents carry the credential and open only under the passphrase; the archive the sibling holds contains no byte of it.
#[test]
#[ignore = "acceptance ARC-28: owed at milestone after-5"]
fn arc_28_carry_the_operator_s_provider_credential_in_the() {
    todo!("ARC-28: Carry the operator's provider credential in the backup envelope and never in the archive")
}
