//! GENERATED by tools/gen_stubs.py from acceptance.json.  Do not edit;
//! change the catalogue and regenerate.  Each stub is one acceptance test
//! still owed for this area.

/// Staple the issuer's delegation to an attestation signed under a delegated key, and verify the signature against the key it names
///
/// Spec: wire-format.md §7.1; wire-format.md §8.2
/// Milestone: after-5.  Kind: positive.  Oracle: behaviour.
///
/// Rule (wire-format.md §7.1): "A verifier checks field 7 against the key field 8 names, and field 8 against the issuer's own key material"
/// Rule (wire-format.md §8.2): "Where the verifier sits outside the horizon, the object carries the delegation itself"
///
/// Given: Patron P runs as an instance under delegation D for key k; relying party R holds P's KeyMaterial and is outside P's horizon.
/// When: P's node issues a CurrencyAttestation for subject A and it is stapled to an introduction R receives.
/// Then: Field 8 is present and equals D; field 7 verifies under k; R accepts the attestation as P's, having verified D under P's KeyMaterial and matched k to D's field 1, and addresses the key it holds for A by participant-authored evidence.
#[test]
#[ignore = "acceptance CUR-21: owed at milestone after-5"]
fn cur_21_staple_the_issuer_s_delegation_to_an_attestation() {
    todo!("CUR-21: Staple the issuer's delegation to an attestation signed under a delegated key, and verify the signature against the key it names")
}

/// Reject an attestation whose stapled delegation names a key other than the one that signed it
///
/// Spec: wire-format.md §7.1
/// Milestone: after-5.  Kind: negative.  Oracle: behaviour.
///
/// Rule (wire-format.md §7.1): "an attestation whose field 8 names a key other than the one that signed field 7 is malformed"
///
/// Given: A CurrencyAttestation whose field 7 verifies under key k and whose field 8 is a valid delegation by the issuer naming key k'.
/// When: A relying party evaluates it.
/// Then: The attestation is malformed: not accepted, not treated as absent, and no currency is taken from it.
#[test]
#[ignore = "acceptance CUR-22: owed at milestone after-5"]
fn cur_22_reject_an_attestation_whose_stapled_delegation_n() {
    todo!("CUR-22: Reject an attestation whose stapled delegation names a key other than the one that signed it")
}
