//! GENERATED by tools/gen_stubs.py from acceptance.json.  Do not edit;
//! change the catalogue and regenerate.  Each stub is one acceptance test
//! still owed for this area.

/// Reject an envelope signature made under a delegated key
///
/// Spec: design §23.3; infra-client-requirements.md §7
/// Milestone: after-5.  Kind: negative.  Oracle: behaviour.
///
/// Rule (design §23.3): "what advances an archive it never signs"
/// Rule (infra-client-requirements.md §7): "What advances an archive, a disavowal or a countersignature, is your operator's act and never yours."
///
/// Given: A type-3 disavowal envelope whose single signature is by an instance's delegated transport key, the instance's delegation held and valid.
/// When: A node verifies it.
/// Then: The envelope fails signature verification: the delegated key is not the identity's key material and a held delegation does not stand in for it; the transaction is not stored and not forwarded.
#[test]
#[ignore = "acceptance DEC-35: owed at milestone after-5"]
fn dec_35_reject_an_envelope_signature_made_under_a_delega() {
    todo!("DEC-35: Reject an envelope signature made under a delegated key")
}
