//! GENERATED by tools/gen_stubs.py from acceptance.json.  Do not edit;
//! change the catalogue and regenerate.  Each stub is one acceptance test
//! still owed for this area.  tests/rustfmt.toml keeps rustfmt off
//! this directory: the titles are the catalogue's, not hand-laid code.

/// Evaluate a candidate from presence records fetched from the candidate's own client
///
/// Spec: light-client-requirements.md §2
/// Milestone: after-5.  Kind: positive.  Oracle: behaviour.
///
/// Rule (light-client-requirements.md §2): "the subject holds their archive, so a patron evaluating you fetches from you"
///
/// Given: Patron P and candidate C, C's client serving its own archive over the payload channel; nothing injected into P's store by the test.
/// When: P's operator asks P to evaluate C for adoption.
/// Then: P fetches C's presence records from C's client, verifies the walk, keeps the records as evidence, and the evaluation P reports reflects them; before the fetch C's standing at P was zero.
#[test]
#[ignore = "acceptance MET-12: owed at milestone after-5"]
fn met_12_evaluate_a_candidate_from_presence_records_fetch() {
    todo!("MET-12: Evaluate a candidate from presence records fetched from the candidate's own client")
}
