//! GENERATED by tools/gen_stubs.py from acceptance.json.  Do not edit;
//! change the catalogue and regenerate.  Each stub is one acceptance test
//! still owed for this area.

/// Let the user override direct versus relayed payload in both directions, with each disclosure stated
///
/// Spec: light-client-requirements.md §5
/// Milestone: manual.  Kind: manual.  Oracle: behaviour.
///
/// Rule (light-client-requirements.md §5): "Direct versus relayed payload must be overridable"
///
/// Given: A release build of the light client.
/// When: A reviewer opens the payload path setting.
/// Then: Both overrides exist, and the setting states that direct reveals the user's IP to a peer inside the horizon and relayed reveals the communication graph to the serving node.
#[test]
#[ignore = "acceptance PRD-01: owed at milestone manual"]
fn prd_01_let_the_user_override_direct_versus_relayed_payl() {
    todo!("PRD-01: Let the user override direct versus relayed payload in both directions, with each disclosure stated")
}

/// Warn before an authority change that revokes resource access, and list upward-reaching policies on a new patron
///
/// Spec: light-client-requirements.md §6
/// Milestone: manual.  Kind: manual.  Oracle: behaviour.
///
/// Rule (light-client-requirements.md §6): "warn if the resulting topology change will revoke access to resources the user currently uses"
/// Rule (light-client-requirements.md §6): "When accepting a new patron, list any resources whose policy reaches upward."
///
/// Given: A release build with the user holding access to resources under the current patron.
/// When: A reviewer initiates a departure, then accepts a new patron.
/// Then: The departure flow warns and names the resources that will be lost before confirmation; the adoption flow lists resources whose predicates reach upward.
#[test]
#[ignore = "acceptance PRD-02: owed at milestone manual"]
fn prd_02_warn_before_an_authority_change_that_revokes_res() {
    todo!("PRD-02: Warn before an authority change that revokes resource access, and list upward-reaching policies on a new patron")
}

/// Warn that an unlinked identity path abandons standing, and that a linked one loses unlinkability
///
/// Spec: light-client-requirements.md §6
/// Milestone: manual.  Kind: manual.  Oracle: behaviour.
///
/// Rule (light-client-requirements.md §6): "warn that prior standing will be abandoned"
///
/// Given: A release build.
/// When: A reviewer starts a plain rotation, then a recovery.
/// Then: The plain rotation warns that prior standing is abandoned; the recovery states that the link to the prior identity will be published within the horizon.
#[test]
#[ignore = "acceptance PRD-03: owed at milestone manual"]
fn prd_03_warn_that_an_unlinked_identity_path_abandons_sta() {
    todo!("PRD-03: Warn that an unlinked identity path abandons standing, and that a linked one loses unlinkability")
}

/// Encourage a second independent adoption early
///
/// Spec: light-client-requirements.md §6
/// Milestone: manual.  Kind: manual.  Oracle: behaviour.
///
/// Rule (light-client-requirements.md §6): "Encourage a second independent adoption early"
///
/// Given: A release build with a user holding one adoption.
/// When: A reviewer uses the client through its first sessions.
/// Then: The client prompts, unobtrusively and before any eclipse condition, that a second independent adoption protects against a single patron.
#[test]
#[ignore = "acceptance PRD-04: owed at milestone manual"]
fn prd_04_encourage_a_second_independent_adoption_early() {
    todo!("PRD-04: Encourage a second independent adoption early")
}

/// Resolve simultaneous opposite adoptions by asking the two to choose a direction
///
/// Spec: light-client-requirements.md §7
/// Milestone: manual.  Kind: manual.  Oracle: behaviour.
///
/// Rule (light-client-requirements.md §7): "ask them to choose one direction rather than reporting a protocol failure"
///
/// Given: Two release-build clients in one ceremony each proposing to adopt the other.
/// When: A reviewer triggers the conflict.
/// Then: Both clients present a choice of direction and neither reports a protocol error.
#[test]
#[ignore = "acceptance PRD-05: owed at milestone manual"]
fn prd_05_resolve_simultaneous_opposite_adoptions_by_askin() {
    todo!("PRD-05: Resolve simultaneous opposite adoptions by asking the two to choose a direction")
}

/// Disclose to operators what their subordinates are exposed to, the hosting model, and the roles users hold
///
/// Spec: infra-client-requirements.md §8; infra-client-requirements.md §10.6; infra-client-requirements.md §10.7
/// Milestone: manual.  Kind: manual.  Oracle: behaviour.
///
/// Rule (infra-client-requirements.md §8): "Tell an operator plainly what their subordinates are exposed to"
/// Rule (infra-client-requirements.md §10.6): "Display whether a resource is hosted here or brokered to an external service."
/// Rule (infra-client-requirements.md §10.7): "The roles they hold on each resource."
///
/// Given: A release build of the infra client with one hosted and one brokered resource.
/// When: A reviewer binds each resource and views a member's access.
/// Then: The binding view shows hosted against brokered; the operator view states the exposure the configuration creates; the accessing user's view shows the roles held and not the predicates.
#[test]
#[ignore = "acceptance PRD-06: owed at milestone manual"]
fn prd_06_disclose_to_operators_what_their_subordinates_ar() {
    todo!("PRD-06: Disclose to operators what their subordinates are exposed to, the hosting model, and the roles users hold")
}

/// Encrypt backups under a key kept apart, say what losing the device costs, and scan imports for expired retention
///
/// Spec: design §13.7.1; light-client-requirements.md §2
/// Milestone: manual.  Kind: manual.  Oracle: behaviour.
///
/// Rule (design §13.7.1): "Encrypt under a key not stored alongside it."
/// Rule (light-client-requirements.md §2): "Maintain backups, and make the consequence visible to the user."
/// Rule (light-client-requirements.md §2): "Scan any imported backup for expired retention"
///
/// Given: A release build.
/// When: A reviewer creates a backup, reads the backup screen, and imports a backup containing captures past their window.
/// Then: The backup is encrypted under a passphrase-derived key not stored with it; the screen states what device loss costs; the import deletes the expired captures and says so.
#[test]
#[ignore = "acceptance PRD-07: owed at milestone manual"]
fn prd_07_encrypt_backups_under_a_key_kept_apart_say_what() {
    todo!("PRD-07: Encrypt backups under a key kept apart, say what losing the device costs, and scan imports for expired retention")
}

/// Tell the user on first brokered use that ending membership does not end the vendor's session
///
/// Spec: light-client-requirements.md §8
/// Milestone: manual.  Kind: manual.  Oracle: behaviour.
///
/// Rule (light-client-requirements.md §8): "Tell the user, when they first use a brokered resource, that ending their membership will not end that vendor's session."
///
/// Given: A release build with a brokered resource available.
/// When: A reviewer opens the brokered resource for the first time.
/// Then: A notice states that the vendor's session outlives membership, shown once, before traffic is routed.
#[test]
#[ignore = "acceptance PRD-08: owed at milestone manual"]
fn prd_08_tell_the_user_on_first_brokered_use_that_ending() {
    todo!("PRD-08: Tell the user on first brokered use that ending membership does not end the vendor's session")
}

/// Present a restored archive as recovered on trust, never as verified-complete
///
/// Spec: light-client-requirements.md §2
/// Milestone: manual.  Kind: manual.  Oracle: behaviour.
///
/// Rule (light-client-requirements.md §2): "never present a restored archive as verified-complete"
///
/// Given: A release build on a device that lost its archive.
/// When: A reviewer restores from a holder.
/// Then: The interface states that the restored history is complete only as far as the holder claims and was not verified complete.
#[test]
#[ignore = "acceptance PRD-09: owed at milestone manual"]
fn prd_09_present_a_restored_archive_as_recovered_on_trust() {
    todo!("PRD-09: Present a restored archive as recovered on trust, never as verified-complete")
}
