//! GENERATED by tools/gen_stubs.py from acceptance.json.  Do not edit;
//! change the catalogue and regenerate.  Each stub is one acceptance test
//! still owed for this area.  tests/rustfmt.toml keeps rustfmt off
//! this directory: the titles are the catalogue's, not hand-laid code.

/// Treat a memo naming you as a cycle, confirm it against your own row, and remove the subordinate that forwarded it
///
/// Spec: wire-format.md §10.2.1; wire-format.md §10.2.4; design §15.2
/// Milestone: 4.  Kind: positive.  Oracle: model.
///
/// Rule (wire-format.md §10.2.1): "If field 1 is you, a memo you originated has come back to you from below"
/// Rule (wire-format.md §10.2.1): "It fires at any depth, on the memo alone, and terminates the memo there."
/// Rule (wire-format.md §10.2.4): "It removes the direct subordinate that forwarded the memo to it"
/// Rule (wire-format.md §10.2.4): "the slot is emptied in the detector's own table and the vacancy memo goes rootward"
///
/// Given: Node N holds subordinate S in slot k and a row matching that. A cycle below S has formed, so a memo N originated for slot k returns to N on the session from S.
/// When: N receives the memo.
/// Then: No TopologyMemo is forwarded further. N's slot k is empty afterwards, a vacancy memo for slot k goes rootward from N, and no transaction of any type is minted, stored or pushed.
///
/// Interpretation: Re-derived 2026-09-21: a cycle repair is a removal, not a disavowal [author, 2026-09-21]. The live test that held this entry asserts the superseded disavowal and is unmarked until the code lands.
#[test]
#[ignore = "acceptance PRP-12: owed at milestone 4"]
fn prp_12_treat_a_memo_naming_you_as_a_cycle_confirm_it_ag() {
    todo!("PRP-12: Treat a memo naming you as a cycle, confirm it against your own row, and remove the subordinate that forwarded it")
}

/// Store a pushed delegation that verifies under its delegating keyhash, keep the newest per keyhash, and forward it
///
/// Spec: wire-format.md §10.1.1; wire-format.md §8.2
/// Milestone: after-5.  Kind: positive.  Oracle: behaviour.
///
/// Rule (wire-format.md §10.1.1): "A `Delegation` is stored when its hybrid signature verifies under the delegating keyhash's material and replaces any earlier one held for that keyhash"
/// Rule (wire-format.md §8.2): "A holder keeps one delegation per delegating keyhash, the newest by field 3, and drops the rest"
///
/// Given: Node S holds G's KeyMaterial, G within S's h_store, and a delegation D1 by G for key k1; a TopologyPush carrying delegation D2 by G for key k2 with a later not_before arrives from neighbour X.
/// When: S receives it.
/// Then: S stores D2, no longer holds D1, forwards D2 to every adjacent node except X, and forwards a second copy of D2 to nobody.
#[test]
#[ignore = "acceptance PRP-26: owed at milestone after-5"]
fn prp_26_store_a_pushed_delegation_that_verifies_under_it() {
    todo!("PRP-26: Store a pushed delegation that verifies under its delegating keyhash, keep the newest per keyhash, and forward it")
}

/// Mint no transaction on a confirmed cycle
///
/// Spec: wire-format.md §10.2.4
/// Milestone: after-5.  Kind: negative.  Oracle: behaviour.
///
/// Rule (wire-format.md §10.2.4): "A removal is not a disavowal."
/// Rule (wire-format.md §10.2.4): "No transaction is signed and no reason code is carried"
///
/// Given: Node N confirms a memo naming itself against its own row for slot k held by S.
/// When: N acts on it.
/// Then: N's store gains no transaction, no envelope by N is pushed to any neighbour, and no reason code appears anywhere; the slot is empty and the vacancy memo is the only thing sent.
#[test]
#[ignore = "acceptance PRP-27: owed at milestone after-5"]
fn prp_27_mint_no_transaction_on_a_confirmed_cycle() {
    todo!("PRP-27: Mint no transaction on a confirmed cycle")
}

/// Push your own delegation as each credential comes into force
///
/// Spec: wire-format.md §8.2
/// Milestone: after-5.  Kind: positive.  Oracle: behaviour.
///
/// Rule (wire-format.md §8.2): "An instance pushes each credential as it comes into force, under §10.1's forwarding rule"
///
/// Given: An instance with a run of credentials and a neighbour N inside its horizon; the clock crosses a credential boundary.
/// When: The next credential comes into force.
/// Then: The instance sends a TopologyPush carrying that credential to every adjacent node; N stores it, drops the previous one for that keyhash, and forwards it onward.
#[test]
#[ignore = "acceptance PRP-28: owed at milestone after-5"]
fn prp_28_push_your_own_delegation_as_each_credential_come() {
    todo!("PRP-28: Push your own delegation as each credential comes into force")
}
