//! GENERATED by tools/gen_stubs.py from acceptance.json.  Do not edit;
//! change the catalogue and regenerate.  Each stub is one acceptance test
//! still owed for this area.  tests/rustfmt.toml keeps rustfmt off
//! this directory: the titles are the catalogue's, not hand-laid code.

/// Hold only ciphertext, recipient keyhash and device, and arrival time while a message waits.
///
/// Spec: infra-client-requirements.md §2; design §14.1.6
/// Milestone: 3.  Kind: negative.  Oracle: behaviour.
///
/// Rule (infra-client-requirements.md §2): "Hold the minimum while a message waits: ciphertext, recipient keyhash, arrival time. Nothing further."
/// Rule (design §14.1.6): "Queue metadata is the minimum: ciphertext, recipient keyhash and device, arrival time."
///
/// Given: Sender X submitted one message addressed to C to N while C was not attached, and N accepted it; N exposes its queue store to the test.
/// When: The test inspects N's record of the waiting message.
/// Then: The record consists of the ciphertext, C's keyhash, the device the submission named and an arrival time, and carries nothing further: in particular no identity or address of X.
///
/// Interpretation: Re-derived 2026-09-22: the queue is per device, so the device the submission named is part of the minimum.
#[test]
#[ignore = "acceptance QUE-05: owed at milestone 3"]
fn que_05_hold_only_ciphertext_recipient_keyhash_and_devic() {
    todo!("QUE-05: Hold only ciphertext, recipient keyhash and device, and arrival time while a message waits.")
}

/// Queue a ciphertext for the device it names and deliver it to that device's session alone
///
/// Spec: design §14.1.6; wire-format.md §7.10
/// Milestone: after-5.  Kind: positive.  Oracle: behaviour.
///
/// Rule (design §14.1.6): "The queue is per device"
/// Rule (wire-format.md §7.10): "the recipient's device this ciphertext is for"
///
/// Given: Subject T's devices d1 and d2 are both offline; N accepts a submission for T naming d1.
/// When: d2 attaches, drains, and detaches; then d1 attaches.
/// Then: d2's AttachAck field 4 is 0 and d2 receives nothing; d1's AttachAck field 4 is 1 and d1 receives the ciphertext.
#[test]
#[ignore = "acceptance QUE-21: owed at milestone after-5"]
fn que_21_queue_a_ciphertext_for_the_device_it_names_and_d() {
    todo!("QUE-21: Queue a ciphertext for the device it names and deliver it to that device's session alone")
}
