//! GENERATED by tools/gen_stubs.py from acceptance.json.  Do not edit;
//! change the catalogue and regenerate.  Each stub is one acceptance test
//! still owed for this area.

/// Keep no record of a catalog query after answering it
///
/// Spec: infra-client-requirements.md §1
/// Milestone: after-5.  Kind: negative.  Oracle: behaviour.
///
/// Rule (infra-client-requirements.md §1): "Keep the state that serving needs and no history of the requests that produced it, whatever the request class"
///
/// Given: Node N with a catalog; client C sends a filtered catalog query and receives its reply.
/// When: N's state is inspected after the reply and again after a save and restart.
/// Then: Nothing at N records that C asked, what filter it used or when: the catalog and the registrations are the only state, unchanged by the query.
#[test]
#[ignore = "acceptance RSC-41: owed at milestone after-5"]
fn rsc_41_keep_no_record_of_a_catalog_query_after_answerin() {
    todo!("RSC-41: Keep no record of a catalog query after answering it")
}

/// Keep no history of a role table's rows
///
/// Spec: infra-client-requirements.md §10.2
/// Milestone: after-5.  Kind: negative.  Oracle: behaviour.
///
/// Rule (infra-client-requirements.md §10.2): "The table is current state, and no history of its rows is kept"
///
/// Given: A resource whose owner sets member M's row to reader, then to editor, then removes it.
/// When: The table is inspected after each change and after a restart.
/// Then: Only the current row is held at each step and nothing after removal; nothing in the table, its provenance marks or its store says what M's roles used to be.
#[test]
#[ignore = "acceptance RSC-42: owed at milestone after-5"]
fn rsc_42_keep_no_history_of_a_role_table_s_rows() {
    todo!("RSC-42: Keep no history of a role table's rows")
}
