//! GENERATED by tools/gen_stubs.py from acceptance.json.  Do not edit;
//! change the catalogue and regenerate.  Each stub is one acceptance test
//! still owed for this area.  tests/rustfmt.toml keeps rustfmt off
//! this directory: the titles are the catalogue's, not hand-laid code.

/// Attach a subject's several devices as several sessions, each named by the key it presented
///
/// Spec: wire-format.md §8.2
/// Milestone: after-5.  Kind: positive.  Oracle: behaviour.
///
/// Rule (wire-format.md §8.2): "An attach speaks for a device, and a subject's several devices attach as several sessions"
///
/// Given: Subject T's phone presents T's classical component and T's desktop presents a delegated key under T's delegation.
/// When: Both attach to serving node N with field 1 = T.
/// Then: N holds two sessions for T, one per presented key, refuses neither, and binds each device's later publication, deposit and wake registration to the session it arrived on.
#[test]
#[ignore = "acceptance SES-26: owed at milestone after-5"]
fn ses_26_attach_a_subject_s_several_devices_as_several_se() {
    todo!("SES-26: Attach a subject's several devices as several sessions, each named by the key it presented")
}
