//! GENERATED by tools/gen_stubs.py from acceptance.json.  Do not edit;
//! change the catalogue and regenerate.  Each stub is one acceptance test
//! still owed for this area.  tests/rustfmt.toml keeps rustfmt off
//! this directory: the titles are the catalogue's, not hand-laid code.

/// Post a content-free doorbell to the registered endpoint when a message arrives for an offline client, and log nothing
///
/// Spec: infra-client-requirements.md §6.1
/// Milestone: after-5.  Kind: positive.  Oracle: behaviour.
///
/// Rule (infra-client-requirements.md §6.1): "post nothing but a doorbell to it"
/// Rule (infra-client-requirements.md §6.1): "The body carries no payload, no sender and no count"
/// Rule (infra-client-requirements.md §6.1): "Do not log doorbells."
///
/// Given: Node N with a test wake endpoint registered by offline client C under key k; a second submission for C arrives later; then C withdraws the endpoint and a third arrives.
/// When: Each submission is accepted.
/// Then: The endpoint receives one post per arrival while registered, each body encrypted to k and carrying no payload, no sender and no count; nothing is posted after withdrawal; N's state and logs hold no record of any post.
#[test]
#[ignore = "acceptance SUB-14: owed at milestone after-5"]
fn sub_14_post_a_content_free_doorbell_to_the_registered_e() {
    todo!("SUB-14: Post a content-free doorbell to the registered endpoint when a message arrives for an offline client, and log nothing")
}
