//! GENERATED by tools/gen_stubs.py from acceptance.json.  Do not edit;
//! change the catalogue and regenerate.  Each stub is one acceptance test
//! still owed for this area.  tests/rustfmt.toml keeps rustfmt off
//! this directory: the titles are the catalogue's, not hand-laid code.

/// Hold the delegations of the parties in a light client's horizon, and bind a direct-path peer by one
///
/// Spec: light-client-requirements.md §4.2; wire-format.md §10.1.1
/// Milestone: after-5.  Kind: positive.  Oracle: behaviour.
///
/// Rule (light-client-requirements.md §4.2): "Hold the delegations of the parties in it, as a node does"
/// Rule (wire-format.md §10.1.1): "a holder keeps the newest by `not_before` alone"
///
/// Given: Light client A attached to node N; identity D within A's horizon runs a delegated desktop under key k; N pushes D's delegation, then a later one over the same key.
/// When: A receives both and then dials D's desktop on a direct path.
/// Then: A's horizon view holds one delegation for D, the later one, and A binds the presented key k to D from it before any frame arrives on the connection.
#[test]
#[ignore = "acceptance TOP-43: owed at milestone after-5"]
fn top_43_hold_the_delegations_of_the_parties_in_a_light_c() {
    todo!("TOP-43: Hold the delegations of the parties in a light client's horizon, and bind a direct-path peer by one")
}

/// Issue and take subtree acknowledgements in a running node under its standing policy, and admit the grandchild
///
/// Spec: infra-client-requirements.md §10.1; wire-format.md §7.5
/// Milestone: after-5.  Kind: positive.  Oracle: behaviour.
///
/// Rule (infra-client-requirements.md §10.1): "Issue it automatically, under a policy the operator set beforehand."
/// Rule (wire-format.md §7.5): "Acceptance by other nodes is policy, not obligation."
///
/// Given: Daemons G, P and S, S a sibling of G that accepts G's acknowledgements by policy; G configured with a standing acknowledgement policy and hosting a resource; nothing injected by the test.
/// When: An adoption of N under P is pushed to G.
/// Then: G's runtime issues the acknowledgement and pushes it; G's gateway admits N's resource request (no code 4); S holds the acknowledgement and admits N by its policy; the acknowledgement lapses at all three when P departs.
#[test]
#[ignore = "acceptance TOP-44: owed at milestone after-5"]
fn top_44_issue_and_take_subtree_acknowledgements_in_a_run() {
    todo!("TOP-44: Issue and take subtree acknowledgements in a running node under its standing policy, and admit the grandchild")
}
