//! GENERATED by tools/gen_stubs.py from acceptance.json.  Do not edit;
//! change the catalogue and regenerate.  Each stub is one acceptance test
//! still owed for this area.

/// Bind an unpinned presented key by a delegation already held from the topology class, with no attach
///
/// Spec: wire-format.md §9.1; wire-format.md §10.1
/// Milestone: after-5.  Kind: positive.  Oracle: behaviour.
///
/// Rule (wire-format.md §9.1): "a delegation from that keyhash naming it is already held from the topology class (§10.1)"
///
/// Given: Node A holds B's KeyMaterial and, from a TopologyPush, B's current delegation naming transport key k; B is an instance presenting k.
/// When: A opens a request-only connection to B for a resolution and B presents k in the handshake.
/// Then: A's pinned check fails, A binds k to B by the held delegation without waiting for any frame, sends its request, and accepts the unsigned reply as B's.
#[test]
#[ignore = "acceptance TRN-18: owed at milestone after-5"]
fn trn_18_bind_an_unpinned_presented_key_by_a_delegation_a() {
    todo!("TRN-18: Bind an unpinned presented key by a delegation already held from the topology class, with no attach")
}

/// Read a delegated peer's delegation frame before sending anything on a connection that opens no session
///
/// Spec: wire-format.md §8.2; wire-format.md §8.0
/// Milestone: after-5.  Kind: positive.  Oracle: behaviour.
///
/// Rule (wire-format.md §8.2): "A dialler whose pinned check fails and who holds no delegation for the keyhash reads that frame before sending anything"
/// Rule (wire-format.md §8.0): "a delegated peer's first frame on a connection that opens no session"
///
/// Given: Node A holds B's KeyMaterial from a referral and no delegation for B; B is an instance presenting delegated key k.
/// When: A opens a request-only connection to B.
/// Then: A sends nothing until B's first frame on stream 0, a control frame of type 7 carrying a delegation by B naming k within its window, arrives and verifies under B's KeyMaterial; A then sends its request, and B's delegation is cached against k so a second connection under k waits for no frame.
#[test]
#[ignore = "acceptance TRN-19: owed at milestone after-5"]
fn trn_19_read_a_delegated_peer_s_delegation_frame_before() {
    todo!("TRN-19: Read a delegated peer's delegation frame before sending anything on a connection that opens no session")
}

/// Refuse a connection whose unpinned presented key is bound by nothing, and attribute no request to a delegated client before its frame
///
/// Spec: wire-format.md §9.1; wire-format.md §8.2
/// Milestone: after-5.  Kind: negative.  Oracle: behaviour.
///
/// Rule (wire-format.md §9.1): "A connection on which none holds is refused, whether or not it would have opened a session."
/// Rule (wire-format.md §8.2): "a server binds a delegated client's requests to the keyhash it claims only after the frame"
///
/// Given: Node A holds B's KeyMaterial and no delegation; B presents an unpinned key k and its first frame is a Heartbeat. Separately, delegated client C opens a connection to node N and sends a type-4 verifier query naming C in field 2 before any delegation frame.
/// When: Each connection proceeds.
/// Then: A refuses the connection to B and sends no request on it. N does not attribute C's query to C: the query is rejected as from an unauthenticated requester, and no verifier answers it.
#[test]
#[ignore = "acceptance TRN-20: owed at milestone after-5"]
fn trn_20_refuse_a_connection_whose_unpinned_presented_key() {
    todo!("TRN-20: Refuse a connection whose unpinned presented key is bound by nothing, and attribute no request to a delegated client before its frame")
}

/// Refuse a delegation whose window is not exactly 48 hours as malformed
///
/// Spec: wire-format.md §8.2
/// Milestone: after-5.  Kind: negative.  Oracle: behaviour.
///
/// Rule (wire-format.md §8.2): "EXACTLY 48 HOURS after field 3: 172,800"
/// Rule (wire-format.md §8.2): "the box under another name"
///
/// Given: Three delegations by a valid issuer over the presented key: field 4 equal to field 3 plus 172,799, plus 172,801, and plus 172,800.
/// When: A receiver decodes each.
/// Then: The first two are malformed and bind nothing; the third decodes, and its window is then checked against the clock.
#[test]
#[ignore = "acceptance TRN-21: owed at milestone after-5"]
fn trn_21_refuse_a_delegation_whose_window_is_not_exactly() {
    todo!("TRN-21: Refuse a delegation whose window is not exactly 48 hours as malformed")
}

/// Accept a delegation whose window contains the receiver's clock within its leeway, and refuse one beyond it
///
/// Spec: wire-format.md §8.2
/// Milestone: after-5.  Kind: must-accept.  Oracle: behaviour.
///
/// Rule (wire-format.md §8.2): "the leeway is configurable on the receiving side with a default of 10 seconds"
/// Rule (wire-format.md §8.2): "A connection refused on the window is retried by the dialler"
///
/// Given: A receiver at default leeway whose clock reads T; delegations with not_before = T + 9, T + 11, and not_after = T - 9, T - 11, each otherwise valid; and the same receiver configured to a leeway of 60.
/// When: Each is presented on a handshake.
/// Then: At the default the T + 9 and T - 9 windows bind and the T + 11 and T - 11 windows are refused, and the dialler retries a connection refused this way; at a leeway of 60 all four bind.
///
/// Interpretation: A must-accept and a negative in one entry, since the boundary is one number read from both sides.
#[test]
#[ignore = "acceptance TRN-22: owed at milestone after-5"]
fn trn_22_accept_a_delegation_whose_window_contains_the_re() {
    todo!("TRN-22: Accept a delegation whose window contains the receiver's clock within its leeway, and refuse one beyond it")
}
