//! GENERATED by tools/gen_stubs.py from acceptance.json.  Do not edit;
//! change the catalogue and regenerate.  Each stub is one acceptance test
//! still owed for this area.  tests/rustfmt.toml keeps rustfmt off
//! this directory: the titles are the catalogue's, not hand-laid code.

/// Bind an unpinned presented key by a delegation already held from the topology class, with no attach
///
/// Spec: wire-format.md §9.1; wire-format.md §10.1
/// Milestone: after-5.  Kind: positive.  Oracle: behaviour.
///
/// Rule (wire-format.md §9.1): "a delegation from that keyhash naming it is already held from the topology class (§10.1)"
///
/// Given: Node A holds B's KeyMaterial and, from a TopologyPush, B's current delegation naming transport key k; B is an instance presenting k.
/// When: A opens a request-only connection to B for a resolution and B presents k in the handshake.
/// Then: A's pinned check fails, A binds k to B by the held delegation without waiting for any frame, sends its request, and accepts the unsigned reply as B's.
#[test]
#[ignore = "acceptance TRN-18: owed at milestone after-5"]
fn trn_18_bind_an_unpinned_presented_key_by_a_delegation_a() {
    todo!("TRN-18: Bind an unpinned presented key by a delegation already held from the topology class, with no attach")
}

/// Read a delegated peer's delegation frame before sending anything on a connection that opens no session
///
/// Spec: wire-format.md §8.2; wire-format.md §8.0
/// Milestone: after-5.  Kind: positive.  Oracle: behaviour.
///
/// Rule (wire-format.md §8.2): "A dialler whose pinned check fails and who holds no delegation for the keyhash reads that frame before sending anything"
/// Rule (wire-format.md §8.0): "a delegated peer's first frame on a connection that opens no session"
///
/// Given: Node A holds B's KeyMaterial from a referral and no delegation for B; B is an instance presenting delegated key k.
/// When: A opens a request-only connection to B.
/// Then: A sends nothing until B's first frame on stream 0, a control frame of type 7 carrying a delegation by B naming k within its window, arrives and verifies under B's KeyMaterial; A then sends its request, and B's delegation is cached against k so a second connection under k waits for no frame.
#[test]
#[ignore = "acceptance TRN-19: owed at milestone after-5"]
fn trn_19_read_a_delegated_peer_s_delegation_frame_before() {
    todo!("TRN-19: Read a delegated peer's delegation frame before sending anything on a connection that opens no session")
}

/// Refuse a connection whose unpinned presented key is bound by nothing, and attribute no request to a delegated client before its frame
///
/// Spec: wire-format.md §9.1; wire-format.md §8.2
/// Milestone: after-5.  Kind: negative.  Oracle: behaviour.
///
/// Rule (wire-format.md §9.1): "A connection on which none holds is refused, whether or not it would have opened a session."
/// Rule (wire-format.md §8.2): "a server binds a delegated client's requests to the keyhash it claims only after the frame"
///
/// Given: Node A holds B's KeyMaterial and no delegation; B presents an unpinned key k and its first frame is a Heartbeat. Separately, delegated client C opens a connection to node N and sends a type-4 verifier query naming C in field 2 before any delegation frame.
/// When: Each connection proceeds.
/// Then: A refuses the connection to B and sends no request on it. N does not attribute C's query to C: the query is rejected as from an unauthenticated requester, and no verifier answers it.
#[test]
#[ignore = "acceptance TRN-20: owed at milestone after-5"]
fn trn_20_refuse_a_connection_whose_unpinned_presented_key() {
    todo!("TRN-20: Refuse a connection whose unpinned presented key is bound by nothing, and attribute no request to a delegated client before its frame")
}

/// Refuse a delegation whose window is not exactly 48 hours as malformed
///
/// Spec: wire-format.md §8.2
/// Milestone: after-5.  Kind: negative.  Oracle: behaviour.
///
/// Rule (wire-format.md §8.2): "EXACTLY 48 HOURS after field 3: 172,800"
/// Rule (wire-format.md §8.2): "the box under another name"
///
/// Given: Three delegations by a valid issuer over the presented key: field 4 equal to field 3 plus 172,799, plus 172,801, and plus 172,800.
/// When: A receiver decodes each.
/// Then: The first two are malformed and bind nothing; the third decodes, and its window is then checked against the clock.
#[test]
#[ignore = "acceptance TRN-21: owed at milestone after-5"]
fn trn_21_refuse_a_delegation_whose_window_is_not_exactly() {
    todo!("TRN-21: Refuse a delegation whose window is not exactly 48 hours as malformed")
}

/// Accept a delegation whose window contains the receiver's clock within its leeway, and refuse one beyond it
///
/// Spec: wire-format.md §8.2
/// Milestone: after-5.  Kind: must-accept.  Oracle: behaviour.
///
/// Rule (wire-format.md §8.2): "the leeway is configurable on the receiving side with a default of 10 seconds"
/// Rule (wire-format.md §8.2): "A connection refused on the window is retried by the dialler"
///
/// Given: A receiver at default leeway whose clock reads T; delegations with not_before = T + 9, T + 11, and not_after = T - 9, T - 11, each otherwise valid; and the same receiver configured to a leeway of 60.
/// When: Each is presented on a handshake.
/// Then: At the default the T + 9 and T - 9 windows bind and the T + 11 and T - 11 windows are refused, and the dialler retries a connection refused this way; at a leeway of 60 all four bind.
///
/// Interpretation: A must-accept and a negative in one entry, since the boundary is one number read from both sides.
#[test]
#[ignore = "acceptance TRN-22: owed at milestone after-5"]
fn trn_22_accept_a_delegation_whose_window_contains_the_re() {
    todo!("TRN-22: Accept a delegation whose window contains the receiver's clock within its leeway, and refuse one beyond it")
}

/// Refuse a session whose delegation names a key other than the one the handshake presented
///
/// Spec: wire-format.md §8.2
/// Milestone: after-5.  Kind: negative.  Oracle: behaviour.
///
/// Rule (wire-format.md §8.2): "A receiver checks field 1 against the key the handshake actually presented and refuses the session if they differ."
///
/// Given: A valid delegation by S naming transport key k1, captured by an adversary; a handshake in which the adversary presents its own key k2 and then sends that delegation in AttachAck field 6.
/// When: The client evaluates the attach.
/// Then: The session is refused: no session state, no queued data and no request is bound to S, and the delegation, though it verifies under S's material, binds nothing because field 1 is not k2.
#[test]
#[ignore = "acceptance TRN-23: owed at milestone after-5"]
fn trn_23_refuse_a_session_whose_delegation_names_a_key_ot() {
    todo!("TRN-23: Refuse a session whose delegation names a key other than the one the handshake presented")
}

/// Refuse a delegation whose delegating keyhash is not the one sought
///
/// Spec: wire-format.md §8.2
/// Milestone: after-5.  Kind: negative.  Oracle: behaviour.
///
/// Rule (wire-format.md §8.2): "checks that field 2 is the keyhash it meant to reach"
///
/// Given: Client C dialling S; the peer presents an unpinned key k and a valid delegation naming k whose field 2 is T, not S.
/// When: C evaluates it.
/// Then: The connection is refused; nothing is bound to S or to T.
#[test]
#[ignore = "acceptance TRN-24: owed at milestone after-5"]
fn trn_24_refuse_a_delegation_whose_delegating_keyhash_is() {
    todo!("TRN-24: Refuse a delegation whose delegating keyhash is not the one sought")
}

/// Reject a classical-only delegation as malformed
///
/// Spec: wire-format.md §8.2
/// Milestone: after-5.  Kind: negative.  Oracle: behaviour.
///
/// Rule (wire-format.md §8.2): "a classical-only delegation is malformed"
///
/// Given: A delegation by S naming the presented key, within its window, whose field 5 carries an Ed25519 signature alone and no ML-DSA-65 signature.
/// When: A receiver decodes it.
/// Then: It is malformed: not verified, not cached, and the session or connection it arrived on is refused as one on which nothing binds the presented key.
#[test]
#[ignore = "acceptance TRN-25: owed at milestone after-5"]
fn trn_25_reject_a_classical_only_delegation_as_malformed() {
    todo!("TRN-25: Reject a classical-only delegation as malformed")
}

/// Cache a verified delegation against its transport key, and verify it once per credential rather than once per connection
///
/// Spec: wire-format.md §8.2
/// Milestone: after-5.  Kind: positive.  Oracle: behaviour.
///
/// Rule (wire-format.md §8.2): "A verified delegation is cached against its transport key."
///
/// Given: Client C with a delegation-verification hook counting verifications; S presents key k under delegation D on two consecutive connections.
/// When: C attaches twice.
/// Then: The hybrid signature over D is verified once; the second connection binds k to S from the cache with no verification; a later connection under a different key k' verifies again.
#[test]
#[ignore = "acceptance TRN-26: owed at milestone after-5"]
fn trn_26_cache_a_verified_delegation_against_its_transpor() {
    todo!("TRN-26: Cache a verified delegation against its transport key, and verify it once per credential rather than once per connection")
}

/// Never issue a resumption ticket that outlives the delegation, and refuse a resumption after it lapses
///
/// Spec: design §14.1.3; infra-client-requirements.md §7
/// Milestone: after-5.  Kind: negative.  Oracle: behaviour.
///
/// Rule (design §14.1.3): "A resumption ticket never outlives the delegation that authorised it."
/// Rule (infra-client-requirements.md §7): "Never issue a resumption ticket that outlives your delegation"
///
/// Given: An instance whose current delegation has one hour of validity left issues a resumption ticket to an attached client; the clock then passes not_after plus the leeway.
/// When: The client attempts a 0-RTT resumption on the ticket.
/// Then: The ticket's lifetime at issue was at most the delegation's remaining validity, and the resumption after not_after is refused; a fresh handshake under the next credential succeeds.
#[test]
#[ignore = "acceptance TRN-27: owed at milestone after-5"]
fn trn_27_never_issue_a_resumption_ticket_that_outlives_th() {
    todo!("TRN-27: Never issue a resumption ticket that outlives the delegation, and refuse a resumption after it lapses")
}
