//! GENERATED by tools/gen_stubs.py from acceptance.json.  Do not edit;
//! change the catalogue and regenerate.  Each stub is one acceptance test
//! still owed for this area.  tests/rustfmt.toml keeps rustfmt off
//! this directory: the titles are the catalogue's, not hand-laid code.

/// Candidates offered on the ceremony's proximity channels open a direct path
///
/// Spec: design §12.6.3; light-client-requirements.md §4
/// Milestone: after-5.  Kind: positive.  Oracle: behaviour.
///
/// Rule (design §12.6.3): "two parties standing in front of each other hand candidates over on the channels the ceremony already uses"
/// Rule (light-client-requirements.md §4): "open nothing from candidates that did not come from the party they name"
///
/// Given: A and B are at a ceremony, on a proximity channel, and neither has written to the other.
/// When: Each offers its traversal candidates on that channel, and afterwards A sends payload to B.
/// Then: A dials B on the candidates B handed over and the payload takes that path; neither serving node carried it. Candidates presented as another party's are not opened from.
#[test]
#[ignore = "acceptance TRV-12: owed at milestone after-5"]
fn trv_12_candidates_offered_on_the_ceremony_s_proximity_c() {
    todo!("TRV-12: Candidates offered on the ceremony's proximity channels open a direct path")
}
