//! GENERATED by tools/gen_stubs.py from acceptance.json.  Do not edit;
//! change the catalogue and regenerate.  Each stub is one acceptance test
//! still owed for this area.  tests/rustfmt.toml keeps rustfmt off
//! this directory: the titles are the catalogue's, not hand-laid code.

/// Check candidate pairs in the order RFC 8445 schedules them, not all at once
///
/// Spec: design §14.1.1
/// Milestone: after-5.  Kind: negative.  Oracle: behaviour.
///
/// Rule (design §14.1.1): "an implementation checks pairs as the RFC schedules them rather than dialling every candidate at once and keeping the first to complete"
///
/// Given: Two leaves with three candidate pairs each of distinct priority, on the path harness recording the order and time of every dial.
/// When: The initiator runs its connectivity checks.
/// Then: The first dial is the highest-priority pair; a lower-priority pair is dialled only after the higher has completed, failed or reached the RFC's pacing interval; no two pairs are dialled in the same instant. An implementation that dials all three at once fails.
///
/// Interpretation: design §14.1.1 defers to RFC 8445's ordering [author, 2026-09-22]; the transport dials every candidate at once today, so this entry is owed and TRV-02, TRV-07 and PAY-15 keep their outcome assertions.
#[test]
#[ignore = "acceptance TRV-11: owed at milestone after-5"]
fn trv_11_check_candidate_pairs_in_the_order_rfc_8445_sche() {
    todo!("TRV-11: Check candidate pairs in the order RFC 8445 schedules them, not all at once")
}
