//! Make and examine identities.
//!
//! An identity is a classical and a post-quantum key with one keyhash over
//! both (design §5.1, `wire-format.md` §1.1). This mints one, prints a
//! public identity's keyhash and key material, and reproduces the corpus
//! seed recipe so a vector can be regenerated by hand.
//!
//! What it owes:
//!
//! - **Say where the private key was written and what protects it.** A tool
//!   that writes a signing key to a path without saying so has published
//!   it.
//! - **Never print private material to a terminal by default.**
//! - **Reproduce `test-vectors/keys.md`'s recipe exactly** for a named test
//!   identity, so a mismatch between the reference and the vectors is
//!   visible from one command.
