//! GENERATED by tools/gen_stubs.py from acceptance.json.  Do not edit;
//! change the catalogue and regenerate.  Each stub is one acceptance test
//! still owed for this area.

/// Evaluate a presented archive by the counterparties the patron already knows and nothing else
///
/// Spec: infra-client-requirements.md §5; design §16.7
/// Milestone: 3.  Kind: positive.  Oracle: behaviour.
///
/// Rule (infra-client-requirements.md §5): "Records naming identities you have never heard of are not weak evidence; they are no evidence"
/// Rule (infra-client-requirements.md §5): "Do not compute a total."
///
/// Given: The reference patron policy on infra node P, whose known identities are the set K; two unbroken presented chains for subject S: chain A whose counterparties are all in K, and chain B equal to A plus many records whose counterparties are all outside K. Weighing an archive is policy per infra-client-requirements.md §5; the test binds the reference policy only.
/// When: P evaluates each chain at adoption.
/// Then: The initial trust state P derives for S is identical for A and B. The result carries no field for archive length, record count or counterparty count.
#[test]
#[ignore = "acceptance ARC-14: owed at milestone 3"]
fn arc_14_evaluate_a_presented_archive_by_the_counterparti() {
    todo!("ARC-14: Evaluate a presented archive by the counterparties the patron already knows and nothing else")
}

/// Report a fork and notify both patrons when currency assertions for one identity diverge
///
/// Spec: design §9.0.2; wire-format.md §7.1
/// Milestone: 3.  Kind: positive.  Oracle: behaviour.
///
/// Rule (design §9.0.2): "A conforming inquirer who receives divergent assertions notifies both patrons."
/// Rule (wire-format.md §7.1): "What a caller can learn is a fork: two patrons attesting competing claims is visible-but-unresolved, and that is the point"
///
/// Given: An inquirer I outside the horizon of identity X, holding two introductions for X whose locators name patrons P1 and P2 respectively; P1 and P2 each answer a currency query for X with an attestation whose field 2, the current key, differs from the other's.
/// When: I issues the currency query to both and receives both attestations.
/// Then: I's result for X reports a fork: both attestations are retained and neither is silently chosen as X's current key. I sends a notification to P1 and a notification to P2.
///
/// Interpretation: The notice is unspecified (design §22.3 item 3 records it as open); the test observes that a message is sent to each patron and checks neither its content nor its encoding.
#[test]
#[ignore = "acceptance ARC-15: owed at milestone 3"]
fn arc_15_report_a_fork_and_notify_both_patrons_when_curre() {
    todo!("ARC-15: Report a fork and notify both patrons when currency assertions for one identity diverge")
}
