//! GENERATED by tools/gen_stubs.py from acceptance.json.  Do not edit;
//! change the catalogue and regenerate.  Each stub is one acceptance test
//! still owed for this area.

/// Emit the genesis value as the back-pointer of a key's first transaction
///
/// Spec: wire-format.md §3.1; design §10.1
/// Milestone: 3.  Kind: positive.  Oracle: fixture.
///
/// Rule (wire-format.md §3.1): "A signer with no prior transaction uses the genesis value, SHA-256(the signer's keyhash) — over the 32 keyhash bytes themselves, not over a CBOR encoding of them — derivable by any verifier"
///
/// Given: A key K generated for the test with no transaction in its archive, and a counterparty P with an existing chain and a proof-of-presence record between K and P.
/// When: K signs its first transaction through the archive component: an adoption of K under P, K in field 1, field 8 naming that record.
/// Then: The adoption's key 0 list for K is exactly one 32-byte value equal to SHA-256 over the 32 bytes of K's keyhash. A verifier recomputing that value from K's keyhash reports K's chain as rooted at genesis at this record.
#[test]
#[ignore = "acceptance ARC-01: owed at milestone 3"]
fn arc_01_emit_the_genesis_value_as_the_back_pointer_of_a() {
    todo!("ARC-01: Emit the genesis value as the back-pointer of a key's first transaction")
}

/// Advance both signers' chains by an adoption, one back-pointer list per signer in signer order
///
/// Spec: wire-format.md §3.1; design §10.1
/// Milestone: 3.  Kind: positive.  Oracle: behaviour.
///
/// Rule (wire-format.md §3.1): "One back-pointer LIST per required signer, since each signer has their own independent archive. An adoption advances both the node's archive and the patron's."
/// Rule (wire-format.md §3.1): "Signer order is the order the type's own schema introduces its required signers"
///
/// Given: Node N whose archive head is h_N and patron P whose archive head is h_P, each the txid of an earlier transaction; a proof-of-presence record between them.
/// When: N and P sign an adoption of N under P; afterwards N signs a departure from P and P signs a disavowal of another subordinate.
/// Then: The adoption's key 0 is [[h_N], [h_P]] in that order, node then patron. N's departure carries key 0 [[txid(adoption)]] and P's disavowal carries key 0 [[txid(adoption)]]: each signer's next record back-points to the adoption.
#[test]
#[ignore = "acceptance ARC-02: owed at milestone 3"]
fn arc_02_advance_both_signers_chains_by_an_adoption_one_b() {
    todo!("ARC-02: Advance both signers' chains by an adoption, one back-pointer list per signer in signer order")
}

/// Report a chain that does not reach back when a signer's back-pointer names another signer's record
///
/// Spec: wire-format.md §3.1; wire-format.md §3.4
/// Milestone: 3.  Kind: negative.  Oracle: behaviour.
///
/// Rule (wire-format.md §3.1): "Getting this wrong is silent. Every hash and signature still verifies while each predecessor is attributed to the wrong signer, so a mismatch surfaces only when someone walks a chain and finds it does not reach back."
///
/// Given: N (head h_N) and P (head h_P) as in ARC-02, and an adoption of N under P whose key 0 is [[h_P], [h_N]], the two lists swapped, signed by both parties.
/// When: The adoption is verified structurally, then a walker follows N's chain backward from the adoption, fetching each named predecessor.
/// Then: Structural verification does not report the adoption malformed. The walk of N's chain fetches h_P, finds that N is not a signer of that record, and reports N's chain as not reaching back past the adoption; it reports no complete prefix for N from that head.
///
/// Interpretation: The section names the symptom, a walked chain that does not reach back, and no verdict word; the test reads a fetched predecessor that the named signer did not sign as that symptom, reported distinctly from malformed.
#[test]
#[ignore = "acceptance ARC-03: owed at milestone 3"]
fn arc_03_report_a_chain_that_does_not_reach_back_when_a_s() {
    todo!("ARC-03: Report a chain that does not reach back when a signer's back-pointer names another signer's record")
}

/// Open a relationship's series at counter 0 on adoption and advance it strictly on departure
///
/// Spec: wire-format.md §2.3; wire-format.md §4.2; design §6.2.1
/// Milestone: 3.  Kind: positive.  Oracle: behaviour.
///
/// Rule (wire-format.md §2.3): "a new adoption establishes its relationship's series, countersigned by the same party a reissue would need"
/// Rule (wire-format.md §4.2): "counter incremented within the current series"
/// Rule (wire-format.md §2.3): "Within one series a new counter must be strictly greater than the last one the verifier holds"
///
/// Given: Node N adopted under patron P, the adoption's field 3 locator carrying seqno {s, 0}; an observer O holding that adoption and nothing else in series s.
/// When: N signs a departure from P and O verifies it.
/// Then: The departure's field 3 is {s, c} with the same series s and c strictly greater than 0; O accepts it as newer than the adoption within series s. A second departure from N carrying {s, c} again, with different contents, is not accepted as newer.
#[test]
#[ignore = "acceptance ARC-04: owed at milestone 3"]
fn arc_04_open_a_relationship_s_series_at_counter_0_on_ado() {
    todo!("ARC-04: Open a relationship's series at counter 0 on adoption and advance it strictly on departure")
}

/// Accept a departure whose counter skips values in its series, and one in a series with no prior state
///
/// Spec: wire-format.md §2.3; design §6.2.1
/// Milestone: 3.  Kind: must-accept.  Oracle: behaviour.
///
/// Rule (wire-format.md §2.3): "not exactly previous+1, since a verifier may legitimately have missed intervening transactions and requiring contiguity would reject valid updates. Absence of prior state is not a failure."
///
/// Given: Observer O holds N's adoption under P at seqno {s, 0} and nothing else in series s, and holds no record at all in series s2.
/// When: O verifies a departure of N from P carrying seqno {s, 7}, and separately a departure carrying seqno {s2, 5}.
/// Then: Both are accepted: the gap from 0 to 7 within s is not reported as an error, and the record in s2 is not rejected for O holding no prior state in that series or ranked against the record in s.
#[test]
#[ignore = "acceptance ARC-05: owed at milestone 3"]
fn arc_05_accept_a_departure_whose_counter_skips_values_in() {
    todo!("ARC-05: Accept a departure whose counter skips values in its series, and one in a series with no prior state")
}

/// Accept a record timed at its predecessor's effective time or far ahead of the verifier's clock
///
/// Spec: wire-format.md §3.3
/// Milestone: 3.  Kind: must-accept.  Oracle: behaviour.
///
/// Rule (wire-format.md §3.3): "It is a floor, and not a rate limit. Everything at or after the predecessor's effective time is admissible, including days in the future"
/// Rule (wire-format.md §3.3): "Timestamps are not checked against a local clock at structural verification."
///
/// Given: Node N whose archive head is a transaction with timestamp t0, and a verifier whose local clock reads t_now, with t0 not later than t_now.
/// When: N signs two departures back-pointing to that head, one with timestamp exactly t0 and one with timestamp t_now plus thirty days; the verifier checks each.
/// Then: Both verify as structurally valid; neither is reported malformed.
#[test]
#[ignore = "acceptance ARC-06: owed at milestone 3"]
fn arc_06_accept_a_record_timed_at_its_predecessor_s_effec() {
    todo!("ARC-06: Accept a record timed at its predecessor's effective time or far ahead of the verifier's clock")
}

/// Carry both branch heads in the next ordinary transaction after the archive forks
///
/// Spec: wire-format.md §3.1; design §10.3; light-client-requirements.md §2
/// Milestone: 3.  Kind: positive.  Oracle: behaviour.
///
/// Rule (wire-format.md §3.1): "A signer whose archive has forked — typically from concurrent use of two devices — reunites it by supplying both branch heads in the next ordinary transaction."
/// Rule (light-client-requirements.md §2): "Merge automatically on noticing divergence."
///
/// Given: A client for N holding two heads of its own archive, h_a and h_b, neither reachable from the other: two records each back-pointing to the same earlier record of N.
/// When: The client signs its next ordinary transaction, a departure.
/// Then: The departure's key 0 list for N contains exactly h_a and h_b, sorted ascending bytewise; a walker from the departure reaches both branches and reports no unsatisfied back-pointer; no separate merge object is emitted.
#[test]
#[ignore = "acceptance ARC-07: owed at milestone 3"]
fn arc_07_carry_both_branch_heads_in_the_next_ordinary_tra() {
    todo!("ARC-07: Carry both branch heads in the next ordinary transaction after the archive forks")
}

/// Serve an archive fetch head-first in batches that continue from the previous reply's oldest record
///
/// Spec: wire-format.md §7.9; light-client-requirements.md §2
/// Milestone: 3.  Kind: positive.  Oracle: behaviour.
///
/// Rule (wire-format.md §7.9): "Paginate by re-requesting with field 2 set to the previous reply's field 4."
/// Rule (wire-format.md §7.9): "records in reverse chain order, head first"
///
/// Given: Subject S holding an unbroken chain of R records rooted at genesis and serving its own archive; the requester asks for max_records m, 1 to 256, with R greater than m so that more than one batch is needed.
/// When: A requester sends ArchiveRequest {1: S, 2: S's head, 3: m, 5: nonce}, then re-requests with field 2 set to each reply's field 4 until a reply's field 3 is false.
/// Then: Every reply's field 1 equals its request's nonce. The first reply's first envelope has txid equal to the requested head. Within each reply, each record's back-pointer list for S names the record that follows it. Each non-final reply's field 4 is the txid of its oldest record. The batches concatenated are the whole chain, and only the last reply's field 3 is false.
#[test]
#[ignore = "acceptance ARC-08: owed at milestone 3"]
fn arc_08_serve_an_archive_fetch_head_first_in_batches_tha() {
    todo!("ARC-08: Serve an archive fetch head-first in batches that continue from the previous reply's oldest record")
}

/// Reject an archive batch whose back-pointers do not match the records that follow
///
/// Spec: wire-format.md §7.9; light-client-requirements.md §2
/// Milestone: 3.  Kind: negative.  Oracle: behaviour.
///
/// Rule (wire-format.md §7.9): "The requester verifies the chain itself. Each returned record's back-pointers must match the record that follows it in the batch, and the first must match the requested head."
///
/// Given: A holder answering for subject S, and a requester asking with field 2 set to S's head.
/// When: The holder returns a batch in which one middle record has been replaced by another record of S that the preceding record's back-pointer does not name; in a second run the batch's first record is not the requested head.
/// Then: In the first run the requester reports the batch as failing chain verification at the first mismatching record, and the records from that point on are not reported as a verified prefix. In the second run it fails at record one.
#[test]
#[ignore = "acceptance ARC-09: owed at milestone 3"]
fn arc_09_reject_an_archive_batch_whose_back_pointers_do_n() {
    todo!("ARC-09: Reject an archive batch whose back-pointers do not match the records that follow")
}

/// Treat a short archive reply as no evidence about the archive's length
///
/// Spec: wire-format.md §7.9; light-client-requirements.md §2
/// Milestone: 3.  Kind: must-accept.  Oracle: behaviour.
///
/// Rule (wire-format.md §7.9): "A holder may refuse a request or return fewer records than asked for; a short reply is not evidence of a short archive, and a patron must not treat it as truncation."
///
/// Given: A requester holding S's head and asking for max_records m; a holder that returns k records, k less than m, whose oldest record's back-pointer names a record not in the batch, once with field 3 true and once with field 3 false.
/// When: The requester processes each reply.
/// Then: In both runs the requester's result marks the verified range as ending at an unfetched predecessor and does not record S's archive as beginning at the oldest returned record or as rooted at genesis; when the test continues, the requester's next request names the oldest returned record in field 2.
#[test]
#[ignore = "acceptance ARC-10: owed at milestone 3"]
fn arc_10_treat_a_short_archive_reply_as_no_evidence_about() {
    todo!("ARC-10: Treat a short archive reply as no evidence about the archive's length")
}

/// Mark an archive restored without a requested head as internally verified but not verified-complete
///
/// Spec: wire-format.md §7.9; light-client-requirements.md §2
/// Milestone: 3.  Kind: positive.  Oracle: behaviour.
///
/// Rule (wire-format.md §7.9): "Where field 2 was absent, there is no requested head to match: the chain still verifies internally, but its newestness is the holder's claim and nothing the requester holds can check it"
/// Rule (light-client-requirements.md §2): "never present a restored archive as verified-complete"
///
/// Given: A client for S that has lost its archive and holds no head; a holder serving S's chain from a record the holder claims as newest.
/// When: The client sends ArchiveRequest with field 2 absent and fetches the chain to its end.
/// Then: The client reports the chain as internally verified, every back-pointer matching the following record, and its status is distinguishable from a head-verified fetch: the restored archive is not marked verified-complete and the newest record is recorded as the holder's claim.
#[test]
#[ignore = "acceptance ARC-11: owed at milestone 3"]
fn arc_11_mark_an_archive_restored_without_a_requested_hea() {
    todo!("ARC-11: Mark an archive restored without a requested head as internally verified but not verified-complete")
}

/// Verify a history presented from an earlier head as an unbroken prefix
///
/// Spec: design §10.1; light-client-requirements.md §2; wire-format.md §4.1
/// Milestone: 3.  Kind: must-accept.  Oracle: behaviour.
///
/// Rule (design §10.1): "Any presented sequence is provably unbroken across the range shown, even though the archive is built and held by the subject."
/// Rule (light-client-requirements.md §2): "Presenting less history means presenting an earlier head; there is no other way to truncate, and none is needed."
///
/// Given: Subject S with a chain of R records rooted at genesis whose newest record is r_R; a patron evaluating an adoption of S.
/// When: S presents adoption field 7 = txid(r_j) for some j less than R, and the patron walks back from it, fetching from S.
/// Then: The walk reports the range r_j back to genesis as unbroken and rooted at genesis. The records after r_j are neither fetched nor reported missing, and the presentation is not rejected for naming a head that is not S's newest record.
#[test]
#[ignore = "acceptance ARC-12: owed at milestone 3"]
fn arc_12_verify_a_history_presented_from_an_earlier_head() {
    todo!("ARC-12: Verify a history presented from an earlier head as an unbroken prefix")
}

/// Stop a backward walk at a series reissue and report it as the presented range's root
///
/// Spec: design §10.1; design §10.0; wire-format.md §3.4
/// Milestone: 3.  Kind: positive.  Oracle: behaviour.
///
/// Rule (design §10.1): "supplies that root, asserting that history existed across the boundary without carrying what it contained, so the chain before it need not be retained or presented"
/// Rule (design §10.1): "That range is rooted at identity genesis, or at a checkpoint attesting that history existed before it"
///
/// Given: Subject S whose chain contains a patron-countersigned series reissue r_c, and whose records before r_c S no longer holds; a patron walking back from S's head.
/// When: The walk reaches r_c and requests its predecessor, which S does not serve.
/// Then: The result names the range from the head to r_c as unbroken and r_c as the range's root, a checkpoint distinguished from genesis; the unfetched record before r_c is reported as lying beyond the checkpoint, and no record is reported malformed.
///
/// Interpretation: The design says a checkpoint supplies a root and wire-format.md §3.4 says an unfetchable predecessor is incomplete rather than malformed; the test reads a stop at a countersigned reissue as a result distinct from a stop at an ordinary unfetchable record, which no sentence states.
#[test]
#[ignore = "acceptance ARC-13: owed at milestone 3"]
fn arc_13_stop_a_backward_walk_at_a_series_reissue_and_rep() {
    todo!("ARC-13: Stop a backward walk at a series reissue and report it as the presented range's root")
}

/// Evaluate a presented archive by the counterparties the patron already knows and nothing else
///
/// Spec: infra-client-requirements.md §5; design §16.7
/// Milestone: 3.  Kind: positive.  Oracle: behaviour.
///
/// Rule (infra-client-requirements.md §5): "Records naming identities you have never heard of are not weak evidence; they are no evidence"
/// Rule (infra-client-requirements.md §5): "Do not compute a total."
///
/// Given: The reference patron policy on infra node P, whose known identities are the set K; two unbroken presented chains for subject S: chain A whose counterparties are all in K, and chain B equal to A plus many records whose counterparties are all outside K. Weighing an archive is policy per infra-client-requirements.md §5; the test binds the reference policy only.
/// When: P evaluates each chain at adoption.
/// Then: The initial trust state P derives for S is identical for A and B. The result carries no field for archive length, record count or counterparty count.
#[test]
#[ignore = "acceptance ARC-14: owed at milestone 3"]
fn arc_14_evaluate_a_presented_archive_by_the_counterparti() {
    todo!("ARC-14: Evaluate a presented archive by the counterparties the patron already knows and nothing else")
}

/// Report a fork and notify both patrons when currency assertions for one identity diverge
///
/// Spec: design §9.0.2; wire-format.md §7.1
/// Milestone: 3.  Kind: positive.  Oracle: behaviour.
///
/// Rule (design §9.0.2): "A conforming inquirer who receives divergent assertions notifies both patrons."
/// Rule (wire-format.md §7.1): "What a caller can learn is a fork: two patrons attesting competing claims is visible-but-unresolved, and that is the point"
///
/// Given: An inquirer I outside the horizon of identity X, holding two introductions for X whose locators name patrons P1 and P2 respectively; P1 and P2 each answer a currency query for X with an attestation whose field 2, the current key, differs from the other's.
/// When: I issues the currency query to both and receives both attestations.
/// Then: I's result for X reports a fork: both attestations are retained and neither is silently chosen as X's current key. I sends a notification to P1 and a notification to P2.
///
/// Interpretation: The notice is unspecified (design §22.3 item 3 records it as open); the test observes that a message is sent to each patron and checks neither its content nor its encoding.
#[test]
#[ignore = "acceptance ARC-15: owed at milestone 3"]
fn arc_15_report_a_fork_and_notify_both_patrons_when_curre() {
    todo!("ARC-15: Report a fork and notify both patrons when currency assertions for one identity diverge")
}

/// Keep presence records, sealed captures and seeds when the chain is pruned at a checkpoint
///
/// Spec: light-client-requirements.md §2; design §10.1; design §10.0
/// Milestone: 3.  Kind: positive.  Oracle: behaviour.
///
/// Rule (light-client-requirements.md §2): "Pruning the chain must not delete presence records, sealed captures or capture seeds."
/// Rule (design §10.1): "Pruning is therefore permitted only beyond the window"
///
/// Given: A client for S whose chain holds a patron-countersigned series reissue r_c dated more than 730 days ago, with presence records before r_c, each with a sealed capture and a capture seed in the local store.
/// When: The user prunes the chain at r_c through the client's deliberate retention control.
/// Then: A backward walk from S's head now stops at r_c and the chain records before it are no longer served. Every presence record, sealed capture and capture seed dated before r_c is still present in the local store and returned by lookup by txid.
#[test]
#[ignore = "acceptance ARC-16: owed at milestone 3"]
fn arc_16_keep_presence_records_sealed_captures_and_seeds() {
    todo!("ARC-16: Keep presence records, sealed captures and seeds when the chain is pruned at a checkpoint")
}
