//! GENERATED by tools/gen_stubs.py from acceptance.json.  Do not edit;
//! change the catalogue and regenerate.  Each stub is one acceptance test
//! still owed for this area.

/// Obtain the strongest proximity channel the hardware supports and record which was achieved
///
/// Spec: light-client-requirements.md §1.3; design §7.6.3
/// Milestone: after-5.  Kind: positive.  Oracle: behaviour.
///
/// Rule (light-client-requirements.md §1.3): "Obtain the strongest proximity channel the hardware supports"
/// Rule (design §7.6.3): "record which channel it got"
///
/// Given: Two clients on a harness whose device layer offers NFC and optical channels and no UWB.
/// When: They run a presence ceremony to completion.
/// Then: The finalized record's proximity channels carry an NFC entry as the strongest achieved, and no UWB entry.
#[test]
#[ignore = "acceptance CER-01: owed at milestone after-5"]
fn cer_01_obtain_the_strongest_proximity_channel_the_hardw() {
    todo!("CER-01: Obtain the strongest proximity channel the hardware supports and record which was achieved")
}

/// Never present a weaker channel as a stronger one
///
/// Spec: light-client-requirements.md §1.3; design §7.6.3
/// Milestone: after-5.  Kind: negative.  Oracle: behaviour.
///
/// Rule (light-client-requirements.md §1.3): "Never present a weaker channel as a stronger one"
/// Rule (design §7.6.3): "No implementation should treat any single channel as proof that a counterparty's key is physically present."
///
/// Given: Two clients on a harness whose device layer offers only the optical channel.
/// When: They run a presence ceremony to completion.
/// Then: The record's proximity channels carry optical and nothing ranked above it; no NFC or UWB entry appears.
#[test]
#[ignore = "acceptance CER-02: owed at milestone after-5"]
fn cer_02_never_present_a_weaker_channel_as_a_stronger_one() {
    todo!("CER-02: Never present a weaker channel as a stronger one")
}

/// Run the guided capture with randomised prompts, three to five images over ten to fifteen seconds
///
/// Spec: light-client-requirements.md §1.3; design §7.5
/// Milestone: after-5.  Kind: positive.  Oracle: behaviour.
///
/// Rule (light-client-requirements.md §1.3): "Randomised prompts, 3-5 images over 10-15 seconds"
/// Rule (design §7.5): "The gain comes from diversity, not count."
///
/// Given: A client capturing its counterparty on the harness, run twice with independent randomness. The figures are chosen values (design §21).
/// When: Each capture sequence runs.
/// Then: Each sealed capture holds between three and five frames whose timestamps span between ten and fifteen seconds, and the two runs' prompt sequences differ.
#[test]
#[ignore = "acceptance CER-03: owed at milestone after-5"]
fn cer_03_run_the_guided_capture_with_randomised_prompts_t() {
    todo!("CER-03: Run the guided capture with randomised prompts, three to five images over ten to fifteen seconds")
}

/// Hold no decryptable likeness and no sealing key once the capture is sealed
///
/// Spec: light-client-requirements.md §1.3; design §7.5.2
/// Milestone: after-5.  Kind: negative.  Oracle: behaviour.
///
/// Rule (light-client-requirements.md §1.3): "Seal captures under the capture key the subject supplied, discard it once the capture is sealed, and never retain a key released later"
/// Rule (light-client-requirements.md §1.3): "A compliant client holds no decryptable likeness of another person"
///
/// Given: Client B has completed a ceremony with A and sealed its captures of A. The biometric engine, template format and sealed-store AEAD parameters are undecided (design §22.2) and are supplied to the test as parameters.
/// When: The test inspects B's persistent storage and asks B to open A's capture without a grant.
/// Then: Storage holds the sealed capture and A's seed for B's own captures only; no plaintext frame, no plaintext template and no k_capture for A's capture is present, and the open attempt fails.
#[test]
#[ignore = "acceptance CER-06: owed at milestone after-5"]
fn cer_06_hold_no_decryptable_likeness_and_no_sealing_key() {
    todo!("CER-06: Hold no decryptable likeness and no sealing key once the capture is sealed")
}

/// Query verifiers and answer queries without asking the operator
///
/// Spec: light-client-requirements.md §1.4; design Appendix A.3; design §7.3
/// Milestone: after-5.  Kind: positive.  Oracle: behaviour.
///
/// Rule (light-client-requirements.md §1.4): "Query verifiers automatically."
/// Rule (design Appendix A.3): "the witness's client observes a ceremony, tests the evidence and signs without pausing for its operator's approval"
/// Rule (design §7.3): "A's operator is not asked and is not told"
///
/// Given: A ceremony on the harness with a prompt hook that records every operator interaction on every client, including the verifiers'.
/// When: The ceremony runs and its queries are answered.
/// Then: Queries are issued and answered, and the hook records no prompt to any operator for querying, witnessing or answering; the verifier's operator receives no notification.
#[test]
#[ignore = "acceptance CER-17: owed at milestone after-5"]
fn cer_17_query_verifiers_and_answer_queries_without_askin() {
    todo!("CER-17: Query verifiers and answer queries without asking the operator")
}

/// Strip metadata from captured images before sealing
///
/// Spec: light-client-requirements.md §1.3
/// Milestone: after-5.  Kind: positive.  Oracle: behaviour.
///
/// Rule (light-client-requirements.md §1.3): "Strip metadata from captured images before storing them, and do not rely on camera-pipeline defaults."
///
/// Given: The harness camera returns frames carrying EXIF location, timestamp and device identifiers. The biometric engine, template format and sealed-store AEAD parameters are undecided (design §22.2) and are supplied to the test as parameters.
/// When: Client B captures and seals, and the test opens the capture with the subject's key.
/// Then: No frame in the opened capture carries EXIF or other metadata.
#[test]
#[ignore = "acceptance CER-23: owed at milestone after-5"]
fn cer_23_strip_metadata_from_captured_images_before_seali() {
    todo!("CER-23: Strip metadata from captured images before sealing")
}

/// Send the capture key directly to the selected verifier
///
/// Spec: light-client-requirements.md §1.3; design §7.5.2
/// Milestone: after-5.  Kind: positive.  Oracle: behaviour.
///
/// Rule (light-client-requirements.md §1.3): "Send the capture key directly to a selected verifier"
/// Rule (light-client-requirements.md §1.3): "bypassing the counterparty running the ceremony and every witness"
///
/// Given: Subject A in a ceremony run by C, with witnesses observing; C selects B as a verifier for A.
/// When: A's client releases the capture key.
/// Then: The KeyGrant is observed only on A's end-to-end path to B; no grant bytes appear on any path to C or to a witness.
#[test]
#[ignore = "acceptance CER-24: owed at milestone after-5"]
fn cer_24_send_the_capture_key_directly_to_the_selected_ve() {
    todo!("CER-24: Send the capture key directly to the selected verifier")
}

/// Disclose at capture time what the record will contain and who can read it
///
/// Spec: light-client-requirements.md §1.5; design §19.6
/// Milestone: after-5.  Kind: positive.  Oracle: behaviour.
///
/// Rule (light-client-requirements.md §1.5): "Tell participants what the record will contain and who will be able to read it"
/// Rule (design §19.6): "The reference client must disclose to a verifier or witness, at the moment they are asked, that their identity and relationship will be permanently recorded in a third party's evidence and readable by future evaluators."
///
/// Given: A ceremony on the harness with a notification hook on the participants', witnesses' and verifiers' clients.
/// When: The ceremony reaches capture and the witnesses and verifiers are asked.
/// Then: The hook records a disclosure to each participant before capture, and to each witness and verifier at the moment it is asked.
///
/// Interpretation: The content and form of the disclosure are not specified; the test asserts its occurrence and timing.
#[test]
#[ignore = "acceptance CER-26: owed at milestone after-5"]
fn cer_26_disclose_at_capture_time_what_the_record_will_co() {
    todo!("CER-26: Disclose at capture time what the record will contain and who can read it")
}
