//! GENERATED by tools/gen_stubs.py from acceptance.json.  Do not edit;
//! change the catalogue and regenerate.  Each stub is one acceptance test
//! still owed for this area.

/// Obtain the strongest proximity channel the hardware supports and record which was achieved
///
/// Spec: light-client-requirements.md §1.3; design §7.6.3
/// Milestone: after-5.  Kind: positive.  Oracle: behaviour.
///
/// Rule (light-client-requirements.md §1.3): "Obtain the strongest proximity channel the hardware supports"
/// Rule (design §7.6.3): "record which channel it got"
///
/// Given: Two clients on a harness whose device layer offers NFC and optical channels and no UWB.
/// When: They run a presence ceremony to completion.
/// Then: The finalized record's proximity channels carry an NFC entry as the strongest achieved, and no UWB entry.
#[test]
#[ignore = "acceptance CER-01: owed at milestone after-5"]
fn cer_01_obtain_the_strongest_proximity_channel_the_hardw() {
    todo!("CER-01: Obtain the strongest proximity channel the hardware supports and record which was achieved")
}

/// Never present a weaker channel as a stronger one
///
/// Spec: light-client-requirements.md §1.3; design §7.6.3
/// Milestone: after-5.  Kind: negative.  Oracle: behaviour.
///
/// Rule (light-client-requirements.md §1.3): "Never present a weaker channel as a stronger one"
/// Rule (design §7.6.3): "No implementation should treat any single channel as proof that a counterparty's key is physically present."
///
/// Given: Two clients on a harness whose device layer offers only the optical channel.
/// When: They run a presence ceremony to completion.
/// Then: The record's proximity channels carry optical and nothing ranked above it; no NFC or UWB entry appears.
#[test]
#[ignore = "acceptance CER-02: owed at milestone after-5"]
fn cer_02_never_present_a_weaker_channel_as_a_stronger_one() {
    todo!("CER-02: Never present a weaker channel as a stronger one")
}

/// Run the guided capture with randomised prompts, three to five images over ten to fifteen seconds
///
/// Spec: light-client-requirements.md §1.3; design §7.5
/// Milestone: after-5.  Kind: positive.  Oracle: behaviour.
///
/// Rule (light-client-requirements.md §1.3): "Randomised prompts, 3-5 images over 10-15 seconds"
/// Rule (design §7.5): "The gain comes from diversity, not count."
///
/// Given: A client capturing its counterparty on the harness, run twice with independent randomness. The figures are chosen values (design §21).
/// When: Each capture sequence runs.
/// Then: Each sealed capture holds between three and five frames whose timestamps span between ten and fifteen seconds, and the two runs' prompt sequences differ.
#[test]
#[ignore = "acceptance CER-03: owed at milestone after-5"]
fn cer_03_run_the_guided_capture_with_randomised_prompts_t() {
    todo!("CER-03: Run the guided capture with randomised prompts, three to five images over ten to fifteen seconds")
}

/// Hold no decryptable likeness and no sealing key once the capture is sealed
///
/// Spec: light-client-requirements.md §1.3; design §7.5.2
/// Milestone: after-5.  Kind: negative.  Oracle: behaviour.
///
/// Rule (light-client-requirements.md §1.3): "Seal captures under the capture key the subject supplied, discard it once the capture is sealed, and never retain a key released later"
/// Rule (light-client-requirements.md §1.3): "A compliant client holds no decryptable likeness of another person"
///
/// Given: Client B has completed a ceremony with A and sealed its captures of A. The biometric engine, template format and sealed-store AEAD parameters are undecided (design §22.2) and are supplied to the test as parameters.
/// When: The test inspects B's persistent storage and asks B to open A's capture without a grant.
/// Then: Storage holds the sealed capture and A's seed for B's own captures only; no plaintext frame, no plaintext template and no k_capture for A's capture is present, and the open attempt fails.
#[test]
#[ignore = "acceptance CER-06: owed at milestone after-5"]
fn cer_06_hold_no_decryptable_likeness_and_no_sealing_key() {
    todo!("CER-06: Hold no decryptable likeness and no sealing key once the capture is sealed")
}

/// Retain no released key after answering
///
/// Spec: light-client-requirements.md §1.3; wire-format.md §5.5
/// Milestone: after-5.  Kind: negative.  Oracle: behaviour.
///
/// Rule (light-client-requirements.md §1.3): "never retain a key released later"
/// Rule (wire-format.md §5.5): "An absent capture key is `unavailable`, not `inconclusive`"
///
/// Given: Verifier B answered a consented query about A using a KeyGrant A sent.
/// When: A second consented query about the same record arrives with no new grant, and the test inspects B's storage.
/// Then: The released key is absent from storage and the second query is answered `unavailable`.
#[test]
#[ignore = "acceptance CER-07: owed at milestone after-5"]
fn cer_07_retain_no_released_key_after_answering() {
    todo!("CER-07: Retain no released key after answering")
}

/// Open only the capture the grant names and keep the others sealed
///
/// Spec: wire-format.md §7.3; design §7.5.2.8
/// Milestone: after-5.  Kind: positive.  Oracle: behaviour.
///
/// Rule (wire-format.md §7.3): "the grant names the one to open"
/// Rule (design §7.5.2.8): "A ceremony seals a new capture; it does not replace an earlier one."
///
/// Given: Verifier B holds two sealed captures of A from records R1 and R2, each under its own seed.
/// When: A consented query arrives with a KeyGrant whose field 1 is R2's txid.
/// Then: B answers from R2's capture; R1's capture is still sealed afterwards and R1's key was never derived.
#[test]
#[ignore = "acceptance CER-08: owed at milestone after-5"]
fn cer_08_open_only_the_capture_the_grant_names_and_keep_t() {
    todo!("CER-08: Open only the capture the grant names and keep the others sealed")
}

/// Grant against the most recent eligible capture by default
///
/// Spec: design §7.5.2.8; light-client-requirements.md §1.3
/// Milestone: after-5.  Kind: positive.  Oracle: behaviour.
///
/// Rule (design §7.5.2.8): "Querying prefers the most recent eligible capture"
/// Rule (light-client-requirements.md §1.3): "when you are the subject releasing a key, the most recent eligible capture is the default"
///
/// Given: Subject A has met verifier B twice, in records R1 then R2, both eligible, and has set no preference.
/// When: A's client releases a capture key for a query directed at B.
/// Then: The KeyGrant's field 1 is R2's txid.
#[test]
#[ignore = "acceptance CER-09: owed at milestone after-5"]
fn cer_09_grant_against_the_most_recent_eligible_capture_b() {
    todo!("CER-09: Grant against the most recent eligible capture by default")
}

/// Treat a grant unattached to a countersigned query as malformed
///
/// Spec: light-client-requirements.md §1.3; wire-format.md §7.3
/// Milestone: after-5.  Kind: negative.  Oracle: behaviour.
///
/// Rule (light-client-requirements.md §1.3): "A grant arriving unattached to a query the subject countersigned is an unsolicited key release; treat one as malformed rather than opening your store."
/// Rule (wire-format.md §7.3): "Field 2 binds the grant to a query."
///
/// Given: Verifier B holds a sealed capture of A. No query about A has arrived, and the buffering bound is the test's parameter since the wire leaves it local.
/// When: A KeyGrant from A naming that record and a query_id B has not seen arrives, and the bound elapses.
/// Then: B opens nothing, answers nothing, and the grant is discarded when the bound elapses.
#[test]
#[ignore = "acceptance CER-10: owed at milestone after-5"]
fn cer_10_treat_a_grant_unattached_to_a_countersigned_quer() {
    todo!("CER-10: Treat a grant unattached to a countersigned query as malformed")
}

/// Reject a grant from anyone but the subject, and let the first authenticated grant stand
///
/// Spec: wire-format.md §7.3
/// Milestone: after-5.  Kind: negative.  Oracle: behaviour.
///
/// Rule (wire-format.md §7.3): "The authenticated sender MUST be the subject"
/// Rule (wire-format.md §7.3): "Duplicates are ignored, and so is a differing second grant for a query already satisfied"
///
/// Given: Verifier B holds a consented query about A. A grant for it arrives from C, then a valid grant from A, then a differing grant from A for the same query.
/// When: B processes the three in order.
/// Then: The grant from C is rejected and opens nothing; the first grant from A is used to answer; the third changes nothing and B's answer is not revised.
#[test]
#[ignore = "acceptance CER-11: owed at milestone after-5"]
fn cer_11_reject_a_grant_from_anyone_but_the_subject_and_l() {
    todo!("CER-11: Reject a grant from anyone but the subject, and let the first authenticated grant stand")
}

/// Answer `unavailable` for a grant naming a record you do not hold
///
/// Spec: wire-format.md §7.3
/// Milestone: after-5.  Kind: negative.  Oracle: behaviour.
///
/// Rule (wire-format.md §7.3): "A grant naming a record the holder does not hold yields `unavailable`"
///
/// Given: Verifier B holds no sealed capture for record R, and a consented query about A names R in its grant.
/// When: The grant and query arrive.
/// Then: B's signed response carries result `unavailable`.
#[test]
#[ignore = "acceptance CER-12: owed at milestone after-5"]
fn cer_12_answer_unavailable_for_a_grant_naming_a_record_y() {
    todo!("CER-12: Answer `unavailable` for a grant naming a record you do not hold")
}

/// Reject a query without consent, or not addressed to you, by closing the stream
///
/// Spec: wire-format.md §5.6; design §7.4.2
/// Milestone: after-5.  Kind: negative.  Oracle: behaviour.
///
/// Rule (wire-format.md §5.6): "a query arriving without consent is rejected"
/// Rule (wire-format.md §5.6): "a receiving verifier rejects a query not addressed to it before any processing"
/// Rule (design §7.4.2): "No verifier may answer an identity-comparison request unless the subject of that request has signed it."
///
/// Given: Verifier B receives, on separate type-4 streams, a query with no consent beside it, a query whose consent does not verify under the subject, and a query whose field 7 names another verifier.
/// When: B processes each.
/// Then: Each stream is closed with no VerifierResponse sent, and no comparison is run for any of them.
#[test]
#[ignore = "acceptance CER-13: owed at milestone after-5"]
fn cer_13_reject_a_query_without_consent_or_not_addressed() {
    todo!("CER-13: Reject a query without consent, or not addressed to you, by closing the stream")
}

/// Deliver a copy of your signed response to the subject
///
/// Spec: wire-format.md §5.6; design §7.4.2
/// Milestone: after-5.  Kind: positive.  Oracle: behaviour.
///
/// Rule (wire-format.md §5.6): "A response about a subject is also delivered to that subject"
/// Rule (design §7.4.2): "a verifier answering a query about subject S sends a copy of its signed response to S as well as to the querier"
///
/// Given: Verifier B answers a consented query from C about subject A.
/// When: B sends its response.
/// Then: The signed VerifierResponse reaches C, and a copy with identical bytes reaches A over the association the grant established.
#[test]
#[ignore = "acceptance CER-14: owed at milestone after-5"]
fn cer_14_deliver_a_copy_of_your_signed_response_to_the_su() {
    todo!("CER-14: Deliver a copy of your signed response to the subject")
}

/// Report a failed decryption as `inconclusive`, never as `no-match`
///
/// Spec: wire-format.md §5.5; light-client-requirements.md §1.3; design §7.5.2.7
/// Milestone: after-5.  Kind: negative.  Oracle: behaviour.
///
/// Rule (wire-format.md §5.5): "`inconclusive` covers a failure to decrypt, and `no-match` never does."
/// Rule (light-client-requirements.md §1.3): "Report a decryption failure as `inconclusive`, never as `no-match`."
/// Rule (design §7.5.2.7): "Truncated or unauthenticated ciphertext is a decryption failure"
///
/// Given: Verifier B's sealed capture of A has been truncated on disk, and a consented query with a valid grant arrives. The biometric engine, template format and sealed-store AEAD parameters are undecided (design §22.2) and are supplied to the test as parameters.
/// When: B attempts to open and compare.
/// Then: B's signed response carries `inconclusive` with basis 0 and the query's template version, and never `no-match`.
#[test]
#[ignore = "acceptance CER-15: owed at milestone after-5"]
fn cer_15_report_a_failed_decryption_as_inconclusive_never() {
    todo!("CER-15: Report a failed decryption as `inconclusive`, never as `no-match`")
}

/// Reject a second, different profile within one ceremony
///
/// Spec: design §7.4.1; design §7.4.2
/// Milestone: after-5.  Kind: negative.  Oracle: behaviour.
///
/// Rule (design §7.4.1): "one profile per ceremony, or the verifier rejects"
/// Rule (design §7.4.2): "can require that all queries from one ceremony carry the identical profile"
///
/// Given: Verifier B has answered a consented query bound to ceremony pre-commitment P carrying profile F1.
/// When: A second consented query bound to P arrives carrying a different profile F2.
/// Then: B rejects it and sends no second response for that ceremony.
///
/// Interpretation: Whether the subject's client also refuses to countersign a differing second profile is stated as a capability rather than a rule, so only the verifier side is asserted.
#[test]
#[ignore = "acceptance CER-16: owed at milestone after-5"]
fn cer_16_reject_a_second_different_profile_within_one_cer() {
    todo!("CER-16: Reject a second, different profile within one ceremony")
}

/// Query verifiers and answer queries without asking the operator
///
/// Spec: light-client-requirements.md §1.4; design Appendix A.3; design §7.3
/// Milestone: after-5.  Kind: positive.  Oracle: behaviour.
///
/// Rule (light-client-requirements.md §1.4): "Query verifiers automatically."
/// Rule (design Appendix A.3): "the witness's client observes a ceremony, tests the evidence and signs without pausing for its operator's approval"
/// Rule (design §7.3): "A's operator is not asked and is not told"
///
/// Given: A ceremony on the harness with a prompt hook that records every operator interaction on every client, including the verifiers'.
/// When: The ceremony runs and its queries are answered.
/// Then: Queries are issued and answered, and the hook records no prompt to any operator for querying, witnessing or answering; the verifier's operator receives no notification.
#[test]
#[ignore = "acceptance CER-17: owed at milestone after-5"]
fn cer_17_query_verifiers_and_answer_queries_without_askin() {
    todo!("CER-17: Query verifiers and answer queries without asking the operator")
}

/// Withhold disclosable fields by default, and let the digests travel
///
/// Spec: light-client-requirements.md §1.3; design §8.1.1.3
/// Milestone: after-5.  Kind: positive.  Oracle: behaviour.
///
/// Rule (light-client-requirements.md §1.3): "Withhold a presence record's disclosable fields by default"
/// Rule (design §8.1.1.3): "The digest count and labels always travel, so a recipient knows a field exists and was withheld."
///
/// Given: Client A holds a finalized record with all seven disclosable fields, and has given no instruction to reveal.
/// When: A presents the record to a party that is not a prospective patron.
/// Then: The presentation reveals none of the seven fields and carries every field's digest and label, and the envelope signature verifies over it.
#[test]
#[ignore = "acceptance CER-18: owed at milestone after-5"]
fn cer_18_withhold_disclosable_fields_by_default_and_let_t() {
    todo!("CER-18: Withhold disclosable fields by default, and let the digests travel")
}

/// Withhold your envelope signature from a body omitting a response you hold
///
/// Spec: light-client-requirements.md §1.4; wire-format.md §5.6
/// Milestone: after-5.  Kind: negative.  Oracle: behaviour.
///
/// Rule (light-client-requirements.md §1.4): "Withhold your envelope signature from a proposed body omitting a verifier response you hold"
/// Rule (wire-format.md §5.6): "a subject holding a response withholds its envelope signature from a proposed body that omits it"
///
/// Given: Subject A holds a copy of verifier B's response about A, delivered by B; the counterparty proposes a final body without it.
/// When: A's client is asked to sign the proposed body.
/// Then: No envelope signature by A is produced for that body; a body that includes B's response is signed.
#[test]
#[ignore = "acceptance CER-19: owed at milestone after-5"]
fn cer_19_withhold_your_envelope_signature_from_a_body_omi() {
    todo!("CER-19: Withhold your envelope signature from a body omitting a response you hold")
}

/// Refuse to sign a record attributing to you a witness you did not nominate
///
/// Spec: light-client-requirements.md §1.1
/// Milestone: after-5.  Kind: negative.  Oracle: model.
///
/// Rule (light-client-requirements.md §1.1): "Refuse to sign a record attributing to you a witness you did not nominate"
///
/// Given: Participant A nominated witnesses W1 and W2; the proposed body attributes W3 to A.
/// When: A's client is asked to sign.
/// Then: No envelope signature by A is produced; the same body with W3 attributed to the counterparty is signed.
#[test]
#[ignore = "acceptance CER-20: owed at milestone after-5"]
fn cer_20_refuse_to_sign_a_record_attributing_to_you_a_wit() {
    todo!("CER-20: Refuse to sign a record attributing to you a witness you did not nominate")
}

/// Tell the user when your own nominees are absent or outnumbered
///
/// Spec: light-client-requirements.md §1.1
/// Milestone: after-5.  Kind: positive.  Oracle: behaviour.
///
/// Rule (light-client-requirements.md §1.1): "Check the `nominated_by` split before you sign, and tell the user when your own nominees are absent or outnumbered."
///
/// Given: Participant A nominated two witnesses; the proposed body carries five witnesses of which one is A's, with a notification hook on A's client.
/// When: A's client checks the split before signing.
/// Then: The hook records a notice to the user that A's nominees are outnumbered, before any signature is produced.
///
/// Interpretation: The form of the notice is not specified; the test asserts that one is raised before signing.
#[test]
#[ignore = "acceptance CER-21: owed at milestone after-5"]
fn cer_21_tell_the_user_when_your_own_nominees_are_absent() {
    todo!("CER-21: Tell the user when your own nominees are absent or outnumbered")
}

/// Decline to witness a ceremony whose claimed start is far from your clock
///
/// Spec: light-client-requirements.md §1.2
/// Milestone: after-5.  Kind: negative.  Oracle: behaviour.
///
/// Rule (light-client-requirements.md §1.2): "Decline to witness a ceremony whose claimed `started_at` is far from the time you observe."
///
/// Given: Witness W with tolerance T, chosen by the test since the requirement leaves it to the witness, is nominated for a ceremony whose started_at is more than T from W's clock.
/// When: W's client is asked to sign.
/// Then: No witness signature by W is produced; the same ceremony with started_at within T is signed.
#[test]
#[ignore = "acceptance CER-22: owed at milestone after-5"]
fn cer_22_decline_to_witness_a_ceremony_whose_claimed_star() {
    todo!("CER-22: Decline to witness a ceremony whose claimed start is far from your clock")
}

/// Strip metadata from captured images before sealing
///
/// Spec: light-client-requirements.md §1.3
/// Milestone: after-5.  Kind: positive.  Oracle: behaviour.
///
/// Rule (light-client-requirements.md §1.3): "Strip metadata from captured images before storing them, and do not rely on camera-pipeline defaults."
///
/// Given: The harness camera returns frames carrying EXIF location, timestamp and device identifiers. The biometric engine, template format and sealed-store AEAD parameters are undecided (design §22.2) and are supplied to the test as parameters.
/// When: Client B captures and seals, and the test opens the capture with the subject's key.
/// Then: No frame in the opened capture carries EXIF or other metadata.
#[test]
#[ignore = "acceptance CER-23: owed at milestone after-5"]
fn cer_23_strip_metadata_from_captured_images_before_seali() {
    todo!("CER-23: Strip metadata from captured images before sealing")
}

/// Send the capture key directly to the selected verifier
///
/// Spec: light-client-requirements.md §1.3; design §7.5.2
/// Milestone: after-5.  Kind: positive.  Oracle: behaviour.
///
/// Rule (light-client-requirements.md §1.3): "Send the capture key directly to a selected verifier"
/// Rule (light-client-requirements.md §1.3): "bypassing the counterparty running the ceremony and every witness"
///
/// Given: Subject A in a ceremony run by C, with witnesses observing; C selects B as a verifier for A.
/// When: A's client releases the capture key.
/// Then: The KeyGrant is observed only on A's end-to-end path to B; no grant bytes appear on any path to C or to a witness.
#[test]
#[ignore = "acceptance CER-24: owed at milestone after-5"]
fn cer_24_send_the_capture_key_directly_to_the_selected_ve() {
    todo!("CER-24: Send the capture key directly to the selected verifier")
}

/// Keep the anti-oracle aggregate as a lock, not a log
///
/// Spec: light-client-requirements.md §1.4; design §7.4.1
/// Milestone: after-5.  Kind: positive.  Oracle: behaviour.
///
/// Rule (light-client-requirements.md §1.4): "A counter per requester and per ceremony window, discarded when the window closes"
/// Rule (design §7.4.1): "The aggregate is a lock, not a log."
///
/// Given: Subject A, with the ceremony window W chosen by the test.
/// When: During W a requester exceeds the per-requester limit; after W closes the test inspects A's storage.
/// Then: The excess query receives no grant, and after W no record of the requester or of the count remains.
#[test]
#[ignore = "acceptance CER-25: owed at milestone after-5"]
fn cer_25_keep_the_anti_oracle_aggregate_as_a_lock_not_a_l() {
    todo!("CER-25: Keep the anti-oracle aggregate as a lock, not a log")
}

/// Disclose at capture time what the record will contain and who can read it
///
/// Spec: light-client-requirements.md §1.5; design §19.6
/// Milestone: after-5.  Kind: positive.  Oracle: behaviour.
///
/// Rule (light-client-requirements.md §1.5): "Tell participants what the record will contain and who will be able to read it"
/// Rule (design §19.6): "The reference client must disclose to a verifier or witness, at the moment they are asked, that their identity and relationship will be permanently recorded in a third party's evidence and readable by future evaluators."
///
/// Given: A ceremony on the harness with a notification hook on the participants', witnesses' and verifiers' clients.
/// When: The ceremony reaches capture and the witnesses and verifiers are asked.
/// Then: The hook records a disclosure to each participant before capture, and to each witness and verifier at the moment it is asked.
///
/// Interpretation: The content and form of the disclosure are not specified; the test asserts its occurrence and timing.
#[test]
#[ignore = "acceptance CER-26: owed at milestone after-5"]
fn cer_26_disclose_at_capture_time_what_the_record_will_co() {
    todo!("CER-26: Disclose at capture time what the record will contain and who can read it")
}

/// Count qualifying bundle records once by txid when computing n
///
/// Spec: light-client-requirements.md §1.4
/// Milestone: after-5.  Kind: positive.  Oracle: fixture.
///
/// Rule (light-client-requirements.md §1.4): "count qualifying ones once by txid"
/// Rule (light-client-requirements.md §1.4): "Compute n over the bundle handed to you, and treat it as your counterparty's claim"
///
/// Given: A bundle handed to the selector containing four qualifying records, two of them the same record twice.
/// When: The selector computes n.
/// Then: n is 3, and the required response count follows from 3.
#[test]
#[ignore = "acceptance CER-27: owed at milestone after-5"]
fn cer_27_count_qualifying_bundle_records_once_by_txid_whe() {
    todo!("CER-27: Count qualifying bundle records once by txid when computing n")
}

/// Answer `unavailable` to a claimed `met` your own records refute
///
/// Spec: wire-format.md §5.6
/// Milestone: after-5.  Kind: negative.  Oracle: behaviour.
///
/// Rule (wire-format.md §5.6): "A claimed `met` the verifier's own records refute is answered `unavailable`"
///
/// Given: Verifier B holds no record of ever having met selector C, and a consented query from C arrives with selection basis 0.
/// When: B processes the query.
/// Then: B's signed response carries `unavailable` and no comparison is run.
#[test]
#[ignore = "acceptance CER-28: owed at milestone after-5"]
fn cer_28_answer_unavailable_to_a_claimed_met_your_own_rec() {
    todo!("CER-28: Answer `unavailable` to a claimed `met` your own records refute")
}

/// Keep a late response beside its record, never inside it, and discard it with the record
///
/// Spec: wire-format.md §7.4
/// Milestone: after-5.  Kind: positive.  Oracle: behaviour.
///
/// Rule (wire-format.md §7.4): "It does not amend the record it names."
/// Rule (wire-format.md §7.4): "The response must carry a `query_id` the subject countersigned for that ceremony"
/// Rule (wire-format.md §7.4): "Retention follows the record it supplements."
///
/// Given: A holder keeps record R; a LateResponse naming R with a countersigned query_id arrives, then one with an unconsented query_id.
/// When: The holder processes both, then later discards R.
/// Then: R's bytes and txid are unchanged; the first LateResponse is held beside R and the second is rejected; after R is discarded the LateResponse is gone too.
#[test]
#[ignore = "acceptance CER-29: owed at milestone after-5"]
fn cer_29_keep_a_late_response_beside_its_record_never_ins() {
    todo!("CER-29: Keep a late response beside its record, never inside it, and discard it with the record")
}
