//! GENERATED by tools/gen_stubs.py from acceptance.json.  Do not edit;
//! change the catalogue and regenerate.  Each stub is one acceptance test
//! still owed for this area.

/// Issue a fresh patron attestation for a subordinate, signed under the currency tag
///
/// Spec: infra-client-requirements.md §3; wire-format.md §7.1
/// Milestone: 4.  Kind: positive.  Oracle: behaviour.
///
/// Rule (infra-client-requirements.md §3): "Issue currency attestations for subordinates"
/// Rule (wire-format.md §7.1): "~10 h default; hours, not days"
///
/// Given: Infra node P has adopted S, whose current key is k. The attestation lifetime L is chosen by the test, since design §21.1 leaves its value unset.
/// When: S requests currency from P.
/// Then: A CurrencyReply with code 0 carries an attestation whose field 1 is S, field 2 is k, field 5 is 0, field 6 is P, whose field 4 minus field 3 equals L, and whose COSE_Sign1 verifies under P's classical key with external_aad rhtn/1:currency.
#[test]
#[ignore = "acceptance CUR-01: owed at milestone 4"]
fn cur_01_issue_a_fresh_patron_attestation_for_a_subordina() {
    todo!("CUR-01: Issue a fresh patron attestation for a subordinate, signed under the currency tag")
}

/// Refresh by issuing anew, never by extending
///
/// Spec: infra-client-requirements.md §3; wire-format.md §7.1
/// Milestone: 4.  Kind: negative.  Oracle: behaviour.
///
/// Rule (infra-client-requirements.md §3): "Issue fresh, never extend stale."
/// Rule (wire-format.md §7.1): "There is no "extend" operation and no field for one, deliberately."
///
/// Given: S holds an attestation A from P, issued at t0.
/// When: S requests currency from P again at t1 > t0.
/// Then: The reply's attestation has field 3 later than A's field 3 and a signature different from A's. No message from P carries A's fields 1 to 3 with a later field 4.
#[test]
#[ignore = "acceptance CUR-02: owed at milestone 4"]
fn cur_02_refresh_by_issuing_anew_never_by_extending() {
    todo!("CUR-02: Refresh by issuing anew, never by extending")
}

/// Issue nothing for a key you have superseded
///
/// Spec: infra-client-requirements.md §3; design §9.0.2
/// Milestone: 4.  Kind: negative.  Oracle: model.
///
/// Rule (infra-client-requirements.md §3): "Issue only for the key you currently record."
/// Rule (infra-client-requirements.md §3): "after it you have nothing to issue for the old key and MUST NOT"
///
/// Given: P recorded S under k1, then received and verified a recovery adoption binding S to k2.
/// When: A CurrencyRequest naming S arrives at P.
/// Then: Every attestation P issues for S afterwards carries k2 in field 2; none carries k1.
#[test]
#[ignore = "acceptance CUR-03: owed at milestone 4"]
fn cur_03_issue_nothing_for_a_key_you_have_superseded() {
    todo!("CUR-03: Issue nothing for a key you have superseded")
}

/// Answer a request you cannot issue for with code 1, not with an invented attestation and not with silence
///
/// Spec: wire-format.md §7.1
/// Milestone: 4.  Kind: positive.  Oracle: behaviour.
///
/// Rule (wire-format.md §7.1): "So the answers are: an attestation, or nothing."
/// Rule (wire-format.md §7.1): "Code 1 says the responder cannot issue rather than inventing one"
///
/// Given: Node P holds no record of subject X.
/// When: A CurrencyRequest naming X with nonce n arrives on an authenticated session.
/// Then: A CurrencyReply is observed with field 1 equal to n, field 2 equal to 1 and field 3 absent.
#[test]
#[ignore = "acceptance CUR-04: owed at milestone 4"]
fn cur_04_answer_a_request_you_cannot_issue_for_with_code() {
    todo!("CUR-04: Answer a request you cannot issue for with code 1, not with an invented attestation and not with silence")
}

/// Fail closed on a trust-bearing operation while the counterparty's staple is expired or missing
///
/// Spec: design §12.6.5; wire-format.md §7.1
/// Milestone: 4.  Kind: negative.  Oracle: behaviour.
///
/// Rule (design §12.6.5): "Fail closed. Current control of the acting credential must be established first"
/// Rule (design §12.6.5): "falls back to a lookup (§9.0.2) only if the staple is absent or expired"
///
/// Given: Node N is introduced to X with a staple whose field 4 is in N's past, and N's clock is authoritative for the test.
/// When: X proposes an adoption with N.
/// Then: N emits no countersigned adoption while the staple is expired. A CurrencyRequest naming X is observed leaving N, and only after a CurrencyReply with code 0 carrying an unexpired attestation does the adoption proceed.
#[test]
#[ignore = "acceptance CUR-05: owed at milestone 4"]
fn cur_05_fail_closed_on_a_trust_bearing_operation_while_t() {
    todo!("CUR-05: Fail closed on a trust-bearing operation while the counterparty's staple is expired or missing")
}

/// Fail open for routine payload when the staple is expired
///
/// Spec: design §12.6.5
/// Milestone: 4.  Kind: must-accept.  Oracle: behaviour.
///
/// Rule (design §12.6.5): "Fail open. Proceed"
/// Rule (design §12.6.5): "a user offline for a day arrives with a stale staple, can still receive messages, and cannot spend accumulated standing until they refresh"
///
/// Given: Client S attaches to its serving node holding only an expired staple.
/// When: Queued payload for S is available for delivery.
/// Then: Delivery proceeds. An implementation that withholds routine payload until currency is refreshed fails.
#[test]
#[ignore = "acceptance CUR-06: owed at milestone 4"]
fn cur_06_fail_open_for_routine_payload_when_the_staple_is() {
    todo!("CUR-06: Fail open for routine payload when the staple is expired")
}

/// Serve nothing under a binding you hold supersession evidence for, whatever the staple says
///
/// Spec: design §12.6.5
/// Milestone: 4.  Kind: negative.  Oracle: model.
///
/// Rule (design §12.6.5): "Fail-open is for ignorance, never for knowledge"
/// Rule (design §12.6.5): "MUST NOT continue serving it"
///
/// Given: Node N holds a verified reissue chain that supersedes S's key k1, and is then presented with an unexpired, validly signed attestation naming S under k1.
/// When: S attempts to attach under k1 and requests delivery.
/// Then: No session is served under k1 and nothing is delivered under it; the unexpired staple does not restore service.
#[test]
#[ignore = "acceptance CUR-07: owed at milestone 4"]
fn cur_07_serve_nothing_under_a_binding_you_hold_supersess() {
    todo!("CUR-07: Serve nothing under a binding you hold supersession evidence for, whatever the staple says")
}

/// Issue secondhand as a sibling from replicated state when the patron is unreachable
///
/// Spec: design §12.6.5.1; wire-format.md §7.1
/// Milestone: 4.  Kind: positive.  Oracle: model.
///
/// Rule (design §12.6.5.1): "Sibling issuance from replicated state, marked secondhand and weighted slightly lower"
/// Rule (wire-format.md §7.1): "1 sibling (secondhand)"
///
/// Given: P adopted S; P's sibling P' holds P's replicated adoption record; P is unreachable.
/// When: S requests currency from P'.
/// Then: A CurrencyReply with code 0 carries an attestation whose field 5 is 1, field 6 is P', and whose field 3 is fresh, signed by P'.
#[test]
#[ignore = "acceptance CUR-08: owed at milestone 4"]
fn cur_08_issue_secondhand_as_a_sibling_from_replicated_st() {
    todo!("CUR-08: Issue secondhand as a sibling from replicated state when the patron is unreachable")
}

/// Issue as grandpatron when the patron and its siblings are unreachable
///
/// Spec: design §12.6.5.1; wire-format.md §7.1
/// Milestone: 4.  Kind: positive.  Oracle: model.
///
/// Rule (design §12.6.5.1): "Grandpatron issuance. It holds the adoption record anyway"
/// Rule (wire-format.md §7.1): "2 grandpatron"
///
/// Given: P adopted S; P's patron G holds the adoption record; P and every sibling of P are unreachable.
/// When: S requests currency from G.
/// Then: A CurrencyReply with code 0 carries an attestation whose field 5 is 2 and field 6 is G, signed by G.
#[test]
#[ignore = "acceptance CUR-09: owed at milestone 4"]
fn cur_09_issue_as_grandpatron_when_the_patron_and_its_sib() {
    todo!("CUR-09: Issue as grandpatron when the patron and its siblings are unreachable")
}

/// Stay frozen for trust-bearing operations when every issuer is unreachable, and recover by adopting elsewhere
///
/// Spec: design §12.6.5.1; design §12.6.5
/// Milestone: 4.  Kind: liveness.  Oracle: behaviour.
///
/// Rule (design §12.6.5.1): "no issuance path exists, and affected nodes are frozen for trust-bearing operations until recovery or re-adoption elsewhere"
/// Rule (design §12.6.5.1): "Adopt at a new patron (§6.2). The designed remedy for a bad patron works identically for a dead one"
/// Rule (design §12.6.5): "An operation is trust-bearing if it would create, transfer or spend social standing"
///
/// Given: S's patron, the patron's siblings and the grandpatron are all unreachable and S's staple has expired.
/// When: S attempts a peering, then adopts at a reachable patron P2 and obtains an attestation from P2, then attempts the peering again.
/// Then: The first attempt produces no peering transaction. After adoption at P2 and a code-0 CurrencyReply from P2, the peering transaction is produced.
#[test]
#[ignore = "acceptance CUR-10: owed at milestone 4"]
fn cur_10_stay_frozen_for_trust_bearing_operations_when_ev() {
    todo!("CUR-10: Stay frozen for trust-bearing operations when every issuer is unreachable, and recover by adopting elsewhere")
}

/// Ask the introducer for a fresher staple before querying the subject's patron
///
/// Spec: design §12.6.5
/// Milestone: 4.  Kind: positive.  Oracle: behaviour.
///
/// Rule (design §12.6.5): "a caller with a stale staple should ask its introducer first"
///
/// Given: Client N, introduced to X by I, holds a stale staple for X and has sessions reaching both I and X's patron.
/// When: N needs current control of X's credential for a trust-bearing operation.
/// Then: N's first CurrencyRequest naming X is observed on its session toward I, and none toward X's patron unless I answers with code 1 or not at all.
#[test]
#[ignore = "acceptance CUR-11: owed at milestone 4"]
fn cur_11_ask_the_introducer_for_a_fresher_staple_before_q() {
    todo!("CUR-11: Ask the introducer for a fresher staple before querying the subject's patron")
}

/// Retain nothing from a currency request after answering it
///
/// Spec: wire-format.md §7.1; design §12.6.5
/// Milestone: 4.  Kind: negative.  Oracle: behaviour.
///
/// Rule (wire-format.md §7.1): "Nothing is retained on either side."
/// Rule (wire-format.md §7.1): "It is not archived"
/// Rule (design §12.6.5): "answered and discarded, and never archived (§10)"
///
/// Given: Node P answers a CurrencyRequest naming S from an authenticated peer Q.
/// When: The test inspects P's archive and persistent storage after the reply.
/// Then: No record of the request, of Q, or of the reply is present.
#[test]
#[ignore = "acceptance CUR-12: owed at milestone 4"]
fn cur_12_retain_nothing_from_a_currency_request_after_ans() {
    todo!("CUR-12: Retain nothing from a currency request after answering it")
}

/// Decide expiry against your own clock
///
/// Spec: design §12.6.5
/// Milestone: 4.  Kind: positive.  Oracle: behaviour.
///
/// Rule (design §12.6.5): "Expiry is decided against the relying party's own clock"
///
/// Given: Node N holds an attestation for X with field 4 equal to T. The issuer's clock plays no part in the test.
/// When: N evaluates the staple with its clock set before T, then with its clock set after T.
/// Then: The staple is treated as current in the first case and as expired in the second, so a trust-bearing operation proceeds only in the first.
#[test]
#[ignore = "acceptance CUR-13: owed at milestone 4"]
fn cur_13_decide_expiry_against_your_own_clock() {
    todo!("CUR-13: Decide expiry against your own clock")
}
