//! GENERATED by tools/gen_stubs.py from acceptance.json.  Do not edit;
//! change the catalogue and regenerate.  Each stub is one acceptance test
//! still owed for this area.

/// Accept a presence record at the derived envelope ceiling of 36 signature entries
///
/// Spec: wire-format.md §1.3; wire-format.md §3.5; design §5.1
/// Milestone: 1.  Kind: must-accept.  Oracle: behaviour.
///
/// Rule (wire-format.md §1.3): "The envelope bound MUST be derived, never asserted independently, and derived in two steps."
/// Rule (wire-format.md §1.3): "Sum the transaction type's per-role bounds to get the logical signer ceiling, then double it for the COSE_Signature array, since each logical signer contributes one classical and one post-quantum entry (§3.5)."
/// Rule (wire-format.md §1.3): "For a presence record: 2 participants + 16 witnesses = 18."
/// Rule (wire-format.md §1.3): "Twice the logical-signer bound, since each contributes one classical and one PQ entry (§3.5). For a presence record, 36"
/// Rule (wire-format.md §3.5): "Each logical signer contributes exactly two COSE_Signature entries: one under its classical component (alg = -8) and one under its post-quantum component (alg = -49)."
///
/// Given: Eighteen synthetic identities generated by the test-vectors keygen recipe (test-vectors/README.md; the shipped corpus holds fewer than 18, which is why B-witnesses-17 has no 16-witness accept companion at the envelope layer). A normal presence record whose body names 2 participants and 16 witnesses, with a full envelope of 18 logical signers — 36 COSE_Signature entries, sorted by kid then classical before post-quantum — every signature real over the body under `rhtn/1:envelope`.
/// When: The envelope is presented to the decoder and verifier.
/// Then: structural = valid and signatures[signer, alg] = verified for all 36 entries. An implementation carrying an independently asserted envelope ceiling below 36 entries or below 18 logical signers reports malformed here and fails conformance.
#[test]
#[ignore = "acceptance DEC-05: owed at milestone 1"]
fn dec_05_accept_a_presence_record_at_the_derived_envelope() {
    todo!("DEC-05: Accept a presence record at the derived envelope ceiling of 36 signature entries")
}

/// Accept an array or value exactly at a §1.3 ceiling that no corpus fixture reaches
///
/// Spec: wire-format.md §1.3
/// Milestone: 1.  Kind: must-accept.  Oracle: behaviour.
///
/// Rule (wire-format.md §1.3): "Arrays arriving from strangers are a resource attack surface, so each is given an explicit maximum below; exceeding it is malformed, not merely unusual."
/// Rule (wire-format.md §1.3): "Capabilities value, bytes | 1024"
/// Rule (wire-format.md §1.3): "Verifier responses per presence record | 32 — two subjects × a per-subject threshold capped at 10, with headroom."
/// Rule (wire-format.md §1.3): "Verifier responses per recovery | 32"
///
/// Given: Three at-ceiling objects for rows whose corpus coverage is a rejection only: (a) a Capabilities map carrying one value of exactly 1024 encoded bytes (B-caps-value-1025 is the rejection; no 1024 accept exists); (b) a normal presence record carrying 32 verifier responses from 32 distinct synthetic verifiers, 16 per subject, sorted as §4.5 requires (U-responses-33 is the unit-recipe rejection); (c) a recovery adoption carrying 32 verifier responses (U-recovery-responses-33 is the rejection). Identities from the keygen recipe.
/// When: Each object is presented to the decoder at its layer.
/// Then: structural = valid for all three. An implementation whose ceiling is off by one on the low side — 1023 bytes, or 31 responses — rejects one of these and fails conformance.
#[test]
#[ignore = "acceptance DEC-06: owed at milestone 1"]
fn dec_06_accept_an_array_or_value_exactly_at_a_1_3_ceilin() {
    todo!("DEC-06: Accept an array or value exactly at a §1.3 ceiling that no corpus fixture reaches")
}
