//! GENERATED by tools/gen_stubs.py from acceptance.json.  Do not edit;
//! change the catalogue and regenerate.  Each stub is one acceptance test
//! still owed for this area.

/// Return malformed for every proper prefix of a valid object without crashing
///
/// Spec: wire-format.md §1; wire-format.md §1.2; wire-format.md §1.3; design §21.1
/// Milestone: 1.  Kind: robustness.  Oracle: fixture.
///
/// Rule (wire-format.md §1): "CBOR (RFC 8949) with deterministic encoding, RFC 8949 §4.2."
/// Rule (wire-format.md §1.2): "Definite-length encoding only. No indefinite-length arrays, maps or strings."
/// Rule (wire-format.md §1.3): "Bounds exist to stop a stranger exhausting memory, not to describe normal operation."
///
/// Given: The accept set: every corpus.json entry of class `bytes` whose expect.outcome is `accept` (162 byte-class entries in the current corpus, the accept subset among them). For each entry, every proper prefix of its bytes, lengths 0 to n−1, and memory budget M and per-input time budget T, which no document sets (design §21.1 places buffer bounds with the component and lists none).
/// When: Each prefix is presented to the decoder as a complete input, at whichever layer the entry's expect.kind names (body, envelope, frame, reply, record).
/// Then: Every prefix yields structural = malformed. The decoder returns a verdict for every prefix; the process neither terminates abnormally nor hangs beyond T nor exceeds M on any of them.
///
/// Interpretation: An incomplete CBOR data item is not well-formed under RFC 8949; the profile adopts RFC 8949 without restating well-formedness, so the malformed verdict on a truncated item rests on the RFC rather than on a sentence of the profile.
#[test]
#[ignore = "acceptance DEC-01: owed at milestone 1"]
fn dec_01_return_malformed_for_every_proper_prefix_of_a_va() {
    todo!("DEC-01: Return malformed for every proper prefix of a valid object without crashing")
}

/// Return a verdict for every seeded mutation of a valid object without crashing
///
/// Spec: wire-format.md §1.2; wire-format.md §1.3; design §21.1
/// Milestone: 1.  Kind: robustness.  Oracle: behaviour.
///
/// Rule (wire-format.md §1.3): "Bounds exist to stop a stranger exhausting memory, not to describe normal operation."
/// Rule (wire-format.md §1.3): "They are conservative ceilings chosen to bound a decoder's exposure to a hostile peer, set well above any use anyone has articulated."
/// Rule (wire-format.md §1.2): "Validate the bytes as received; do not decode and re-encode to compare."
///
/// Given: The accept set as in DEC-01. For each entry, N variants produced by a seeded mutator — single-byte substitution, byte insertion, byte deletion, and splicing a run of another entry's bytes into it — with the seed S and N recorded so the run is reproducible; memory budget M and per-input time budget T, which no document sets (design §21.1 places buffer bounds with the component and lists none).
/// When: Each variant is presented to the decoder as a complete input at the entry's layer.
/// Then: Every variant yields exactly one of structural = valid or structural = malformed. No variant terminates the process abnormally, runs beyond T, or drives memory above M. Any variant reported valid is re-checked by re-serialisation: its emitted bytes equal the variant's bytes.
///
/// Interpretation: Crash-freedom and a time bound are not stated in any document; §1.3 states only that the bounds exist to stop memory exhaustion by a hostile peer. The test parameterises M and T and records them with the run.
#[test]
#[ignore = "acceptance DEC-02: owed at milestone 1"]
fn dec_02_return_a_verdict_for_every_seeded_mutation_of_a() {
    todo!("DEC-02: Return a verdict for every seeded mutation of a valid object without crashing")
}

/// Reject a header that declares more content than the input carries, within the memory budget
///
/// Spec: wire-format.md §1.2; wire-format.md §1.3; design §21.1
/// Milestone: 1.  Kind: robustness.  Oracle: behaviour.
///
/// Rule (wire-format.md §1.3): "Bounds exist to stop a stranger exhausting memory, not to describe normal operation."
/// Rule (wire-format.md §1.3): "Arrays arriving from strangers are a resource attack surface, so each is given an explicit maximum below; exceeding it is malformed, not merely unusual."
/// Rule (wire-format.md §1.2): "Definite-length encoding only. No indefinite-length arrays, maps or strings."
///
/// Given: Three inputs derived from the accepted adoption P-adopt-min: (a) the keyhash in field 1 replaced by a byte-string header `5b ffffffffffffffff` (2^64−1 declared bytes) followed by 32 bytes; (b) the merge back-pointer list in field 0 replaced by an array header `9a ffffffff` (2^32−1 declared elements) followed by one element; (c) the body's map header replaced by `ba ffffffff` followed by the original entries. memory budget M and per-input time budget T, which no document sets (design §21.1 places buffer bounds with the component and lists none).
/// When: Each input is presented to the decoder as a complete body.
/// Then: structural = malformed for all three. Peak memory during each decode stays within M, which is set far below the declared sizes; the decoder returns rather than waiting for the declared content.
///
/// Interpretation: The specification bounds memory through the array ceilings and says bounds exist to stop exhaustion; that a declared length beyond the input or beyond any ceiling is rejected on sight, without reserving the declared size, is implied by that purpose rather than stated.
#[test]
#[ignore = "acceptance DEC-03: owed at milestone 1"]
fn dec_03_reject_a_header_that_declares_more_content_than() {
    todo!("DEC-03: Reject a header that declares more content than the input carries, within the memory budget")
}

/// Reject a self-describe CBOR tag prefixed to a message
///
/// Spec: wire-format.md §1; wire-format.md §1.2; wire-format.md §3
/// Milestone: 1.  Kind: negative.  Oracle: behaviour.
///
/// Rule (wire-format.md §1): "Nested COSE objects are UNTAGGED. RFC 9052 permits either, and libraries expose both serialisations, so a profile that does not choose gets two byte encodings for one object"
/// Rule (wire-format.md §1.2): "Validate the bytes as received; do not decode and re-encode to compare."
/// Rule (wire-format.md §3): "Signature coverage is the body map only. Never the envelope, or signatures would not survive the addition of a signer."
///
/// Given: The accepted adoption envelope P-adopt-min with the bytes `d9 d9 f7` (CBOR tag 55799, self-describe) prefixed to the envelope; separately, the same envelope's body with the same prefix; separately, the accepted Attach frame P-frame-01 with the prefix inserted after the u32 length prefix (length adjusted).
/// When: Each tagged form is presented to the decoder at its layer.
/// Then: structural = malformed for all three; none is accepted as the untagged object it wraps. The untagged originals remain accepted.
///
/// Interpretation: No document names tag 55799. The expectation rests on the schema's top-level item being a map (§3's Envelope, §8.0's frame array) and a tag being a different major type, so a library that strips the tag silently would give one object two accepted encodings — the outcome §1 forbids for nested COSE tags.
#[test]
#[ignore = "acceptance DEC-04: owed at milestone 1"]
fn dec_04_reject_a_self_describe_cbor_tag_prefixed_to_a_me() {
    todo!("DEC-04: Reject a self-describe CBOR tag prefixed to a message")
}

/// Accept a presence record at the derived envelope ceiling of 36 signature entries
///
/// Spec: wire-format.md §1.3; wire-format.md §3.5; design §5.1
/// Milestone: 1.  Kind: must-accept.  Oracle: behaviour.
///
/// Rule (wire-format.md §1.3): "The envelope bound MUST be derived, never asserted independently, and derived in two steps."
/// Rule (wire-format.md §1.3): "Sum the transaction type's per-role bounds to get the logical signer ceiling, then double it for the COSE_Signature array, since each logical signer contributes one classical and one post-quantum entry (§3.5)."
/// Rule (wire-format.md §1.3): "For a presence record: 2 participants + 16 witnesses = 18."
/// Rule (wire-format.md §1.3): "Twice the logical-signer bound, since each contributes one classical and one PQ entry (§3.5). For a presence record, 36"
/// Rule (wire-format.md §3.5): "Each logical signer contributes exactly two COSE_Signature entries: one under its classical component (alg = -8) and one under its post-quantum component (alg = -49)."
///
/// Given: Eighteen synthetic identities generated by the test-vectors keygen recipe (test-vectors/README.md; the shipped corpus holds fewer than 18, which is why B-witnesses-17 has no 16-witness accept companion at the envelope layer). A normal presence record whose body names 2 participants and 16 witnesses, with a full envelope of 18 logical signers — 36 COSE_Signature entries, sorted by kid then classical before post-quantum — every signature real over the body under `rhtn/1:envelope`.
/// When: The envelope is presented to the decoder and verifier.
/// Then: structural = valid and signatures[signer, alg] = verified for all 36 entries. An implementation carrying an independently asserted envelope ceiling below 36 entries or below 18 logical signers reports malformed here and fails conformance.
#[test]
#[ignore = "acceptance DEC-05: owed at milestone 1"]
fn dec_05_accept_a_presence_record_at_the_derived_envelope() {
    todo!("DEC-05: Accept a presence record at the derived envelope ceiling of 36 signature entries")
}

/// Accept an array or value exactly at a §1.3 ceiling that no corpus fixture reaches
///
/// Spec: wire-format.md §1.3
/// Milestone: 1.  Kind: must-accept.  Oracle: behaviour.
///
/// Rule (wire-format.md §1.3): "Arrays arriving from strangers are a resource attack surface, so each is given an explicit maximum below; exceeding it is malformed, not merely unusual."
/// Rule (wire-format.md §1.3): "Capabilities value, bytes | 1024"
/// Rule (wire-format.md §1.3): "Verifier responses per presence record | 32 — two subjects × a per-subject threshold capped at 10, with headroom."
/// Rule (wire-format.md §1.3): "Verifier responses per recovery | 32"
///
/// Given: Three at-ceiling objects for rows whose corpus coverage is a rejection only: (a) a Capabilities map carrying one value of exactly 1024 encoded bytes (B-caps-value-1025 is the rejection; no 1024 accept exists); (b) a normal presence record carrying 32 verifier responses from 32 distinct synthetic verifiers, 16 per subject, sorted as §4.5 requires (U-responses-33 is the unit-recipe rejection); (c) a recovery adoption carrying 32 verifier responses (U-recovery-responses-33 is the rejection). Identities from the keygen recipe.
/// When: Each object is presented to the decoder at its layer.
/// Then: structural = valid for all three. An implementation whose ceiling is off by one on the low side — 1023 bytes, or 31 responses — rejects one of these and fails conformance.
#[test]
#[ignore = "acceptance DEC-06: owed at milestone 1"]
fn dec_06_accept_an_array_or_value_exactly_at_a_1_3_ceilin() {
    todo!("DEC-06: Accept an array or value exactly at a §1.3 ceiling that no corpus fixture reaches")
}

/// Reject a CatalogReply carrying 112 entries
///
/// Spec: wire-format.md §1.3; wire-format.md §6.4
/// Milestone: 1.  Kind: negative.  Oracle: behaviour.
///
/// Rule (wire-format.md §1.3): "CatalogReply entries | 111 — an answering node answers for itself plus the ≤110 users it serves"
/// Rule (wire-format.md §1.3): "Arrays arriving from strangers are a resource attack surface, so each is given an explicit maximum below; exceeding it is malformed, not merely unusual."
///
/// Given: The conforming truncated reply P-catalog-reply-truncated, which carries exactly 111 entries in field 2 and a continuation in field 3. A variant appends the withheld 112th entry to field 2, once with field 3 retained and once with field 3 removed. The reply is an unsigned message.
/// When: Each variant is presented to the decoder as a CatalogReply.
/// Then: structural = malformed for both variants. The 111-entry original remains accepted.
#[test]
#[ignore = "acceptance DEC-07: owed at milestone 1"]
fn dec_07_reject_a_catalogreply_carrying_112_entries() {
    todo!("DEC-07: Reject a CatalogReply carrying 112 entries")
}

/// Reject an unknown map key on every unsigned message family
///
/// Spec: wire-format.md §1.2; wire-format.md §6.4
/// Milestone: 1.  Kind: negative.  Oracle: behaviour.
///
/// Rule (wire-format.md §1.2): "Unsigned messages reject unknown map keys — every message outside a signature's coverage, in every family."
/// Rule (wire-format.md §6.4): "Unsigned session messages reject unknown map keys (§1's global rule) — CatalogQuery, CatalogReply, ResourceRequest, ResourceResponse and the control frames of §8.0 alike, and equally every unsigned family this chapter does not name: resolution, prekey and archive requests, grants and wrappers."
///
/// Given: For every unsigned family that has an accepted vector in test-vectors/messages.md — control frames on stream 0, requests, and replies, including CatalogQuery, CatalogReply, ResourceRequest, ResourceResponse, the resolution, prekey and archive messages, grants and wrappers — the vector's top-level map with one added entry `99: h'c0ffee'`, inserted in ascending key position so the map stays canonical; where the message is a frame, the u32 length prefix adjusted.
/// When: Each modified message is presented to the decoder at its layer.
/// Then: Each is rejected as malformed; none is accepted with the key preserved, and none is accepted with the key ignored. The unmodified vectors remain accepted.
#[test]
#[ignore = "acceptance DEC-08: owed at milestone 1"]
fn dec_08_reject_an_unknown_map_key_on_every_unsigned_mess() {
    todo!("DEC-08: Reject an unknown map key on every unsigned message family")
}

/// Reject an unknown key in the transaction envelope map
///
/// Spec: wire-format.md §1.2; wire-format.md §3
/// Milestone: 1.  Kind: negative.  Oracle: behaviour.
///
/// Rule (wire-format.md §1.2): "Unsigned messages reject unknown map keys — every message outside a signature's coverage, in every family."
/// Rule (wire-format.md §3): "Signature coverage is the body map only. Never the envelope, or signatures would not survive the addition of a signer."
///
/// Given: The accepted adoption envelope P-adopt-min with one entry `5: h'c0ffee'` appended to the Envelope map after key 4 (map header `a4` becomes `a5`); the body in field 3 and all four signatures unchanged.
/// When: The envelope is presented to the decoder and verifier.
/// Then: structural = malformed, even though all four body signatures verify over the unchanged body; the object is not accepted with the envelope-level key preserved.
///
/// Interpretation: The Envelope map's own keys (version, type, signatures) sit outside every signature's coverage, so §1.2's rule for keys outside a signature's coverage is read as reaching the envelope map; §3 does not say so in as many words, and D2's preservation rule is read as scoped to the signed body.
#[test]
#[ignore = "acceptance DEC-09: owed at milestone 1"]
fn dec_09_reject_an_unknown_key_in_the_transaction_envelop() {
    todo!("DEC-09: Reject an unknown key in the transaction envelope map")
}

/// Reject a duplicated unknown extension key
///
/// Spec: wire-format.md §1.2
/// Milestone: 1.  Kind: negative.  Oracle: behaviour.
///
/// Rule (wire-format.md §1.2): "No duplicate map keys; a decoder MUST reject them rather than take the last."
/// Rule (wire-format.md §1.2): "Duplicate map keys MUST be rejected before the map is materialised."
///
/// Given: The accepted extended adoption body P-adopt-extensions (unknown key 99 at the top level and inside the Locator) with the top-level entry `99: h'c0ffee'` repeated once immediately after itself (body map header `a7` becomes `a8`), in two variants: the second value identical, and the second value `h'c0ffef'`.
/// When: Each variant body is presented to the decoder.
/// Then: structural = malformed for both variants. The single-key original remains accepted. An implementation that collects unknown keys into a list rather than a keyed structure, and so never sees the collision, accepts these and fails.
#[test]
#[ignore = "acceptance DEC-10: owed at milestone 1"]
fn dec_10_reject_a_duplicated_unknown_extension_key() {
    todo!("DEC-10: Reject a duplicated unknown extension key")
}

/// Reject an unknown extension value that is not deterministically encoded
///
/// Spec: wire-format.md §1.2
/// Milestone: 1.  Kind: negative.  Oracle: behaviour.
///
/// Rule (wire-format.md §1.2): "Any deterministically encoded CBOR item is admissible — the profile's encoding rules govern the slice's framing, and its meaning is nobody else's to evaluate"
/// Rule (wire-format.md §1.2): "Definite-length encoding only. No indefinite-length arrays, maps or strings."
/// Rule (wire-format.md §1.2): "Shortest-form integers."
///
/// Given: P-adopt-extensions with its top-level key-99 value replaced by, in turn: (a) the indefinite-length array `9f 05 ff`; (b) the non-shortest integer `18 0a`; (c) a byte string with a non-shortest length header `58 03 c0ffee`. Each slice is within the 1024-byte ceiling and the map stays otherwise canonical.
/// When: Each variant body is presented to the decoder.
/// Then: structural = malformed for all three. An implementation that skips an unknown value by walking its framing without checking the profile's encoding rules inside the slice accepts these and fails.
///
/// Interpretation: 'The profile's encoding rules govern the slice's framing' is read as requiring the whole slice, not only its outermost header, to be deterministically encoded; whether the protocol-map key rules (unsigned-integer keys, ascending) also reach a map nested inside the slice is a question for the author and is not tested here.
#[test]
#[ignore = "acceptance DEC-11: owed at milestone 1"]
fn dec_11_reject_an_unknown_extension_value_that_is_not_de() {
    todo!("DEC-11: Reject an unknown extension value that is not deterministically encoded")
}

/// Accept a 1024-byte extension value nested 1024 levels deep
///
/// Spec: wire-format.md §1.2; wire-format.md §1.3
/// Milestone: 1.  Kind: must-accept.  Oracle: behaviour.
///
/// Rule (wire-format.md §1.2): "Any deterministically encoded CBOR item is admissible — the profile's encoding rules govern the slice's framing, and its meaning is nobody else's to evaluate"
/// Rule (wire-format.md §1.3): "1024 bytes of encoded CBOR — the complete encoded slice for the value, which is measurable for every value type and is what bounds parser work."
///
/// Given: P-adopt-extensions with its top-level key-99 value replaced by 1023 bytes of `81` followed by `80` — a deterministic encoding of one-element arrays nested 1024 deep, occupying exactly the 1024-byte extension-value ceiling. memory budget M and per-input time budget T, which no document sets (design §21.1 places buffer bounds with the component and lists none).
/// When: The body is presented to the decoder.
/// Then: structural = valid; the decoder returns within T and within M; the unknown key's slice is preserved, so the body re-serialises to bytes identical to the input. An implementation with a recursion limit below 1024 reports malformed or terminates abnormally here and fails.
///
/// Interpretation: §1.3 sets no nesting-depth ceiling; depth is bounded only through the 1024-byte encoded-slice bound, so a decoder that caps depth lower is over-strict under the text as written. Whether the author wants a depth ceiling is raised in the notes.
#[test]
#[ignore = "acceptance DEC-12: owed at milestone 1"]
fn dec_12_accept_a_1024_byte_extension_value_nested_1024_l() {
    todo!("DEC-12: Accept a 1024-byte extension value nested 1024 levels deep")
}

/// Accept sixteen unknown keys in each of two maps of one body
///
/// Spec: wire-format.md §1.2; wire-format.md §1.3
/// Milestone: 1.  Kind: must-accept.  Oracle: behaviour.
///
/// Rule (wire-format.md §1.3): "Unknown extension keys per map | 16"
/// Rule (wire-format.md §1.2): "Unknown map keys MUST be preserved when re-serializing for signature verification, and MUST NOT be silently dropped."
///
/// Given: P-adopt-extensions' pattern extended: 16 unknown keys (99 through 114, each `h'c0ffee'`) at the body's top level and 16 unknown keys (the same numbers) inside the Locator map in field 3 — 32 unknown keys in one body, 16 per map, both maps canonical (B-ext-keys-16 exercises one map only).
/// When: The body is presented to the decoder.
/// Then: structural = valid, and the body re-serialises to bytes identical to the input with all 32 keys present. An implementation counting unknown keys per object rather than per map reports malformed here and fails.
///
/// Interpretation: 'Per map' is read as each map counted independently, so 32 unknown keys across two maps are within bound; the specification does not say whether the count is per map or per object in any other words.
#[test]
#[ignore = "acceptance DEC-13: owed at milestone 1"]
fn dec_13_accept_sixteen_unknown_keys_in_each_of_two_maps() {
    todo!("DEC-13: Accept sixteen unknown keys in each of two maps of one body")
}

/// Accept an Attach whose required Capabilities map is empty
///
/// Spec: wire-format.md §1.2; wire-format.md §8.1; wire-format.md §8.2
/// Milestone: 1.  Kind: must-accept.  Oracle: behaviour.
///
/// Rule (wire-format.md §1.2): "A required map with no entries is encoded as an empty map — `Capabilities` in `Attach` and `AttachAck` is the case in point, since a peer advertising nothing must still send the field."
/// Rule (wire-format.md §1.2): "This does not apply to required fields."
///
/// Given: The accepted Attach frame P-frame-01 (two capability parameters, one greased) with field 3 replaced by the empty map `a0`, fields 1 and 2 unchanged, and the u32 length prefix adjusted.
/// When: The frame is presented to the decoder as a stream-0 control frame.
/// Then: The frame is accepted: structural = valid with an empty capability set. An implementation that applies the omit-if-empty rule to a required field, or requires at least one capability parameter, rejects this and fails.
#[test]
#[ignore = "acceptance DEC-14: owed at milestone 1"]
fn dec_14_accept_an_attach_whose_required_capabilities_map() {
    todo!("DEC-14: Accept an Attach whose required Capabilities map is empty")
}

/// Reject an Attach that omits its required Capabilities map
///
/// Spec: wire-format.md §1.2; wire-format.md §8.2
/// Milestone: 1.  Kind: negative.  Oracle: behaviour.
///
/// Rule (wire-format.md §1.2): "This does not apply to required fields."
/// Rule (wire-format.md §1.2): "A required map with no entries is encoded as an empty map — `Capabilities` in `Attach` and `AttachAck` is the case in point, since a peer advertising nothing must still send the field."
///
/// Given: P-frame-01 with field 3 removed entirely (Attach map header `a3` becomes `a2`), fields 1 and 2 unchanged, length prefix adjusted. N-shape-attach-missing-identity covers field 1; no fixture covers field 3.
/// When: The frame is presented to the decoder as a stream-0 control frame.
/// Then: structural = malformed. An implementation that reads the omit-if-empty rule as licensing omission of a required map accepts this and fails.
#[test]
#[ignore = "acceptance DEC-15: owed at milestone 1"]
fn dec_15_reject_an_attach_that_omits_its_required_capabil() {
    todo!("DEC-15: Reject an Attach that omits its required Capabilities map")
}

/// Re-serialise every accepted object to bytes identical to the input
///
/// Spec: wire-format.md §1; wire-format.md §1.2
/// Milestone: 1.  Kind: positive.  Oracle: fixture.
///
/// Rule (wire-format.md §1.2): "Unknown map keys MUST be preserved when re-serializing for signature verification, and MUST NOT be silently dropped."
/// Rule (wire-format.md §1.2): "Keep the received bytes and derive typed views from them."
/// Rule (wire-format.md §1): "A signature covers every retained field of the object it signs, except the signature field itself, including unknown extension keys."
///
/// Given: The accept set: every corpus.json entry of class `bytes` whose expect.outcome is `accept` (162 byte-class entries in the current corpus, the accept subset among them), including P-adopt-extensions (unknown keys top-level and nested), the extended EndpointRecord of records.md (D8) and the SignedLocator carrying unknown key 4 (D9).
/// When: Each entry is decoded and then emitted again by the implementation's encoder — the same path it uses to reconstruct a signed payload, to store an object, or to hand it onward.
/// Then: For every entry the emitted bytes equal the input bytes exactly, unknown keys, their positions and their encoded values included. No entry is emitted with an unknown key dropped, reordered, or re-encoded.
///
/// Interpretation: §1.2 states preservation for re-serialisation for signature verification; this entry asserts the same for every re-serialisation the implementation performs, on the reading that a key dropped on any other path yields a different object, and a different txid, at the next holder.
#[test]
#[ignore = "acceptance DEC-16: owed at milestone 1"]
fn dec_16_re_serialise_every_accepted_object_to_bytes_iden() {
    todo!("DEC-16: Re-serialise every accepted object to bytes identical to the input")
}
