//! GENERATED by tools/gen_stubs.py from acceptance.json.  Do not edit;
//! change the catalogue and regenerate.  Each stub is one acceptance test
//! still owed for this area.

/// Rank candidates by available flow, then path length, then consideration order
///
/// Spec: design §16.4
/// Milestone: 5.  Kind: positive.  Oracle: fixture.
///
/// Rule (design §16.4): "ranks candidates explicitly, by available flow first, then path length, then consideration order"
/// Rule (design §16.4): "Available flow ranks first"
///
/// Given: A fixed reference graph in which a saturated cut cannot admit every candidate: A carries more flow than B and C; B and C carry equal flow but B is fewer hops from the observer; D and E are equal on both and D was considered first.
/// When: The reference metric allocates.
/// Then: The allocation admits A before B, B before C, and D before E, and the reported per-candidate flow values match the fixture's expected values.
#[test]
#[ignore = "acceptance MET-01: owed at milestone 5"]
fn met_01_rank_candidates_by_available_flow_then_path_leng() {
    todo!("MET-01: Rank candidates by available flow, then path length, then consideration order")
}

/// Let no adjacency order decide an equal-path tie
///
/// Spec: design §16.4
/// Milestone: 5.  Kind: negative.  Oracle: fixture.
///
/// Rule (design §16.4): "at equal path length the winner is then decided by the order edges happen to occupy in the implementation's own adjacency structure"
/// Rule (design §16.4): "Consideration order breaks true ties only"
///
/// Given: The graph of MET-01 built twice, with its edges inserted in two different orders, and the same consideration order supplied to both.
/// When: The reference metric allocates over each.
/// Then: Both allocations are identical.
#[test]
#[ignore = "acceptance MET-02: owed at milestone 5"]
fn met_02_let_no_adjacency_order_decide_an_equal_path_tie() {
    todo!("MET-02: Let no adjacency order decide an equal-path tie")
}

/// Weigh only the intersection with identities you already know
///
/// Spec: design §16.1
/// Milestone: 5.  Kind: positive.  Oracle: behaviour.
///
/// Rule (design §16.1): "A patron following it weighs the intersection and nothing else"
/// Rule (design §16.1): "records naming unknown identities are not weighed less, they are not weighed"
///
/// Given: The reference policy at patron P, and a presented archive naming three identities P knows and one thousand it does not.
/// When: P evaluates the archive.
/// Then: The standing P computes equals the standing computed from the three records naming known identities alone, and appending further records naming only unknown identities leaves it unchanged.
#[test]
#[ignore = "acceptance MET-03: owed at milestone 5"]
fn met_03_weigh_only_the_intersection_with_identities_you() {
    todo!("MET-03: Weigh only the intersection with identities you already know")
}

/// Substitute a policy without changing anything the protocol does
///
/// Spec: design §16.1; design §16.4
/// Milestone: 5.  Kind: positive.  Oracle: behaviour.
///
/// Rule (design §16.1): "Each node computes its own trust for every known node from the transactions it observes, using the reference algorithm or a variant tuned to its application or group norms."
/// Rule (design §16.4): "No pass is promoted to a protocol rule"
///
/// Given: The reference metric and a trivial alternative policy that scores every known node equally, both supplied through the implementation's policy interface.
/// When: The same observed transactions are fed to a node running each in turn.
/// Then: The two nodes store and forward the same objects and produce the same wire traffic; only their computed standings differ.
///
/// Interpretation: What the policy interface must expose is not stated; the test asserts that a substitute policy changes computed standing and nothing on the wire.
#[test]
#[ignore = "acceptance MET-04: owed at milestone 5"]
fn met_04_substitute_a_policy_without_changing_anything_th() {
    todo!("MET-04: Substitute a policy without changing anything the protocol does")
}

/// Report a policy's resistance bound from the conformance test
///
/// Spec: design §16.4; design §17.3
/// Milestone: 5.  Kind: positive.  Oracle: model.
///
/// Rule (design §16.4): "provide a conformance test that reports a policy's resistance bound so anyone tuning their own can see what they have given up"
/// Rule (design §17.3): "Flow-limited trust bounds what any single-entry region can claim regardless of its size (§16.2)"
///
/// Given: The conformance test's fake-region topology, entered beyond the observer's horizon, grown across the population sizes the simulation uses, and two policies: the reference metric and a distance-decay policy.
/// When: The conformance test runs each policy.
/// Then: For the reference metric the report states a bound equal to the region's cut and the best score never exceeds it at any size. For the decay policy the report states that the score grows with region size.
///
/// Interpretation: The form of the reported bound is not specified; the test asserts a finite cut-equal bound for the reference and growth for the decay policy.
#[test]
#[ignore = "acceptance MET-05: owed at milestone 5"]
fn met_05_report_a_policy_s_resistance_bound_from_the_conf() {
    todo!("MET-05: Report a policy's resistance bound from the conformance test")
}

/// Collapse parallel edges between one pair to one capacity
///
/// Spec: design §16.2.1
/// Milestone: 5.  Kind: positive.  Oracle: model.
///
/// Rule (design §16.2.1): "capacity belongs to the pair, not to the count of relationships between them"
///
/// Given: A pair joined by an adoption and two later presence records.
/// When: The reference metric builds its graph.
/// Then: The pair carries one edge's capacity; summing the three would give a larger flow, and the computed flow equals the single-edge value.
#[test]
#[ignore = "acceptance MET-06: owed at milestone 5"]
fn met_06_collapse_parallel_edges_between_one_pair_to_one() {
    todo!("MET-06: Collapse parallel edges between one pair to one capacity")
}

/// Bound the aggregate a set can draw by the cut, per computation
///
/// Spec: design §16.4; design §17.3
/// Milestone: 5.  Kind: positive.  Oracle: model.
///
/// Rule (design §16.4): "the aggregate a set can draw is bounded by the cut (§16.2)"
/// Rule (design §17.3): "where the entry lies beyond the observer's horizon"
///
/// Given: The simulation's conserving topology: a region behind one acquired peering edge beyond the observer's horizon, at the population sizes the simulation uses.
/// When: The reference metric computes joint flow to the region and the sum of independent per-target flows.
/// Then: The joint flow saturates at the cut at every size while the independent sum grows with population; the figures match the simulation's committed results.
#[test]
#[ignore = "acceptance MET-07: owed at milestone 5"]
fn met_07_bound_the_aggregate_a_set_can_draw_by_the_cut_pe() {
    todo!("MET-07: Bound the aggregate a set can draw by the cut, per computation")
}

/// Treat the branching condition as necessary and not sufficient
///
/// Spec: design §16.4
/// Milestone: 5.  Kind: negative.  Oracle: model.
///
/// Rule (design §16.4): "it bounds the hierarchy's fanout and not §16.2.1's unbounded acquaintance degree, so it is necessary and not sufficient"
///
/// Given: Two graphs at the same fanout and the same decay parameter satisfying the condition: one whose acquaintance degree is bounded and one whose acquaintance degree grows with depth.
/// When: A distance-decay policy is scored on each.
/// Then: The first converges and the second does not, and the conformance report says which; an implementation that reports the condition as sufficient fails.
#[test]
#[ignore = "acceptance MET-08: owed at milestone 5"]
fn met_08_treat_the_branching_condition_as_necessary_and_n() {
    todo!("MET-08: Treat the branching condition as necessary and not sufficient")
}
