//! GENERATED by tools/gen_stubs.py from acceptance.json.  Do not edit;
//! change the catalogue and regenerate.  Each stub is one acceptance test
//! still owed for this area.

/// Publish a signed prekey bundle and keep the one-time pool stocked
///
/// Spec: light-client-requirements.md §3; wire-format.md §7.8
/// Milestone: after-5.  Kind: positive.  Oracle: behaviour.
///
/// Rule (light-client-requirements.md §3): "Publish a prekey bundle and keep it stocked."
/// Rule (wire-format.md §7.8): "The bundle is opaque to this protocol"
///
/// Given: Client S attaches to serving node N. The identity binding, prekey cadence and last-resort policy are open integration decisions (design §22.2) and are supplied to the test as parameters.
/// When: S completes its attach.
/// Then: N holds a PrekeyBundle for S with field 2 equal to 1 and a signature by S under the prekey tag over fields 1 to 4, and a non-empty one-time pool for S.
#[test]
#[ignore = "acceptance PAY-01: owed at milestone after-5"]
fn pay_01_publish_a_signed_prekey_bundle_and_keep_the_one() {
    todo!("PAY-01: Publish a signed prekey bundle and keep the one-time pool stocked")
}

/// Never serve or use a one-time prekey twice
///
/// Spec: light-client-requirements.md §3; infra-client-requirements.md §6; wire-format.md §7.8
/// Milestone: after-5.  Kind: negative.  Oracle: behaviour.
///
/// Rule (light-client-requirements.md §3): "never reuse a one-time prekey"
/// Rule (infra-client-requirements.md §6): "Consume one-time keys on serving them, and only when one is requested."
/// Rule (wire-format.md §7.8): "Only the one-time key is consumed on serving."
///
/// Given: N holds a pool of one-time keys for S.
/// When: Two requesters each send a PrekeyRequest for S with field 2 equal to 1.
/// Then: The two replies carry different one-time keys, the pool shrinks by two, and neither key is ever served again.
#[test]
#[ignore = "acceptance PAY-02: owed at milestone after-5"]
fn pay_02_never_serve_or_use_a_one_time_prekey_twice() {
    todo!("PAY-02: Never serve or use a one-time prekey twice")
}

/// Replenish the one-time pool before it is exhausted
///
/// Spec: light-client-requirements.md §3
/// Milestone: after-5.  Kind: liveness.  Oracle: behaviour.
///
/// Rule (light-client-requirements.md §3): "Replenish well before exhaustion"
/// Rule (light-client-requirements.md §3): "Rotate the signed prekey on a policy interval"
///
/// Given: Client S with a replenishment threshold and a signed-prekey interval chosen by the test, since both are policy.
/// When: Requesters draw one-time keys until the pool falls below the threshold, and the interval elapses.
/// Then: S uploads further one-time keys before the pool reaches zero, and publishes a new bundle with a later field 4 after the interval.
#[test]
#[ignore = "acceptance PAY-03: owed at milestone after-5"]
fn pay_03_replenish_the_one_time_pool_before_it_is_exhaust() {
    todo!("PAY-03: Replenish the one-time pool before it is exhausted")
}

/// Serve reusable material freely and consume nothing unless a one-time key is requested
///
/// Spec: infra-client-requirements.md §6; wire-format.md §7.8
/// Milestone: after-5.  Kind: positive.  Oracle: behaviour.
///
/// Rule (infra-client-requirements.md §6): "Serve reusable material freely."
/// Rule (wire-format.md §7.8): "The reusable material may be returned any number of times to anyone."
///
/// Given: N holds S's bundle and pool.
/// When: Two PrekeyRequests for S with field 2 equal to 0 arrive from different peers.
/// Then: Both replies carry S's bundle, neither carries field 3, and the pool is unchanged.
#[test]
#[ignore = "acceptance PAY-04: owed at milestone after-5"]
fn pay_04_serve_reusable_material_freely_and_consume_nothi() {
    todo!("PAY-04: Serve reusable material freely and consume nothing unless a one-time key is requested")
}

/// Rate-limit one-time key issuance per requester per subject
///
/// Spec: infra-client-requirements.md §6; wire-format.md §7.8
/// Milestone: after-5.  Kind: negative.  Oracle: behaviour.
///
/// Rule (infra-client-requirements.md §6): "Rate-limit one-time key issuance per requester per subject."
/// Rule (wire-format.md §7.8): "rate-limits one-time key issuance per requester per subject"
///
/// Given: N with a limit L per requester per subject per window, chosen by the test.
/// When: One requester sends L plus one PrekeyRequests for S with field 2 equal to 1 within the window, and one for another subject T.
/// Then: The first L replies carry one-time keys; the excess request for S is served no one-time key; the request for T is served one.
///
/// Interpretation: Whether the refused request is answered with the bundle and no field 3, or with failure code 1, is not stated; the test asserts only that no one-time key is served.
#[test]
#[ignore = "acceptance PAY-05: owed at milestone after-5"]
fn pay_05_rate_limit_one_time_key_issuance_per_requester_p() {
    todo!("PAY-05: Rate-limit one-time key issuance per requester per subject")
}

/// Tell the subject when its one-time pool is exhausted
///
/// Spec: infra-client-requirements.md §6
/// Milestone: after-5.  Kind: positive.  Oracle: behaviour.
///
/// Rule (infra-client-requirements.md §6): "Tell the subject when their one-time pool is exhausted."
///
/// Given: S's pool at N is drained by requesters.
/// When: The last one-time key is served.
/// Then: S's client learns of the exhaustion and replenishes; the test observes the notice through S's client and the subsequent upload.
///
/// Interpretation: No wire object carries the exhaustion notice; the test observes it through the client and treats the carrier as a parameter.
#[test]
#[ignore = "acceptance PAY-06: owed at milestone after-5"]
fn pay_06_tell_the_subject_when_its_one_time_pool_is_exhau() {
    todo!("PAY-06: Tell the subject when its one-time pool is exhausted")
}

/// Prefetch reusable material for the whole Dunbar Org as one sweep
///
/// Spec: light-client-requirements.md §3; wire-format.md §7.8
/// Milestone: after-5.  Kind: positive.  Oracle: behaviour.
///
/// Rule (light-client-requirements.md §3): "Prefetch reusable prekey material for the whole Dunbar Org as a batch request"
/// Rule (wire-format.md §7.8): "the population swept, in ascending keyhash order"
/// Rule (wire-format.md §7.8): "A `PrekeyBatchRequest` naming a population is visibly a sweep"
///
/// Given: Client S attaches with a horizon of known population.
/// When: S refreshes its prekey material.
/// Then: A PrekeyBatchRequest naming the population in ascending keyhash order is observed, and no single-subject PrekeyRequest with field 2 equal to 0 for any of them.
#[test]
#[ignore = "acceptance PAY-07: owed at milestone after-5"]
fn pay_07_prefetch_reusable_material_for_the_whole_dunbar() {
    todo!("PAY-07: Prefetch reusable material for the whole Dunbar Org as one sweep")
}

/// Request a one-time key only when opening a session, and never in a prefetch
///
/// Spec: light-client-requirements.md §3
/// Milestone: after-5.  Kind: negative.  Oracle: behaviour.
///
/// Rule (light-client-requirements.md §3): "Never prefetch one-time keys."
/// Rule (light-client-requirements.md §3): "Request a one-time key only when actually opening a session."
///
/// Given: Client S has prefetched reusable material for its org and has no session with T.
/// When: S idles, then sends its first message to T.
/// Then: No PrekeyRequest with field 2 equal to 1 is observed while idle; exactly one, naming T, is observed immediately before the first message.
#[test]
#[ignore = "acceptance PAY-08: owed at milestone after-5"]
fn pay_08_request_a_one_time_key_only_when_opening_a_sessi() {
    todo!("PAY-08: Request a one-time key only when opening a session, and never in a prefetch")
}

/// Keep no record of who asked for whose bundle
///
/// Spec: infra-client-requirements.md §6
/// Milestone: after-5.  Kind: negative.  Oracle: behaviour.
///
/// Rule (infra-client-requirements.md §6): "keep no record of who asked for whose bundle"
///
/// Given: N serves several PrekeyRequests and a PrekeyBatchRequest.
/// When: The test inspects N's persistent storage afterwards.
/// Then: No record of the requesters or of which subjects they asked for is present.
#[test]
#[ignore = "acceptance PAY-09: owed at milestone after-5"]
fn pay_09_keep_no_record_of_who_asked_for_whose_bundle() {
    todo!("PAY-09: Keep no record of who asked for whose bundle")
}

/// Store and serve a bundle without interpreting its contents
///
/// Spec: infra-client-requirements.md §6; wire-format.md §7.8
/// Milestone: after-5.  Kind: must-accept.  Oracle: behaviour.
///
/// Rule (infra-client-requirements.md §6): "The bundle is opaque."
/// Rule (wire-format.md §7.8): "The bundle is opaque to this protocol"
///
/// Given: A PrekeyBundle for S whose field 3 is an arbitrary byte string, correctly signed by S.
/// When: S uploads it and a requester fetches it.
/// Then: N stores and serves it unchanged. An implementation that parses field 3 and rejects it fails.
#[test]
#[ignore = "acceptance PAY-10: owed at milestone after-5"]
fn pay_10_store_and_serve_a_bundle_without_interpreting_it() {
    todo!("PAY-10: Store and serve a bundle without interpreting its contents")
}

/// Use the asynchronous construction only leaf to leaf
///
/// Spec: light-client-requirements.md §3; design §14.2.4.1
/// Milestone: after-5.  Kind: positive.  Oracle: behaviour.
///
/// Rule (light-client-requirements.md §3): "Only leaf-to-leaf needs this."
/// Rule (design §14.2.4.1): "Leaf → patron | Nothing new."
///
/// Given: Client S with a session to its patron P and a first message for leaf T.
/// When: S sends to P and then to T.
/// Then: No prekey request names P and the message to P rides the transport session; a one-time key request names T and the message to T is encrypted under the payload construction.
#[test]
#[ignore = "acceptance PAY-11: owed at milestone after-5"]
fn pay_11_use_the_asynchronous_construction_only_leaf_to_l() {
    todo!("PAY-11: Use the asynchronous construction only leaf to leaf")
}

/// Open a session on reusable material alone when no one-time key remains
///
/// Spec: wire-format.md §7.8
/// Milestone: after-5.  Kind: must-accept.  Oracle: behaviour.
///
/// Rule (wire-format.md §7.8): "when none remain, field 3 is simply absent and the session proceeds on reusable material alone"
///
/// Given: T's one-time pool at N is empty.
/// When: S requests a one-time key for T and then sends its first message.
/// Then: The PrekeyReply carries field 2 and no field 3, and S still opens the session and delivers the message. An implementation that refuses to send without a one-time key fails.
#[test]
#[ignore = "acceptance PAY-12: owed at milestone after-5"]
fn pay_12_open_a_session_on_reusable_material_alone_when_n() {
    todo!("PAY-12: Open a session on reusable material alone when no one-time key remains")
}

/// Instantiate PQXDH with X25519 and ML-KEM-768 and run the Triple Ratchet, matching the adopted specifications
///
/// Spec: design §14.2.4.2; design §14.2.4.3; design §14.2.4
/// Milestone: after-5.  Kind: positive.  Oracle: fixture.
///
/// Rule (design §14.2.4.2): "this profile instantiates it with X25519 and ML-KEM-768"
/// Rule (design §14.2.4.3): "Signal's Triple Ratchet."
/// Rule (design §14.2.4): "The requirement below is to adopt it, not to design a replacement."
///
/// Given: Two clients with fixed key material and the adopted library's published test vectors. The identity binding, prekey cadence and last-resort policy are open integration decisions (design §22.2) and are supplied to the test as parameters.
/// When: They establish a session and exchange messages.
/// Then: The key agreement and ratchet outputs match the adopted specifications' vectors for the same inputs, and a message decrypts only at its recipient.
///
/// Interpretation: How the session is bound to the hybrid identity is open; the test parameterises the binding and asserts agreement with the adopted construction's vectors.
#[test]
#[ignore = "acceptance PAY-13: owed at milestone after-5"]
fn pay_13_instantiate_pqxdh_with_x25519_and_ml_kem_768_and() {
    todo!("PAY-13: Instantiate PQXDH with X25519 and ML-KEM-768 and run the Triple Ratchet, matching the adopted specifications")
}

/// Dispatch protocol objects and application payload on the end-to-end channel to the right handler
///
/// Spec: wire-format.md §7.3; design §14.2.4.6
/// Milestone: after-5.  Kind: positive.  Oracle: behaviour.
///
/// Rule (wire-format.md §7.3): "Carried as payload, never as a record."
/// Rule (design §14.2.4.6): "Payload-type demultiplexing."
///
/// Given: Subject A sends verifier B a KeyGrant and an application message over the same end-to-end session. The demultiplexing scheme is an open decision (design §22.2) supplied as a parameter.
/// When: B receives both.
/// Then: The KeyGrant reaches B's grant handler and opens the named capture; the application message reaches the application; neither is delivered to the other.
///
/// Interpretation: The demultiplexing scheme is undecided; the test asserts correct dispatch under whichever scheme is supplied.
#[test]
#[ignore = "acceptance PAY-14: owed at milestone after-5"]
fn pay_14_dispatch_protocol_objects_and_application_payloa() {
    todo!("PAY-14: Dispatch protocol objects and application payload on the end-to-end channel to the right handler")
}

/// Deliver payload over the serving node when no direct path exists
///
/// Spec: design §14.1.1
/// Milestone: after-5.  Kind: positive.  Oracle: behaviour.
///
/// Rule (design §14.1.1): "The relay path is not vestigial and must be maintained as a first-class route."
/// Rule (design §14.1.1): "falls back to the serving node when it fails"
///
/// Given: Two leaves whose NATs, emulated by the harness, defeat hole punching.
/// When: One sends the other a message.
/// Then: The direct candidates fail and the message is delivered through the serving node's relay; the recipient decrypts it.
#[test]
#[ignore = "acceptance PAY-15: owed at milestone after-5"]
fn pay_15_deliver_payload_over_the_serving_node_when_no_di() {
    todo!("PAY-15: Deliver payload over the serving node when no direct path exists")
}
