//! GENERATED by tools/gen_stubs.py from acceptance.json.  Do not edit;
//! change the catalogue and regenerate.  Each stub is one acceptance test
//! still owed for this area.

/// Forward a stored topology transaction on every adjacent session except the one it arrived from
///
/// Spec: wire-format.md §10.1.1; design §15
/// Milestone: 4.  Kind: positive.  Oracle: behaviour.
///
/// Rule (wire-format.md §10.1.1): "a node forwards a stored transaction to every adjacent node except the one it arrived from"
/// Rule (design §15): "forward if and only if you stored it, duplicate-suppressed by `txid`, with no hop count and no acknowledgement"
///
/// Given: Node N holds authenticated sessions with its patron P, subordinates S1 and S2, a peer Q and an attached client C. An adoption whose subject lies within N's own h_store, signed by keys N holds, arrives on the session from P.
/// When: N receives the TopologyPush carrying it.
/// Then: N stores the transaction, and one TopologyPush frame carrying the object byte-for-byte is observed on each of the sessions to S1, S2, Q and C, and none on the session to P.
#[test]
#[ignore = "acceptance PRP-01: owed at milestone 4"]
fn prp_01_forward_a_stored_topology_transaction_on_every_a() {
    todo!("PRP-01: Forward a stored topology transaction on every adjacent session except the one it arrived from")
}

/// Forward nothing whose subject lies outside your own h_store
///
/// Spec: wire-format.md §10.1.1; design §15.1
/// Milestone: 4.  Kind: negative.  Oracle: behaviour.
///
/// Rule (wire-format.md §10.1.1): "A node stores a topology-class transaction when its subject falls within that node's own `h_store`"
/// Rule (wire-format.md §10.1.1): "There is no hop count, no TTL and no reach field."
/// Rule (design §15.1): "A horizon is every node within a two-edge walk of you"
///
/// Given: Node N as in PRP-01. An adoption arrives from P whose subject is three adoption edges from N and whose signatures verify.
/// When: N receives the TopologyPush.
/// Then: N's store does not gain the transaction and no TopologyPush follows on any of N's sessions. Nothing in the frame told N how far to forward; the decision came from N's own store.
#[test]
#[ignore = "acceptance PRP-02: owed at milestone 4"]
fn prp_02_forward_nothing_whose_subject_lies_outside_your() {
    todo!("PRP-02: Forward nothing whose subject lies outside your own h_store")
}

/// Neither store nor forward an object you already hold
///
/// Spec: wire-format.md §10.1.2
/// Milestone: 4.  Kind: negative.  Oracle: behaviour.
///
/// Rule (wire-format.md §10.1.2): "A node that already holds an object does not store it again and does not forward it."
///
/// Given: Node N holds a transaction with txid T, received from P and already forwarded.
/// When: The same object arrives again on the session from Q.
/// Then: N's store is unchanged and no TopologyPush carrying T is observed on any session after the second arrival.
#[test]
#[ignore = "acceptance PRP-03: owed at milestone 4"]
fn prp_03_neither_store_nor_forward_an_object_you_already() {
    todo!("PRP-03: Neither store nor forward an object you already hold")
}

/// Hold a transaction whose signer key you lack, and forward it once it verifies
///
/// Spec: wire-format.md §10.1.1
/// Milestone: 4.  Kind: liveness.  Oracle: behaviour.
///
/// Rule (wire-format.md §10.1.1): "Stored means verified."
/// Rule (wire-format.md §10.1.1): "hold it, fetch the key, and let it enter storage and propagation when it verifies"
///
/// Given: Node N as in PRP-01. An adoption arrives whose subject is within h_store but one of whose signers' KeyMaterial N does not hold.
/// When: N receives the TopologyPush, and the missing KeyMaterial is later supplied through the path N uses to fetch it.
/// Then: No TopologyPush carrying the object is observed on any session before the key arrives. After the key arrives and every signature verifies, the object is in N's store and a TopologyPush carrying it is observed on the sessions PRP-01 names.
#[test]
#[ignore = "acceptance PRP-04: owed at milestone 4"]
fn prp_04_hold_a_transaction_whose_signer_key_you_lack_and() {
    todo!("PRP-04: Hold a transaction whose signer key you lack, and forward it once it verifies")
}

/// Relay a stored object you are not a party to
///
/// Spec: wire-format.md §10.1
/// Milestone: 4.  Kind: must-accept.  Oracle: behaviour.
///
/// Rule (wire-format.md §10.1): "This governs origination, not relaying."
/// Rule (wire-format.md §10.1): "a relay changes nothing"
///
/// Given: Node N is neither the patron nor the subject of an adoption that lies within its h_store; it arrived from P.
/// When: N receives the TopologyPush.
/// Then: N forwards it as PRP-01 describes. An implementation that applies the who-may-push rule to relays, forwarding only objects it is a party to, stops the flood here and fails.
#[test]
#[ignore = "acceptance PRP-05: owed at milestone 4"]
fn prp_05_relay_a_stored_object_you_are_not_a_party_to() {
    todo!("PRP-05: Relay a stored object you are not a party to")
}

/// Carry a pushed object byte-for-byte with a body-kind tag and nothing else
///
/// Spec: wire-format.md §10.1
/// Milestone: 4.  Kind: positive.  Oracle: behaviour.
///
/// Rule (wire-format.md §10.1): "carrying the object byte-for-byte with a body-kind tag and nothing else"
/// Rule (wire-format.md §10.1): "That is the only wrapper field permitted."
///
/// Given: Node N receives a TopologyPush from P whose object bytes are recorded by the test.
/// When: N forwards it to S1.
/// Then: The frame observed on the session to S1 carries an object whose bytes equal the recorded bytes exactly, and a wrapper carrying the body-kind tag and no other field.
#[test]
#[ignore = "acceptance PRP-06: owed at milestone 4"]
fn prp_06_carry_a_pushed_object_byte_for_byte_with_a_body() {
    todo!("PRP-06: Carry a pushed object byte-for-byte with a body-kind tag and nothing else")
}

/// Let a later EndpointRecord supersede the held one and a lower or equal seqno die as a duplicate
///
/// Spec: wire-format.md §10.1.2; wire-format.md §2.3
/// Milestone: 4.  Kind: positive.  Oracle: behaviour.
///
/// Rule (wire-format.md §10.1.2): "An `EndpointRecord` therefore supersedes rather than accumulating"
/// Rule (wire-format.md §10.1.2): "the held `seqno` is greater than or equal (§2.3)"
///
/// Given: Node N holds subject X's EndpointRecord at seqno 5 in the series it has proved current.
/// When: A record for X at seqno 4, then an identical record at seqno 5, then a validly signed record at seqno 6 in the same series arrive in turn.
/// Then: After the first two arrivals N's current record for X is still the seqno 5 record and no TopologyPush follows. After the third, N's current record for X is the seqno 6 record and one TopologyPush carrying it is observed on each adjacent session except the one it arrived from.
#[test]
#[ignore = "acceptance PRP-07: owed at milestone 4"]
fn prp_07_let_a_later_endpointrecord_supersede_the_held_on() {
    todo!("PRP-07: Let a later EndpointRecord supersede the held one and a lower or equal seqno die as a duplicate")
}

/// Retain neither of two different signed contents at one seqno, forward nothing for that pair, and re-resolve
///
/// Spec: wire-format.md §10.1.2; wire-format.md §7.7
/// Milestone: 4.  Kind: negative.  Oracle: behaviour.
///
/// Rule (wire-format.md §10.1.2): "Equal `seqno` with different signed contents is malformed"
/// Rule (wire-format.md §10.1.2): "a holder retains neither as current and forwards nothing further for that `(subject, seqno)`"
/// Rule (wire-format.md §10.1.2): "it repairs by re-resolving (§7.7)"
///
/// Given: Node N holds X's EndpointRecord at seqno 5 with contents A, already forwarded.
/// When: A validly signed EndpointRecord for X at seqno 5 with different contents B arrives.
/// Then: N holds no current record for X, no TopologyPush carrying either record is observed after the conflict, and a resolution for X is observed leaving N.
#[test]
#[ignore = "acceptance PRP-08: owed at milestone 4"]
fn prp_08_retain_neither_of_two_different_signed_contents() {
    todo!("PRP-08: Retain neither of two different signed contents at one seqno, forward nothing for that pair, and re-resolve")
}

/// Drop a memo whose anchor is not your subnet's
///
/// Spec: wire-format.md §10.2; design §15.2
/// Milestone: 4.  Kind: negative.  Oracle: behaviour.
///
/// Rule (wire-format.md §10.2): "So a memo whose anchor is not your subnet's is dropped, not forwarded"
/// Rule (wire-format.md §10.2): "neither applied to a table nor passed on"
/// Rule (design §15.2): "A memo never leaves its subnet."
///
/// Given: Node N sits in the subnet anchored at A, with patron P, and keeps a memo table.
/// When: A TopologyMemo whose anchor is B arrives from a subordinate.
/// Then: No TopologyMemo is observed on N's session to P and N's memo table is unchanged.
#[test]
#[ignore = "acceptance PRP-09: owed at milestone 4"]
fn prp_09_drop_a_memo_whose_anchor_is_not_your_subnet_s() {
    todo!("PRP-09: Drop a memo whose anchor is not your subnet's")
}

/// Forward a memo unchanged to your patron, and stop at the root
///
/// Spec: wire-format.md §10.2
/// Milestone: 4.  Kind: positive.  Oracle: behaviour.
///
/// Rule (wire-format.md §10.2): "A receiving node forwards the memo to its own patron, unchanged except that nothing is added"
/// Rule (wire-format.md §10.2): "A root has no patron and forwarding stops there."
///
/// Given: Node N with patron P, and root R with no patron, each receive a memo from a subordinate about a slot neither holds.
/// When: Each processes the memo.
/// Then: On N's session to P a TopologyMemo is observed whose bytes equal the received memo's. R sends no TopologyMemo on any session.
#[test]
#[ignore = "acceptance PRP-10: owed at milestone 4"]
fn prp_10_forward_a_memo_unchanged_to_your_patron_and_stop() {
    todo!("PRP-10: Forward a memo unchanged to your patron, and stop at the root")
}

/// Forward no memo about a slot you hold at or after its timestamp
///
/// Spec: wire-format.md §10.2
/// Milestone: 4.  Kind: negative.  Oracle: behaviour.
///
/// Rule (wire-format.md §10.2): "A node holding that slot at or after the memo's timestamp does not forward it."
///
/// Given: Node N with patron P holds subordinate slot k with an occupant and a timestamp t.
/// When: A memo naming N in field 1 and slot k, with field 4 at or before t, arrives from below.
/// Then: No TopologyMemo is observed on N's session to P.
#[test]
#[ignore = "acceptance PRP-11: owed at milestone 4"]
fn prp_11_forward_no_memo_about_a_slot_you_hold_at_or_afte() {
    todo!("PRP-11: Forward no memo about a slot you hold at or after its timestamp")
}

/// Treat a memo naming you as a cycle, confirm it against your own row, and disavow the subordinate that forwarded it
///
/// Spec: wire-format.md §10.2.1; wire-format.md §10.2.4; design §15.2
/// Milestone: 4.  Kind: positive.  Oracle: model.
///
/// Rule (wire-format.md §10.2.1): "If field 1 is you, a memo you originated has come back to you from below"
/// Rule (wire-format.md §10.2.1): "It fires at any depth, on the memo alone, and terminates the memo there."
/// Rule (wire-format.md §10.2.4): "It disavows the direct subordinate that forwarded the memo to it"
/// Rule (wire-format.md §10.2.4): "Reason code 5, without prejudice"
///
/// Given: Node N holds subordinate S in slot k and a row matching that. A cycle below S has formed, so a memo N originated for slot k returns to N on the session from S.
/// When: N receives the memo.
/// Then: No TopologyMemo is forwarded further. A disavowal transaction by N naming S with reason code 5 is observed, and N's slot k is empty afterwards.
#[test]
#[ignore = "acceptance PRP-12: owed at milestone 4"]
fn prp_12_treat_a_memo_naming_you_as_a_cycle_confirm_it_ag() {
    todo!("PRP-12: Treat a memo naming you as a cycle, confirm it against your own row, and disavow the subordinate that forwarded it")
}

/// Act on no memo your own records do not confirm
///
/// Spec: wire-format.md §10.2.3
/// Milestone: 4.  Kind: negative.  Oracle: behaviour.
///
/// Rule (wire-format.md §10.2.3): "No node acts on a memo alone."
/// Rule (wire-format.md §10.2.3): "A fabricated memo fails both, at no traffic cost."
///
/// Given: Node N holds subordinate S in slot k. An attacker below S injects a memo naming N in field 1 and slot k but naming an occupant N's row does not hold.
/// When: N receives the memo from S.
/// Then: No disavowal is emitted, no archive fetch is issued, the memo is not forwarded, and N's rows are unchanged.
#[test]
#[ignore = "acceptance PRP-13: owed at milestone 4"]
fn prp_13_act_on_no_memo_your_own_records_do_not_confirm() {
    todo!("PRP-13: Act on no memo your own records do not confirm")
}

/// Send a memo to the nearest infrastructure node when the patron holds no session
///
/// Spec: wire-format.md §10.2; design §12.6.3
/// Milestone: 4.  Kind: positive.  Oracle: behaviour.
///
/// Rule (wire-format.md §10.2): "Where no session with the patron exists, the memo goes to the nearest infrastructure node on the patron chain instead"
///
/// Given: Node N's patron L is a light client that holds no sessions; N's serving node I is the nearest infrastructure node on the patron chain.
/// When: N adopts a subordinate and originates the corresponding memo.
/// Then: The TopologyMemo is observed on N's session to I, and nothing is attempted toward L.
#[test]
#[ignore = "acceptance PRP-14: owed at milestone 4"]
fn prp_14_send_a_memo_to_the_nearest_infrastructure_node_w() {
    todo!("PRP-14: Send a memo to the nearest infrastructure node when the patron holds no session")
}

/// Repair a missed object by reconciliation that replays the same frame
///
/// Spec: wire-format.md §10.1.3
/// Milestone: 4.  Kind: liveness.  Oracle: behaviour.
///
/// Rule (wire-format.md §10.1.3): "reconciliation is a replay of the same frames rather than a distinct mechanism"
/// Rule (wire-format.md §10.1.3): "Loss is detected at the receiver, which is the party that can act."
///
/// Given: An adoption within N's h_store was lost in flight, so N holds neither it nor a later object that back-points to it. The test triggers reconciliation between N and its patron, since when it runs is local.
/// When: N reconciles.
/// Then: The missing object arrives at N as a TopologyPush frame of the same shape as the original, N stores it, and forwards it as PRP-01 describes.
#[test]
#[ignore = "acceptance PRP-15: owed at milestone 4"]
fn prp_15_repair_a_missed_object_by_reconciliation_that_re() {
    todo!("PRP-15: Repair a missed object by reconciliation that replays the same frame")
}
