//! GENERATED by tools/gen_stubs.py from acceptance.json.  Do not edit;
//! change the catalogue and regenerate.  Each stub is one acceptance test
//! still owed for this area.

/// Queue messages for a client that is not attached, and report the count at its next attach.
///
/// Spec: design §14.1.6; wire-format.md §8.2; infra-client-requirements.md §2
/// Milestone: 3.  Kind: positive.  Oracle: behaviour.
///
/// Rule (design §14.1.6): "Undelivered messages queue indefinitely at the recipient's serving node"
/// Rule (wire-format.md §8.2): "messages queued for this client AT THE RESPONDING NODE"
/// Rule (infra-client-requirements.md §2): "Hold ciphertext for offline clients"
///
/// Given: N is patron and serving node of light client C; C is not attached. Sender X submits k ciphertext messages addressed to C's keyhash to N, and N accepts each.
/// When: C attaches to N.
/// Then: N's AttachAck carries field 4 equal to k.
///
/// Interpretation: The payload submission path by which a sender hands a message for C to N has no wire encoding (design §14.2.4's integration decisions are open); the test uses the implementation's own and observes the queue through AttachAck field 4 and the drain streams.
#[test]
#[ignore = "acceptance QUE-01: owed at milestone 3"]
fn que_01_queue_messages_for_a_client_that_is_not_attached() {
    todo!("QUE-01: Queue messages for a client that is not attached, and report the count at its next attach.")
}

/// Deliver queued ciphertext, unchanged, when the client returns.
///
/// Spec: design §14.1.6; wire-format.md §9.2; design §12.6.3
/// Milestone: 3.  Kind: positive.  Oracle: behaviour.
///
/// Rule (design §14.1.6): "The message waits; it is not lost."
/// Rule (wire-format.md §9.2): "Unidirectional streams: payload delivery, queue drain"
/// Rule (design §12.6.3): "The recipient's serving node holds ciphertext until reconnect"
///
/// Given: k messages are queued at N for C, each a distinct ciphertext the harness recorded at submission.
/// When: C attaches to N and reads its unidirectional streams.
/// Then: C receives k drain deliveries, and the set of ciphertexts received equals the set submitted, byte for byte.
#[test]
#[ignore = "acceptance QUE-02: owed at milestone 3"]
fn que_02_deliver_queued_ciphertext_unchanged_when_the_cli() {
    todo!("QUE-02: Deliver queued ciphertext, unchanged, when the client returns.")
}

/// Delete on delivery: a second attach finds nothing and redelivers nothing.
///
/// Spec: design §14.1.6; infra-client-requirements.md §2; wire-format.md §8.2
/// Milestone: 3.  Kind: positive.  Oracle: behaviour.
///
/// Rule (design §14.1.6): "No copy outlives delivery. Deletion on delivery is immediate and leaves nothing recoverable — no journal, no tombstone."
/// Rule (infra-client-requirements.md §2): "Delete on delivery, immediately, leaving nothing recoverable."
/// Rule (wire-format.md §8.2): "messages queued for this client AT THE RESPONDING NODE"
///
/// Given: k messages were queued at N for C; C attached and received all k on drain streams, then closed the session.
/// When: C attaches to N again.
/// Then: N's AttachAck carries field 4 equal to 0 and no drain delivery follows; N's inspectable queue store holds no copy of any of the k ciphertexts.
#[test]
#[ignore = "acceptance QUE-03: owed at milestone 3"]
fn que_03_delete_on_delivery_a_second_attach_finds_nothing() {
    todo!("QUE-03: Delete on delivery: a second attach finds nothing and redelivers nothing.")
}

/// Keep no crash-recovery copy that outlives a delivery.
///
/// Spec: infra-client-requirements.md §2; design §14.1.6
/// Milestone: 3.  Kind: negative.  Oracle: behaviour.
///
/// Rule (infra-client-requirements.md §2): "No journal, no tombstone, no crash-recovery copy that outlives the delete. Durable storage for your own crash recovery is your backup problem and must not extend a message's life."
/// Rule (design §14.1.6): "No copy outlives delivery."
///
/// Given: k messages were queued at N for C; C attached and received all k, then closed the session.
/// When: N's process is killed without warning and restarted from whatever it persisted; C attaches to N again.
/// Then: N's AttachAck carries field 4 equal to 0, no drain delivery follows, and none of the k ciphertexts is present in N's storage after the restart.
#[test]
#[ignore = "acceptance QUE-04: owed at milestone 3"]
fn que_04_keep_no_crash_recovery_copy_that_outlives_a_deli() {
    todo!("QUE-04: Keep no crash-recovery copy that outlives a delivery.")
}

/// Hold only ciphertext, recipient keyhash and arrival time while a message waits.
///
/// Spec: infra-client-requirements.md §2; design §14.1.6
/// Milestone: 3.  Kind: negative.  Oracle: behaviour.
///
/// Rule (infra-client-requirements.md §2): "Hold the minimum while a message waits: ciphertext, recipient keyhash, arrival time. Nothing further."
/// Rule (design §14.1.6): "Queue metadata is the minimum: ciphertext, recipient keyhash, arrival time."
///
/// Given: Sender X submitted one message addressed to C to N while C was not attached, and N accepted it; N exposes its queue store to the test.
/// When: The test inspects N's record of the waiting message.
/// Then: The record consists of the ciphertext, C's keyhash and an arrival time, and carries nothing further: in particular no identity or address of X.
#[test]
#[ignore = "acceptance QUE-05: owed at milestone 3"]
fn que_05_hold_only_ciphertext_recipient_keyhash_and_arriv() {
    todo!("QUE-05: Hold only ciphertext, recipient keyhash and arrival time while a message waits.")
}

/// Refuse the newest message at the cap and tell the sender; keep what is queued.
///
/// Spec: design §14.1.6; infra-client-requirements.md §2
/// Milestone: 3.  Kind: negative.  Oracle: behaviour.
///
/// Rule (design §14.1.6): "At the ceiling: refuse the newest message and tell the sender. Never drop the oldest."
/// Rule (infra-client-requirements.md §2): "At the cap, refuse the newest message and tell the sender"
///
/// Given: The queue cap is unset (design §21.1) and is a test parameter: N is configured with a per-subordinate storage cap sized so that exactly k test messages for one subordinate fit. C is not attached; X has submitted k messages for C and N accepted each.
/// When: X submits a (k+1)th message addressed to C.
/// Then: X receives a refusal for the (k+1)th message, distinguishable from acceptance; at C's next attach field 4 equals k and the k earlier ciphertexts are all delivered.
///
/// Interpretation: The sender-facing refusal has no wire encoding; the test checks only that X receives a refusal for that message that differs from the acceptance the earlier k received.
#[test]
#[ignore = "acceptance QUE-06: owed at milestone 3"]
fn que_06_refuse_the_newest_message_at_the_cap_and_tell_th() {
    todo!("QUE-06: Refuse the newest message at the cap and tell the sender; keep what is queued.")
}

/// Let no flood displace what is already queued.
///
/// Spec: infra-client-requirements.md §2; design §14.1.6
/// Milestone: 3.  Kind: robustness.  Oracle: behaviour.
///
/// Rule (infra-client-requirements.md §2): "Never drop the oldest: it destroys a message the sender believes was accepted, and it lets anyone who can reach the queue flush what is already in it."
/// Rule (design §14.1.6): "Refuse-newest bounds an attacker to denying new delivery, which the sender sees."
///
/// Given: The queue cap is unset (design §21.1) and is a test parameter: N is configured with a per-subordinate storage cap sized so that exactly k test messages for one subordinate fit. C is not attached; k legitimate messages for C are queued and N is at C's cap.
/// When: An attacker A submits several times k further messages addressed to C in quick succession, then C attaches.
/// Then: Every one of A's messages is refused to A; C's AttachAck carries field 4 equal to k and the k legitimate ciphertexts are all delivered, none replaced by A's.
///
/// Interpretation: The sender-facing refusal has no wire encoding; the test checks only that A receives a refusal for each message.
#[test]
#[ignore = "acceptance QUE-07: owed at milestone 3"]
fn que_07_let_no_flood_displace_what_is_already_queued() {
    todo!("QUE-07: Let no flood displace what is already queued.")
}

/// Keep a queued message across an absence of any length.
///
/// Spec: infra-client-requirements.md §2; design §14.1.6
/// Milestone: 3.  Kind: positive.  Oracle: behaviour.
///
/// Rule (infra-client-requirements.md §2): "No time limit: a message survives an absence of any length."
/// Rule (design §14.1.6): "No time limit; a space limit."
///
/// Given: One message is queued at N for C, who is not attached. The absence length is a test parameter: the harness advances N's clock by a chosen long duration D and lets N run on.
/// When: After D, C attaches to N.
/// Then: N's AttachAck carries field 4 equal to 1 and the message is delivered on a drain stream.
#[test]
#[ignore = "acceptance QUE-08: owed at milestone 3"]
fn que_08_keep_a_queued_message_across_an_absence_of_any_l() {
    todo!("QUE-08: Keep a queued message across an absence of any length.")
}

/// Apply the cap per subordinate, so one full queue does not refuse another's mail.
///
/// Spec: design §14.1.6; infra-client-requirements.md §2
/// Milestone: 3.  Kind: positive.  Oracle: behaviour.
///
/// Rule (design §14.1.6): "Undelivered messages queue indefinitely at the recipient's serving node"
/// Rule (infra-client-requirements.md §2): "Queue indefinitely, bounded by a per-subordinate storage cap"
///
/// Given: The queue cap is unset (design §21.1) and is a test parameter: N is configured with a per-subordinate storage cap sized so that exactly k test messages for one subordinate fit. N serves C1 and C2, neither attached; C1's queue holds k messages and is at its cap.
/// When: X submits one message addressed to C2, then C2 attaches.
/// Then: N accepts the message for C2, and C2's AttachAck carries field 4 equal to 1 with the message delivered on a drain stream.
#[test]
#[ignore = "acceptance QUE-09: owed at milestone 3"]
fn que_09_apply_the_cap_per_subordinate_so_one_full_queue() {
    todo!("QUE-09: Apply the cap per subordinate, so one full queue does not refuse another's mail.")
}

/// Queue for a client the node has marked unreachable, and deliver at its fresh attach.
///
/// Spec: design §14.1.2; infra-client-requirements.md §2; design §14.1.6
/// Milestone: 4.  Kind: positive.  Oracle: behaviour.
///
/// Rule (design §14.1.2): "the serving node marks the client unreachable; material for it queues as it always did, and delivery waits for its return."
/// Rule (infra-client-requirements.md §2): "Hold ciphertext for offline clients"
/// Rule (design §14.1.6): "The message waits; it is not lost."
///
/// Given: C is attached to N with a heartbeat interval I (unset, design §21.1; a test parameter). The harness blackholes all packets between C and N for three full intervals so that N marks C unreachable.
/// When: X submits one message addressed to C; the blackhole is lifted and C performs a fresh attach to N.
/// Then: N's AttachAck carries field 4 equal to 1 and the message is delivered on a drain stream.
///
/// Interpretation: Whether N ends the old session on marking C unreachable is not stated; the test has C attach afresh and does not depend on the old session's fate.
#[test]
#[ignore = "acceptance QUE-10: owed at milestone 4"]
fn que_10_queue_for_a_client_the_node_has_marked_unreachab() {
    todo!("QUE-10: Queue for a client the node has marked unreachable, and deliver at its fresh attach.")
}

/// Distinguish an offline subordinate from a keyhash with no record.
///
/// Spec: design §14.1.2; design §7.4.3
/// Milestone: 4.  Kind: negative.  Oracle: behaviour.
///
/// Rule (design §14.1.2): "§7.4.3's queue mechanism depends on the node distinguishing "offline" from "no record""
/// Rule (design §7.4.3): "Queries to an offline light client queue at its patron, resolving when the client next connects"
///
/// Given: N serves C, who is not attached, and holds no record of keyhash Z, which belongs to no node in N's topology.
/// When: X submits one message addressed to C and one addressed to Z.
/// Then: The message for C is queued (C's next AttachAck carries field 4 equal to 1); nothing is queued for Z in N's inspectable store, and the answer X receives for Z differs from the one it received for C.
///
/// Interpretation: Neither the acceptance nor the no-record answer to the sender has a wire encoding; the test checks only that the two answers are distinguishable to X.
#[test]
#[ignore = "acceptance QUE-11: owed at milestone 4"]
fn que_11_distinguish_an_offline_subordinate_from_a_keyhas() {
    todo!("QUE-11: Distinguish an offline subordinate from a keyhash with no record.")
}

/// Report no queued messages from a failover sibling, which holds no queue state.
///
/// Spec: infra-client-requirements.md §2; design §14.1.6; wire-format.md §8.2
/// Milestone: 4.  Kind: negative.  Oracle: behaviour.
///
/// Rule (infra-client-requirements.md §2): "Do not replicate queue state to siblings."
/// Rule (design §14.1.6): "Siblings do not hold queue state."
/// Rule (wire-format.md §8.2): "messages queued for this client AT THE RESPONDING NODE"
///
/// Given: N and S are siblings; k messages are queued at N for C; nothing addressed to C was ever submitted to S. C is attached to N with interval I (a test parameter) and holds S's SiblingRef with KeyMaterial.
/// When: N goes dark; after three missed intervals C attaches to S.
/// Then: S's AttachAck carries field 1 equal to 1 and field 4 equal to 0, and S delivers nothing on drain streams.
#[test]
#[ignore = "acceptance QUE-12: owed at milestone 4"]
fn que_12_report_no_queued_messages_from_a_failover_siblin() {
    todo!("QUE-12: Report no queued messages from a failover sibling, which holds no queue state.")
}

/// Collect from the patron, in full, once it returns after a failover.
///
/// Spec: design §14.1.6; infra-client-requirements.md §2
/// Milestone: 4.  Kind: liveness.  Oracle: behaviour.
///
/// Rule (design §14.1.6): "a client attached to a sibling still collects from its own serving node once that node returns"
/// Rule (infra-client-requirements.md §2): "a client attached to a sibling collects from its own serving node when that node returns"
///
/// Given: k messages are queued at N for C; N went dark and C holds a degraded session on sibling S.
/// When: N returns; C's session on S ends and C performs a fresh attach.
/// Then: C attaches to N, N's AttachAck carries field 4 equal to k, and all k ciphertexts are delivered on drain streams.
#[test]
#[ignore = "acceptance QUE-13: owed at milestone 4"]
fn que_13_collect_from_the_patron_in_full_once_it_returns() {
    todo!("QUE-13: Collect from the patron, in full, once it returns after a failover.")
}

/// End a running session once the node holds supersession evidence for its credential.
///
/// Spec: design §12.6.5; infra-client-requirements.md §2
/// Milestone: 3.  Kind: negative.  Oracle: model.
///
/// Rule (design §12.6.5): "sessions under the superseded credential terminate, and nothing further is delivered to it, queued material and capture-key grants included."
/// Rule (infra-client-requirements.md §2): "Terminate its sessions and deliver nothing further to it, its queue included."
///
/// Given: C is attached to N under keyhash K_old with a live session.
/// When: N takes authenticated supersession evidence for C's binding: a verified reissue chain onto a new series, or a recovery it has validated.
/// Then: N closes C's connection, and no payload or drain delivery reaches that session after the evidence was taken.
///
/// Interpretation: No close code is assigned for ending a session on supersession; the test checks that the connection is closed by N and not which code it carries.
#[test]
#[ignore = "acceptance QUE-14: owed at milestone 3"]
fn que_14_end_a_running_session_once_the_node_holds_supers() {
    todo!("QUE-14: End a running session once the node holds supersession evidence for its credential.")
}

/// Deliver nothing queued to a credential the node has verified superseded.
///
/// Spec: design §12.6.5; infra-client-requirements.md §2
/// Milestone: 3.  Kind: negative.  Oracle: model.
///
/// Rule (design §12.6.5): "sessions under the superseded credential terminate, and nothing further is delivered to it, queued material and capture-key grants included."
/// Rule (infra-client-requirements.md §2): "Stop serving a binding you have verified superseded"
///
/// Given: k messages are queued at N for keyhash K_old; N has since taken authenticated supersession evidence for that binding (a verified reissue chain onto a new series, or a validated recovery).
/// When: A client presenting K_old dials N and sends Attach.
/// Then: N sends no AttachAck and no drain delivery on that connection.
///
/// Interpretation: Whether the attach is closed with application close code 1 or otherwise is not assigned; the test checks only that no AttachAck and no delivery follow.
#[test]
#[ignore = "acceptance QUE-15: owed at milestone 3"]
fn que_15_deliver_nothing_queued_to_a_credential_the_node() {
    todo!("QUE-15: Deliver nothing queued to a credential the node has verified superseded.")
}

/// Hand nothing queued for a superseded keyhash to its successor.
///
/// Spec: design §14.1.6; design §12.6.5
/// Milestone: 3.  Kind: negative.  Oracle: model.
///
/// Rule (design §14.1.6): "Queue metadata is the minimum: ciphertext, recipient keyhash, arrival time."
/// Rule (design §12.6.5): "nothing further is delivered to it, queued material and capture-key grants included."
///
/// Given: k messages are queued at N for keyhash K_old; N has taken authenticated supersession evidence moving that binding to K_new, and nothing addressed to K_new has been submitted.
/// When: A client presenting K_new attaches to N.
/// Then: N's AttachAck carries field 4 equal to 0 and no drain delivery carries any of the k ciphertexts.
///
/// Interpretation: That delivery is keyed by the queued recipient keyhash is the model's reading (tamarin/compliant/attach); the specification says nothing further goes to the superseded credential and does not say whether a successor collects material queued for its predecessor.
#[test]
#[ignore = "acceptance QUE-16: owed at milestone 3"]
fn que_16_hand_nothing_queued_for_a_superseded_keyhash_to() {
    todo!("QUE-16: Hand nothing queued for a superseded keyhash to its successor.")
}
