//! GENERATED by tools/gen_stubs.py from acceptance.json.  Do not edit;
//! change the catalogue and regenerate.  Each stub is one acceptance test
//! still owed for this area.

/// Queue for a client the node has marked unreachable, and deliver at its fresh attach.
///
/// Spec: design §14.1.2; infra-client-requirements.md §2; design §14.1.6
/// Milestone: 4.  Kind: positive.  Oracle: behaviour.
///
/// Rule (design §14.1.2): "the serving node marks the client unreachable; material for it queues as it always did, and delivery waits for its return."
/// Rule (infra-client-requirements.md §2): "Hold ciphertext for offline clients"
/// Rule (design §14.1.6): "The message waits; it is not lost."
///
/// Given: C is attached to N with a heartbeat interval I (unset, design §21.1; a test parameter). The harness blackholes all packets between C and N for three full intervals so that N marks C unreachable.
/// When: X submits one message addressed to C; the blackhole is lifted and C performs a fresh attach to N.
/// Then: N's AttachAck carries field 4 equal to 1 and the message is delivered on a drain stream.
///
/// Interpretation: Whether N ends the old session on marking C unreachable is not stated; the test has C attach afresh and does not depend on the old session's fate.
#[test]
#[ignore = "acceptance QUE-10: owed at milestone 4"]
fn que_10_queue_for_a_client_the_node_has_marked_unreachab() {
    todo!("QUE-10: Queue for a client the node has marked unreachable, and deliver at its fresh attach.")
}

/// Distinguish an offline subordinate from a keyhash with no record.
///
/// Spec: design §14.1.2; design §7.4.3
/// Milestone: 4.  Kind: negative.  Oracle: behaviour.
///
/// Rule (design §14.1.2): "§7.4.3's queue mechanism depends on the node distinguishing "offline" from "no record""
/// Rule (design §7.4.3): "Queries to an offline light client queue at its patron, resolving when the client next connects"
///
/// Given: N serves C, who is not attached, and holds no record of keyhash Z, which belongs to no node in N's topology.
/// When: X submits one message addressed to C and one addressed to Z.
/// Then: The message for C is queued (C's next AttachAck carries field 4 equal to 1); nothing is queued for Z in N's inspectable store, and the answer X receives for Z differs from the one it received for C.
///
/// Interpretation: Neither the acceptance nor the no-record answer to the sender has a wire encoding; the test checks only that the two answers are distinguishable to X.
#[test]
#[ignore = "acceptance QUE-11: owed at milestone 4"]
fn que_11_distinguish_an_offline_subordinate_from_a_keyhas() {
    todo!("QUE-11: Distinguish an offline subordinate from a keyhash with no record.")
}

/// Report no queued messages from a failover sibling, which holds no queue state.
///
/// Spec: infra-client-requirements.md §2; design §14.1.6; wire-format.md §8.2
/// Milestone: 4.  Kind: negative.  Oracle: behaviour.
///
/// Rule (infra-client-requirements.md §2): "Do not replicate queue state to siblings."
/// Rule (design §14.1.6): "Siblings do not hold queue state."
/// Rule (wire-format.md §8.2): "messages queued for this client AT THE RESPONDING NODE"
///
/// Given: N and S are siblings; k messages are queued at N for C; nothing addressed to C was ever submitted to S. C is attached to N with interval I (a test parameter) and holds S's SiblingRef with KeyMaterial.
/// When: N goes dark; after three missed intervals C attaches to S.
/// Then: S's AttachAck carries field 1 equal to 1 and field 4 equal to 0, and S delivers nothing on drain streams.
#[test]
#[ignore = "acceptance QUE-12: owed at milestone 4"]
fn que_12_report_no_queued_messages_from_a_failover_siblin() {
    todo!("QUE-12: Report no queued messages from a failover sibling, which holds no queue state.")
}

/// Collect from the patron, in full, once it returns after a failover.
///
/// Spec: design §14.1.6; infra-client-requirements.md §2
/// Milestone: 4.  Kind: liveness.  Oracle: behaviour.
///
/// Rule (design §14.1.6): "a client attached to a sibling still collects from its own serving node once that node returns"
/// Rule (infra-client-requirements.md §2): "a client attached to a sibling collects from its own serving node when that node returns"
///
/// Given: k messages are queued at N for C; N went dark and C holds a degraded session on sibling S.
/// When: N returns; C's session on S ends and C performs a fresh attach.
/// Then: C attaches to N, N's AttachAck carries field 4 equal to k, and all k ciphertexts are delivered on drain streams.
#[test]
#[ignore = "acceptance QUE-13: owed at milestone 4"]
fn que_13_collect_from_the_patron_in_full_once_it_returns() {
    todo!("QUE-13: Collect from the patron, in full, once it returns after a failover.")
}
