//! GENERATED by tools/gen_stubs.py from acceptance.json.  Do not edit;
//! change the catalogue and regenerate.  Each stub is one acceptance test
//! still owed for this area.

/// Assemble a recovery adoption carrying both halves and no other evidence field
///
/// Spec: wire-format.md §4.1
/// Milestone: after-5.  Kind: positive.  Oracle: fixture.
///
/// Rule (wire-format.md §4.1): "A recovery requires both, always: the old key and a present human."
/// Rule (wire-format.md §4.1): "EXACTLY ONE of fields 6, 8 and 9 is present"
/// Rule (wire-format.md §4.1): "with `external_aad = "rhtn/1:successor"`"
///
/// Given: Subject S holds prior key k1 and new key k2, meets prior counterparty V who recognises S, and is re-adopted by patron P.
/// When: S's client assembles the adoption.
/// Then: The adoption carries field 6 and neither field 8 nor field 9; field 6's responses are sorted ascending by verifier keyhash and include a `match`; field 6's field 3 is a hybrid COSE_Sign by k1 over the successor statement naming k1, k2 and P under the successor tag, and the corpus validator accepts the envelope.
#[test]
#[ignore = "acceptance REC-01: owed at milestone after-5"]
fn rec_01_assemble_a_recovery_adoption_carrying_both_halve() {
    todo!("REC-01: Assemble a recovery adoption carrying both halves and no other evidence field")
}

/// Reject a recovery whose successor statement names a different successor or patron
///
/// Spec: wire-format.md §4.1
/// Milestone: after-5.  Kind: negative.  Oracle: model.
///
/// Rule (wire-format.md §4.1): "A verifier MUST check `new_key` and `patron_key` against adoption fields 1 and 2 and reject on mismatch."
///
/// Given: Patron P receives a recovery adoption whose field 3 successor statement was lifted from another recovery and names a different new key, then one naming a different patron.
/// When: P evaluates each.
/// Then: P countersigns neither and records no binding for either.
#[test]
#[ignore = "acceptance REC-02: owed at milestone after-5"]
fn rec_02_reject_a_recovery_whose_successor_statement_name() {
    todo!("REC-02: Reject a recovery whose successor statement names a different successor or patron")
}

/// Sign a recovery verifier response with both components, and the consent classically
///
/// Spec: wire-format.md §4.1
/// Milestone: after-5.  Kind: positive.  Oracle: fixture.
///
/// Rule (wire-format.md §4.1): "A verifier's authentication inside a `Recovery` block is HYBRID"
/// Rule (wire-format.md §4.1): "Field 7 stays classical"
///
/// Given: Verifier V answering in a recovery ceremony for subject S.
/// When: V's client signs its response.
/// Then: The response's field 9 is a detached COSE_Sign with one Ed25519 and one ML-DSA-65 entry that both verify under V, and field 7 is a single classical COSE_Sign1 by S's new key.
#[test]
#[ignore = "acceptance REC-03: owed at milestone after-5"]
fn rec_03_sign_a_recovery_verifier_response_with_both_comp() {
    todo!("REC-03: Sign a recovery verifier response with both components, and the consent classically")
}

/// Run the recovery meeting as a ceremony in which the verifier is its own querier
///
/// Spec: wire-format.md §4.1; design §9.1
/// Milestone: after-5.  Kind: positive.  Oracle: behaviour.
///
/// Rule (wire-format.md §4.1): "The querier is the verifier"
/// Rule (wire-format.md §4.1): "`selection_basis` MUST be 0 (met) in every response here"
/// Rule (design §9.1): "the counterparty is its own querier"
///
/// Given: Subject S stands before prior counterparty V with S's new key on the harness.
/// When: The recovery ceremony runs.
/// Then: V's client generates the VerificationQuery with field 2 naming V and the meeting's own pre-commitment, S's new key countersigns it, and V's response carries selection basis 0 and field 8 equal to S's prior key.
#[test]
#[ignore = "acceptance REC-04: owed at milestone after-5"]
fn rec_04_run_the_recovery_meeting_as_a_ceremony_in_which() {
    todo!("REC-04: Run the recovery meeting as a ceremony in which the verifier is its own querier")
}

/// Seal every old line as the old key's last act before publishing a rotation
///
/// Spec: design §9.0; light-client-requirements.md §2; wire-format.md §4.6
/// Milestone: after-5.  Kind: positive.  Oracle: model.
///
/// Rule (design §9.0): "Seal the old line as the old key's last act."
/// Rule (light-client-requirements.md §2): "as the last thing the old key does"
/// Rule (wire-format.md §4.6): "sets the counter it is leaving to the maximum, then reissues naming that value"
///
/// Given: Subject S with prior key k1 holds series in two patron relationships and rotates to k2.
/// When: S's client performs the rotation.
/// Then: Before the adoption under k2 is pushed, a self-signed SignedLocator by k1 at the maximum counter is produced for each of the two series, and nothing signed by k1 follows them.
#[test]
#[ignore = "acceptance REC-05: owed at milestone after-5"]
fn rec_05_seal_every_old_line_as_the_old_key_s_last_act_be() {
    todo!("REC-05: Seal every old line as the old key's last act before publishing a rotation")
}

/// On suspected compromise, seal, then reissue naming the sealed counter, for every relationship
///
/// Spec: light-client-requirements.md §2; wire-format.md §4.6
/// Milestone: after-5.  Kind: positive.  Oracle: behaviour.
///
/// Rule (light-client-requirements.md §2): "On suspected key compromise, seal before you take a series reissue."
/// Rule (wire-format.md §4.6): "Seal, then reissue, then repeat for every other patron relationship whose line is worth securing."
///
/// Given: Subject S holds two patron relationships and marks its key as suspected compromised.
/// When: S's client acts on the suspicion.
/// Then: For each relationship, in order, a self-signed locator at the maximum counter is produced, then a type-7 reissue whose field 3 equals that maximum and whose field 4 is a fresh series at counter 0, countersigned by that patron.
#[test]
#[ignore = "acceptance REC-06: owed at milestone after-5"]
fn rec_06_on_suspected_compromise_seal_then_reissue_naming() {
    todo!("REC-06: On suspected compromise, seal, then reissue naming the sealed counter, for every relationship")
}

/// Never reissue into a series you have occupied
///
/// Spec: light-client-requirements.md §2; wire-format.md §4.6
/// Milestone: after-5.  Kind: negative.  Oracle: behaviour.
///
/// Rule (light-client-requirements.md §2): "Never take a series reissue into a series you have occupied before."
/// Rule (wire-format.md §4.6): "The new series MUST NOT be one the node has previously occupied."
///
/// Given: Subject S has occupied series s1 then s2 and is now in s3.
/// When: S's client is asked to produce a reissue whose field 4 names s1 or s2.
/// Then: No such reissue is produced; a reissue into an unused series is.
#[test]
#[ignore = "acceptance REC-07: owed at milestone after-5"]
fn rec_07_never_reissue_into_a_series_you_have_occupied() {
    todo!("REC-07: Never reissue into a series you have occupied")
}

/// Reject a reissue naming a series already in the chain you hold
///
/// Spec: wire-format.md §4.6; wire-format.md §4.6.1
/// Milestone: after-5.  Kind: negative.  Oracle: model.
///
/// Rule (wire-format.md §4.6): "who MUST reject a reissue naming a series already in it"
/// Rule (wire-format.md §4.6.1): "Chain length is the order."
///
/// Given: Holder H has the chain for S: adoption into s1, reissue to s2.
/// When: A patron-countersigned reissue for S with field 4 equal to s1 arrives, then one into an unused s3.
/// Then: The first is rejected and H's chain is unchanged; the second extends H's chain to length three.
#[test]
#[ignore = "acceptance REC-08: owed at milestone after-5"]
fn rec_08_reject_a_reissue_naming_a_series_already_in_the() {
    todo!("REC-08: Reject a reissue naming a series already in the chain you hold")
}

/// Reject records in an abandoned series whatever their counter
///
/// Spec: wire-format.md §4.6
/// Milestone: after-5.  Kind: negative.  Oracle: model.
///
/// Rule (wire-format.md §4.6): "MUST reject records in it whatever their counter"
///
/// Given: Holder H has S's chain showing s1 left for s2.
/// When: A validly signed locator for S in s1 at a counter above every s1 record H holds arrives, then a locator in s2 at counter 1.
/// Then: The s1 locator is rejected; the s2 locator is installed.
#[test]
#[ignore = "acceptance REC-09: owed at milestone after-5"]
fn rec_09_reject_records_in_an_abandoned_series_whatever_t() {
    todo!("REC-09: Reject records in an abandoned series whatever their counter")
}

/// Present the chain when asked to rank, and never propagate it
///
/// Spec: light-client-requirements.md §2; wire-format.md §4.6.1
/// Milestone: after-5.  Kind: positive.  Oracle: behaviour.
///
/// Rule (light-client-requirements.md §2): "Keep the chain that proves your current series"
/// Rule (light-client-requirements.md §2): "It is presented, never propagated"
/// Rule (wire-format.md §4.6.1): "Presentation, not propagation, and not a history scan."
///
/// Given: Subject S holds its adoption and one reissue; a counterparty asks S to prove its series.
/// When: S answers, and the test watches S's sessions for a period afterwards.
/// Then: The adoption and the reissue are presented to the counterparty; no TopologyPush carrying either leaves S in response.
#[test]
#[ignore = "acceptance REC-10: owed at milestone after-5"]
fn rec_10_present_the_chain_when_asked_to_rank_and_never_p() {
    todo!("REC-10: Present the chain when asked to rank, and never propagate it")
}

/// Let a thief's seal freeze a chainless holder's entry, and never move it afterwards
///
/// Spec: wire-format.md §4.6
/// Milestone: after-5.  Kind: negative.  Oracle: model.
///
/// Rule (wire-format.md §4.6): "against them it is a race the thief can win by reaching a reader first"
/// Rule (wire-format.md §4.6): "What a recipient ends up holding is an address that can never be updated."
/// Rule (wire-format.md §4.6): "So a thief who seals first burns a line rather than capturing one."
///
/// Given: Holder H has a cached locator for S in series s at counter 5 and no chain. A thief holding S's key produces a locator in s at the maximum counter.
/// When: The thief's locator reaches H first; S's locator in s at counter 6 arrives later.
/// Then: H installs the thief's locator, rejects S's counter-6 locator, and no further record in s changes H's entry.
#[test]
#[ignore = "acceptance REC-11: owed at milestone after-5"]
fn rec_11_let_a_thief_s_seal_freeze_a_chainless_holder_s_e() {
    todo!("REC-11: Let a thief's seal freeze a chainless holder's entry, and never move it afterwards")
}

/// Resolve two competing recoveries for one prior key to one current binding, by trusted patron
///
/// Spec: design §9.0.2
/// Milestone: after-5.  Kind: positive.  Oracle: behaviour.
///
/// Rule (design §9.0.2): "it resolves to one, by which patron it trusts"
/// Rule (design §9.0.2): "Both successors remain valid nodes network-wide"
///
/// Given: Observer O within the horizon receives two recovery adoptions for prior key k1: successor kX under patron X and successor kY under patron Y, with O's policy set by the test to prefer X.
/// When: O processes both.
/// Then: O's binding for the identity is kX alone; kY is held as a distinct valid node and not as the continuation.
///
/// Interpretation: Which patron an observer trusts is policy; the test fixes it and asserts that exactly one continuation results.
#[test]
#[ignore = "acceptance REC-12: owed at milestone after-5"]
fn rec_12_resolve_two_competing_recoveries_for_one_prior_k() {
    todo!("REC-12: Resolve two competing recoveries for one prior key to one current binding, by trusted patron")
}

/// Carry nothing in a plain rotation
///
/// Spec: wire-format.md §4.1; design §9.0
/// Milestone: after-5.  Kind: negative.  Oracle: behaviour.
///
/// Rule (wire-format.md §4.1): "A plain rotation carries nothing"
/// Rule (design §9.0): "A plain rotation carries nothing"
///
/// Given: Subject S rotates from k1 to k2 without claiming k1's history.
/// When: S's client performs the rotation and the memo for the adoption travels rootward.
/// Then: The adoption carries no field 6, no field naming k1 anywhere, and the memo carries no prior key.
#[test]
#[ignore = "acceptance REC-13: owed at milestone after-5"]
fn rec_13_carry_nothing_in_a_plain_rotation() {
    todo!("REC-13: Carry nothing in a plain rotation")
}

/// Reject a transfer whose statement disagrees with the enclosing adoption
///
/// Spec: wire-format.md §4.1
/// Milestone: after-5.  Kind: negative.  Oracle: model.
///
/// Rule (wire-format.md §4.1): "A verifier MUST check all three against the enclosing adoption"
///
/// Given: Patron P receives a transfer adoption whose TransferStatement names a different node, then one naming a different new patron, then one naming a different former patron than the Transfer map's field 1.
/// When: P evaluates each.
/// Then: P countersigns none of them.
#[test]
#[ignore = "acceptance REC-14: owed at milestone after-5"]
fn rec_14_reject_a_transfer_whose_statement_disagrees_with() {
    todo!("REC-14: Reject a transfer whose statement disagrees with the enclosing adoption")
}
