//! GENERATED by tools/gen_stubs.py from acceptance.json.  Do not edit;
//! change the catalogue and regenerate.  Each stub is one acceptance test
//! still owed for this area.

/// Replicate a client's unreachable marking to the serving node's siblings
///
/// Spec: design §14.1.2; design §3.4
/// Milestone: 4.  Kind: positive.  Oracle: behaviour.
///
/// Rule (design §14.1.2): "This state replicates to siblings, or a sibling answering during failover has no idea of the client's status."
/// Rule (design §3.4): "Siblings replicate each other's topology and trust-bearing transaction history (up to f−1 = 9)."
///
/// Given: Infra nodes S and T are siblings under one patron; light client L is attached to S. No separate replication agreement exists between S and T beyond the patron's adoption transactions.
/// When: L's heartbeat fails at S, S marks L unreachable, and L is then attached to T in failover.
/// Then: T's reachability state for L shows L as unreachable-and-queuing rather than as unknown; T does not answer for L as if it held no record of L.
///
/// Interpretation: No wire frame is specified as the carrier of this replicated state; the test observes T's resulting state only and leaves the carrier to the implementation.
#[test]
#[ignore = "acceptance REP-01: owed at milestone 4"]
fn rep_01_replicate_a_client_s_unreachable_marking_to_the() {
    todo!("REP-01: Replicate a client's unreachable marking to the serving node's siblings")
}

/// Do not replicate queue state to siblings
///
/// Spec: infra-client-requirements.md §2; design §14.1.6; wire-format.md §8.2
/// Milestone: 4.  Kind: negative.  Oracle: behaviour.
///
/// Rule (infra-client-requirements.md §2): "Do not replicate queue state to siblings."
/// Rule (design §14.1.6): "Siblings do not hold queue state."
///
/// Given: Sibling infra nodes S and T; light client L attached to S is marked unreachable at S, and three messages for L are queued at S.
/// When: L attaches to T in failover and collects.
/// Then: T delivers none of the three messages, T's store holds no queued ciphertext for L, and T's AttachAck field 4 does not count S's mailbox.
#[test]
#[ignore = "acceptance REP-02: owed at milestone 4"]
fn rep_02_do_not_replicate_queue_state_to_siblings() {
    todo!("REP-02: Do not replicate queue state to siblings")
}

/// Issue secondhand from replicated state while the patron is dark
///
/// Spec: design §12.6.5.1; wire-format.md §7.1; design §3.4
/// Milestone: 4.  Kind: positive.  Oracle: behaviour.
///
/// Rule (design §12.6.5.1): "A sibling issues a fresh attestation reflecting whatever rotation reached the replicated state."
/// Rule (wire-format.md §7.1): "a consumer must be able to weight a secondhand attestation lower"
///
/// Given: Infra patron P adopted L; sibling T holds P's replicated adoption records for L. P then countersigns a rotation for L that has not yet reached T. P becomes unreachable.
/// When: A currency request for L is sent to T.
/// Then: T returns a CurrencyAttestation whose field 5 is 1 and whose field 2 is the key T's replicated state holds for L; the reply carries no indication that P's state differs, so the lag is visible only as the secondhand role.
///
/// Interpretation: The spec does not name replication lag; the test reads 'whatever rotation reached the replicated state' as: the sibling attests what it holds and neither fetches from the dark patron nor marks its state as behind.
#[test]
#[ignore = "acceptance REP-03: owed at milestone 4"]
fn rep_03_issue_secondhand_from_replicated_state_while_the() {
    todo!("REP-03: Issue secondhand from replicated state while the patron is dark")
}

/// Accept a move within the replication horizon without archive presentation
///
/// Spec: wire-format.md §4.2.1; design §6.2.3; design §3.4
/// Milestone: 4.  Kind: must-accept.  Oracle: behaviour.
///
/// Rule (wire-format.md §4.2.1): "Implementations MUST NOT force re-verification in this case."
/// Rule (wire-format.md §4.2.1): "it already holds the node's history through sibling replication (§4.4), so no archive presentation or re-verification is needed and trust history is preserved"
///
/// Given: Light client L is adopted under infra node P; T is P's sibling and holds L's history through sibling replication.
/// When: L presents T an adoption carrying P's countersignature (a lateral shift) with no archive presentation.
/// Then: T completes the adoption; no archive-fetch request and no presence ceremony are required of L.
///
/// Interpretation: 'No archive presentation or re-verification' is observed as the absence of an archive-fetch request and of a presence-ceremony requirement; the spec names no other observable.
#[test]
#[ignore = "acceptance REP-04: owed at milestone 4"]
fn rep_04_accept_a_move_within_the_replication_horizon_wit() {
    todo!("REP-04: Accept a move within the replication horizon without archive presentation")
}

/// Accept a peering record whose self-asserted ASN is not validated against its address
///
/// Spec: wire-format.md §4.4; design §17.3; design §6.3
/// Milestone: 4.  Kind: must-accept.  Oracle: behaviour.
///
/// Rule (wire-format.md §4.4): "The field is optional and self-asserted besides — no IP-to-ASN validation is specified anywhere."
///
/// Given: A well-formed peering transaction between infra nodes A and B, each NetworkPoint carrying an ASN that does not correspond to its IPv4 address in any public routing data.
/// When: A node in A's horizon receives the record by topology push.
/// Then: The record is accepted and stored, and the ASN values it exposes are exactly those asserted; no validation failure is reported.
#[test]
#[ignore = "acceptance REP-05: owed at milestone 4"]
fn rep_05_accept_a_peering_record_whose_self_asserted_asn() {
    todo!("REP-05: Accept a peering record whose self-asserted ASN is not validated against its address")
}

/// Expose both peers' addresses and ASNs from a stored peering record
///
/// Spec: design §6.3; design §3.4; wire-format.md §4.4
/// Milestone: 4.  Kind: positive.  Oracle: behaviour.
///
/// Rule (design §6.3): "The record carries each endpoint's network point. Address, and where available the ASN, so concentration is observable rather than asserted"
/// Rule (design §3.4): "The peering record carries the ASN for both endpoints"
///
/// Given: Infra nodes A and B, in different subtrees and both carrying ASNs, have peered; observer O is in A's horizon and has stored the peering record.
/// When: O's client reads A's peering relationships.
/// Then: The stored record yields A's and B's keyhashes, both IPv4 addresses and both ASNs as decoded from the record's NetworkPoints, with nothing withheld or derived.
#[test]
#[ignore = "acceptance REP-06: owed at milestone 4"]
fn rep_06_expose_both_peers_addresses_and_asns_from_a_stor() {
    todo!("REP-06: Expose both peers' addresses and ASNs from a stored peering record")
}

/// Leave the trust metric's output unchanged by ASN concentration
///
/// Spec: wire-format.md §4.4; design §3.4
/// Milestone: 4.  Kind: negative.  Oracle: model.
///
/// Rule (wire-format.md §4.4): "Concentration is a visible signal, not a trust input — nothing in the metric consumes it."
///
/// Given: Two otherwise identical fixed graphs, differing only in that in one every peering NetworkPoint carries the same ASN and in the other every ASN differs.
/// When: The reference metric scores the same target from the same observer in each graph.
/// Then: The two scores are identical.
#[test]
#[ignore = "acceptance REP-07: owed at milestone 4"]
fn rep_07_leave_the_trust_metric_s_output_unchanged_by_asn() {
    todo!("REP-07: Leave the trust metric's output unchanged by ASN concentration")
}

/// Generate no rootward memo for a peering record
///
/// Spec: wire-format.md §10.2; design §12.7.5
/// Milestone: 4.  Kind: negative.  Oracle: behaviour.
///
/// Rule (wire-format.md §10.2): "Peering is topology class and is excluded from rootward travel"
///
/// Given: Infra node A, with patron P, grandpatron G and root R above it, peers with infra node B in another subtree.
/// When: A pushes the peering record into its horizon.
/// Then: No TopologyMemo derived from the peering is sent to P, and neither G's nor R's memo table gains an entry naming B's NetworkPoint or ASN.
#[test]
#[ignore = "acceptance REP-08: owed at milestone 4"]
fn rep_08_generate_no_rootward_memo_for_a_peering_record() {
    todo!("REP-08: Generate no rootward memo for a peering record")
}

/// Make an infra node's peerlessness observable from held topology
///
/// Spec: design §12.7.5; design §3.4
/// Milestone: 4.  Kind: positive.  Oracle: behaviour.
///
/// Rule (design §12.7.5): "Peering transactions are public, so this is observable"
/// Rule (design §12.7.5): "trust policies should discount peerless infra nodes, and the reference client should tell an operator plainly what their subordinates are exposed to"
///
/// Given: Observer O's horizon contains infra nodes I and J; J has one peering record stored at O and I has none.
/// When: O's client enumerates cross-tree peers for I and for J.
/// Then: I is reported with zero peers and J with one, both derived from O's own topology store, and I's zero is surfaced to the user rather than omitted.
///
/// Interpretation: 'Should tell an operator plainly' is a reference-client commitment; the test asserts only that the count is derivable and displayed, and leaves any policy discount unspecified.
#[test]
#[ignore = "acceptance REP-09: owed at milestone 4"]
fn rep_09_make_an_infra_node_s_peerlessness_observable_fro() {
    todo!("REP-09: Make an infra node's peerlessness observable from held topology")
}

/// Adopt with zero peers
///
/// Spec: design §12.7.5; design §3.4
/// Milestone: 4.  Kind: must-accept.  Oracle: behaviour.
///
/// Rule (design §12.7.5): "a disconnected node must be able to adopt or be adopted before it has any peers"
/// Rule (design §3.4): "zero peers is a supported configuration"
///
/// Given: Infra node I is a root with no peering records and no patron; node N holds a proof of presence with I.
/// When: I adopts N.
/// Then: The adoption completes and is stored; no step refuses or defers it for want of a peering record.
#[test]
#[ignore = "acceptance REP-10: owed at milestone 4"]
fn rep_10_adopt_with_zero_peers() {
    todo!("REP-10: Adopt with zero peers")
}

/// Take the direct payload path inside the horizon
///
/// Spec: design §12.6.3; design §15.1
/// Milestone: 4.  Kind: positive.  Oracle: behaviour.
///
/// Rule (design §12.6.3): "Direct | Peer is inside the horizon (§15.1), both online, traversal succeeds | Nobody. The peers exchange addresses during setup and connect"
/// Rule (design §12.6.3): ""Is this peer in my h=2 topology store?" is the entire check."
///
/// Given: Light clients L1 and L2 are siblings (distance 1, inside each other's h=2 horizon), both online and attached, with a NAT traversal that succeeds; no user override is set.
/// When: L1 sends payload to L2.
/// Then: L2 receives the payload directly from L1's address; neither serving node carries the payload bytes.
#[test]
#[ignore = "acceptance REP-11: owed at milestone 4"]
fn rep_11_take_the_direct_payload_path_inside_the_horizon() {
    todo!("REP-11: Take the direct payload path inside the horizon")
}

/// Relay, never connect directly, to a peer outside the horizon
///
/// Spec: design §12.6.3; design §15.1
/// Milestone: 4.  Kind: negative.  Oracle: behaviour.
///
/// Rule (design §12.6.3): "Direct connection is limited to the horizon, because a direct path reveals each peer's IP to the other (P17)."
/// Rule (design §12.6.3): "Relayed | Peer is outside the horizon, or traversal fails — symmetric NAT, CGNAT, two mobile peers | Both serving infra nodes, as TURN relays carrying ciphertext"
///
/// Given: Light clients L1 (serving node S1) and L2 (serving node S2) sit in different subtrees, outside each other's h=2 horizon; both online; no user override.
/// When: L1 sends payload to L2.
/// Then: The payload passes through S1 and S2 as ciphertext; L1 opens no connection to L2's address, and L2 learns no address for L1.
#[test]
#[ignore = "acceptance REP-12: owed at milestone 4"]
fn rep_12_relay_never_connect_directly_to_a_peer_outside_t() {
    todo!("REP-12: Relay, never connect directly, to a peer outside the horizon")
}

/// Do not count a peering edge toward the horizon for the direct path
///
/// Spec: design §6.3; design §15.1; design §12.6.3
/// Milestone: 4.  Kind: negative.  Oracle: behaviour.
///
/// Rule (design §6.3): "It confers no scope, and does not extend the horizon."
/// Rule (design §15.1): "Peering edges do not count (§6.3): a peering edge is ungoverned and carries none of the subnet's authority, so it contributes flow without conferring scope."
///
/// Given: Infra nodes A and B, in different subtrees, have peered. Light client L attaches to A and light client M to B; without the peering edge they are outside each other's horizon; both online; no override.
/// When: L sends payload to M.
/// Then: The payload is relayed through A and B; M is absent from L's h=2 topology store and no direct connection is attempted.
#[test]
#[ignore = "acceptance REP-13: owed at milestone 4"]
fn rep_13_do_not_count_a_peering_edge_toward_the_horizon_f() {
    todo!("REP-13: Do not count a peering edge toward the horizon for the direct path")
}

/// Honour a user override of the direct-path default
///
/// Spec: design §12.6.3
/// Milestone: 4.  Kind: positive.  Oracle: behaviour.
///
/// Rule (design §12.6.3): "both defaults must therefore be overridable — relay-with-a-patron's-sibling and direct-with-a-distant-trusted-party are both reasonable user choices (P17)"
///
/// Given: As REP-12 (L1 and L2 outside each other's horizon), except that L1's user has chosen direct connection for L2 and L2's user has chosen it for L1; traversal succeeds.
/// When: L1 sends payload to L2.
/// Then: L2 receives the payload directly from L1's address and neither serving node carries it.
///
/// Interpretation: The spec makes the default overridable and does not say whether one side's choice suffices; the test sets the override on both sides.
#[test]
#[ignore = "acceptance REP-14: owed at milestone 4"]
fn rep_14_honour_a_user_override_of_the_direct_path_defaul() {
    todo!("REP-14: Honour a user override of the direct-path default")
}

/// Push the serving node's siblings, not the patron's, as the replication set
///
/// Spec: design §14.1.2; wire-format.md §8.2; design §3.4
/// Milestone: 4.  Kind: positive.  Oracle: behaviour.
///
/// Rule (design §14.1.2): "siblings of the serving node, not of the patron, where those differ"
///
/// Given: Light client L's patron P is a light client under infra node S; S has infra siblings T1 and T2; P has light-client sibling Q.
/// When: L attaches to S.
/// Then: The AttachAck's SiblingRef list names T1 and T2 with their endpoints, and does not name Q.
#[test]
#[ignore = "acceptance REP-15: owed at milestone 4"]
fn rep_15_push_the_serving_node_s_siblings_not_the_patron() {
    todo!("REP-15: Push the serving node's siblings, not the patron's, as the replication set")
}

/// Replicate topology and trust-bearing history to siblings, and no queue state
///
/// Spec: design §3.4; design §14.1.6
/// Milestone: 4.  Kind: positive.  Oracle: behaviour.
///
/// Rule (design §3.4): "every user's topology and trust-bearing transaction history replicates on their nearest infra node and that node's siblings"
/// Rule (design §3.4): "Payload queues do not replicate"
/// Rule (design §14.1.6): "Siblings do not hold queue state."
///
/// Given: Infra node N with sibling N', an attached client C with an adoption and a presence record in N's store, and a message queued for C at N.
/// When: Replication runs and the test inspects N'.
/// Then: N' holds C's adoption and presence record; N' holds no queued message for C and no record that one is waiting.
#[test]
#[ignore = "acceptance REP-16: owed at milestone 4"]
fn rep_16_replicate_topology_and_trust_bearing_history_to() {
    todo!("REP-16: Replicate topology and trust-bearing history to siblings, and no queue state")
}
