//! GENERATED by tools/gen_stubs.py from acceptance.json.  Do not edit;
//! change the catalogue and regenerate.  Each stub is one acceptance test
//! still owed for this area.

/// Leave the trust metric's output unchanged by ASN concentration
///
/// Spec: wire-format.md §4.4; design §3.4
/// Milestone: 4.  Kind: negative.  Oracle: model.
///
/// Rule (wire-format.md §4.4): "Concentration is a visible signal, not a trust input — nothing in the metric consumes it."
///
/// Given: Two otherwise identical fixed graphs, differing only in that in one every peering NetworkPoint carries the same ASN and in the other every ASN differs.
/// When: The reference metric scores the same target from the same observer in each graph.
/// Then: The two scores are identical.
#[test]
#[ignore = "acceptance REP-07: owed at milestone 4"]
fn rep_07_leave_the_trust_metric_s_output_unchanged_by_asn() {
    todo!("REP-07: Leave the trust metric's output unchanged by ASN concentration")
}
