//! GENERATED by tools/gen_stubs.py from acceptance.json.  Do not edit;
//! change the catalogue and regenerate.  Each stub is one acceptance test
//! still owed for this area.

/// Accept a registration only over the owner's own session
///
/// Spec: wire-format.md §6.2; infra-client-requirements.md §11
/// Milestone: after-5.  Kind: positive.  Oracle: behaviour.
///
/// Rule (wire-format.md §6.2): "The authenticated peer MUST be the owner named in the entry."
/// Rule (infra-client-requirements.md §11): "Accept registrations only from the owner's own session"
///
/// Given: Owner O has signed a CatalogEntry naming O; O and another client P both hold sessions with host H.
/// When: O submits the entry over O's session; P submits the same bytes over P's session.
/// Then: O's submission is answered with code 0 and the entry is served; P's is answered with code 1 and the served entry is unchanged.
#[test]
#[ignore = "acceptance RSC-01: owed at milestone after-5"]
fn rsc_01_accept_a_registration_only_over_the_owner_s_own() {
    todo!("RSC-01: Accept a registration only over the owner's own session")
}

/// Refuse a registration for a keyhash already served under a different owner
///
/// Spec: wire-format.md §6.7; infra-client-requirements.md §11
/// Milestone: after-5.  Kind: negative.  Oracle: behaviour.
///
/// Rule (wire-format.md §6.7): "A host refuses a registration for a keyhash it already serves under a different owner"
/// Rule (infra-client-requirements.md §11): "Refuse a registration for a keyhash you already serve under a different owner."
///
/// Given: Host H serves resource keyhash R registered by owner O1.
/// When: Owner O2 submits a valid entry naming R over O2's session.
/// Then: The reply carries code 1 and H still serves O1's entry for R.
#[test]
#[ignore = "acceptance RSC-02: owed at milestone after-5"]
fn rsc_02_refuse_a_registration_for_a_keyhash_already_serv() {
    todo!("RSC-02: Refuse a registration for a keyhash already served under a different owner")
}

/// Replace on re-registration, retain nothing superseded, archive nothing
///
/// Spec: infra-client-requirements.md §11; wire-format.md §6.5
/// Milestone: after-5.  Kind: positive.  Oracle: behaviour.
///
/// Rule (infra-client-requirements.md §11): "Re-registering by the same owner replaces the entry, and the old one is gone."
/// Rule (infra-client-requirements.md §11): "Do not retain superseded registrations"
/// Rule (wire-format.md §6.5): "A registration is not archived"
///
/// Given: Owner O has an entry E1 for R served by H.
/// When: O submits a new entry E2 for R, and the test inspects H's storage and archive.
/// Then: Queries return E2 and never E1, E1 is absent from H's storage, and H's archive did not advance.
#[test]
#[ignore = "acceptance RSC-03: owed at milestone after-5"]
fn rsc_03_replace_on_re_registration_retain_nothing_supers() {
    todo!("RSC-03: Replace on re-registration, retain nothing superseded, archive nothing")
}

/// Default a first registration's discover scope to self
///
/// Spec: wire-format.md §6.2
/// Milestone: after-5.  Kind: positive.  Oracle: behaviour.
///
/// Rule (wire-format.md §6.2): "with no existing rule, the default is ; `self`, the least-disclosing scope"
///
/// Given: Owner O registers R with H for the first time with field 2 absent.
/// When: O queries H, and another horizon member M queries H.
/// Then: O's reply carries R's entry; M's does not.
#[test]
#[ignore = "acceptance RSC-04: owed at milestone after-5"]
fn rsc_04_default_a_first_registration_s_discover_scope_to() {
    todo!("RSC-04: Default a first registration's discover scope to self")
}

/// Withdraw by re-registering with scope self, and propagate nothing
///
/// Spec: wire-format.md §6.5; infra-client-requirements.md §11
/// Milestone: after-5.  Kind: positive.  Oracle: behaviour.
///
/// Rule (wire-format.md §6.5): "It re-registers the resource with a requested `discover_scope` of self, which no asker but the owner satisfies"
/// Rule (infra-client-requirements.md §11): "Withdrawal is not a propagated message."
///
/// Given: Owner O's entry for R is visible to horizon member M at host H.
/// When: O re-registers R requesting scope self, then M queries.
/// Then: M's reply omits R, and no TopologyPush or other frame carrying the entry leaves H.
#[test]
#[ignore = "acceptance RSC-05: owed at milestone after-5"]
fn rsc_05_withdraw_by_re_registering_with_scope_self_and_p() {
    todo!("RSC-05: Withdraw by re-registering with scope self, and propagate nothing")
}

/// Refuse an asker outside your horizon by closing the stream
///
/// Spec: wire-format.md §6.4
/// Milestone: after-5.  Kind: negative.  Oracle: behaviour.
///
/// Rule (wire-format.md §6.4): "An asker outside the answering node's horizon is refused before the application reply."
/// Rule (wire-format.md §6.4): "Close the stream; do not return an empty `CatalogReply`."
///
/// Given: A node X outside H's horizon holds a session with H.
/// When: X sends a CatalogQuery.
/// Then: The stream is closed and no CatalogReply, empty or otherwise, is sent.
#[test]
#[ignore = "acceptance RSC-06: owed at milestone after-5"]
fn rsc_06_refuse_an_asker_outside_your_horizon_by_closing() {
    todo!("RSC-06: Refuse an asker outside your horizon by closing the stream")
}

/// Order entries by resource then owner keyhash, return 111, and name the first withheld type
///
/// Spec: wire-format.md §6.4
/// Milestone: after-5.  Kind: positive.  Oracle: behaviour.
///
/// Rule (wire-format.md §6.4): "orders qualifying entries by resource keyhash, then by owner keyhash, and returns the first 111"
/// Rule (wire-format.md §6.4): "the continuation names the type of the first entry it withheld"
///
/// Given: H holds 113 entries visible to asker M.
/// When: M sends an unfiltered CatalogQuery.
/// Then: The reply's field 2 holds the first 111 entries in ascending resource-then-owner keyhash order and field 3 names the service type of the 112th.
#[test]
#[ignore = "acceptance RSC-07: owed at milestone after-5"]
fn rsc_07_order_entries_by_resource_then_owner_keyhash_ret() {
    todo!("RSC-07: Order entries by resource then owner keyhash, return 111, and name the first withheld type")
}

/// Return the owner's signature unchanged and add none
///
/// Spec: infra-client-requirements.md §11; wire-format.md §6.5
/// Milestone: after-5.  Kind: positive.  Oracle: behaviour.
///
/// Rule (infra-client-requirements.md §11): "Return the owner's signature unchanged, and add none of your own."
/// Rule (wire-format.md §6.5): "An entry is signed once, at registration, and that signature is reused for every answer."
///
/// Given: Owner O registered entry E with H; the test recorded E's bytes.
/// When: Two different askers query H.
/// Then: Each reply carries E byte-for-byte, with O's signature and no signature by H.
#[test]
#[ignore = "acceptance RSC-08: owed at milestone after-5"]
fn rsc_08_return_the_owner_s_signature_unchanged_and_add_n() {
    todo!("RSC-08: Return the owner's signature unchanged and add none")
}

/// Store an entry whose scope you cannot compute, and grant nothing from it
///
/// Spec: wire-format.md §6.8
/// Milestone: after-5.  Kind: must-accept.  Oracle: behaviour.
///
/// Rule (wire-format.md §6.8): "A scope the evaluator cannot compute is structurally valid and ineffective."
/// Rule (wire-format.md §6.8): "A decoder MUST NOT reject it."
///
/// Given: An entry whose connect_scope names a position H cannot resolve, submitted by its owner over the owner's session.
/// When: H processes it and a member requests the resource.
/// Then: The registration is answered code 0 and the entry is served; the scope grants nothing, so the request is decided by the role row alone. An implementation that rejects the entry fails.
#[test]
#[ignore = "acceptance RSC-09: owed at milestone after-5"]
fn rsc_09_store_an_entry_whose_scope_you_cannot_compute_an() {
    todo!("RSC-09: Store an entry whose scope you cannot compute, and grant nothing from it")
}

/// Retain and surface an unknown data_practice value
///
/// Spec: wire-format.md §6.1
/// Milestone: after-5.  Kind: must-accept.  Oracle: behaviour.
///
/// Rule (wire-format.md §6.1): "Unknown values are retained and surfaced, not rejected"
///
/// Given: An entry whose field 9 carries a value outside the four defined, correctly signed, and a client with a display hook.
/// When: The owner registers it and a member's client fetches it.
/// Then: Registration is accepted, the reply carries field 9 unchanged, and the client's hook records that a declaration exists and is unrecognised. An implementation that rejects the entry fails.
#[test]
#[ignore = "acceptance RSC-10: owed at milestone after-5"]
fn rsc_10_retain_and_surface_an_unknown_data_practice_valu() {
    todo!("RSC-10: Retain and surface an unknown data_practice value")
}

/// Never process a resource request from early data, and carry one request per stream
///
/// Spec: wire-format.md §11; resource-requirements.md §3
/// Milestone: after-5.  Kind: negative.  Oracle: behaviour.
///
/// Rule (wire-format.md §11): "a `ResourceRequest` stream is never processed in early data, whatever the method inside"
/// Rule (wire-format.md §11): "one request per stream"
/// Rule (resource-requirements.md §3): "A `ResourceRequest` on a new bidirectional stream"
///
/// Given: Client C resumes a session with H using 0-RTT and holds connect on resource R.
/// When: C sends a ResourceRequest for R on a new bidirectional stream in early data, and later two requests on one stream.
/// Then: No ResourceResponse and no backend traffic for the early-data request are observed before the handshake completes; on the shared stream only the first request is answered.
///
/// Interpretation: What happens to a second request on one stream is not stated; the test asserts only that it is not answered as a second exchange.
#[test]
#[ignore = "acceptance RSC-11: owed at milestone after-5"]
fn rsc_11_never_process_a_resource_request_from_early_data() {
    todo!("RSC-11: Never process a resource request from early data, and carry one request per stream")
}

/// Evaluate a resource request in the normative order and answer with the one code that step yields
///
/// Spec: wire-format.md §11; infra-client-requirements.md §10.1
/// Milestone: after-5.  Kind: positive.  Oracle: behaviour.
///
/// Rule (wire-format.md §11): "Evaluation order is normative"
/// Rule (wire-format.md §11): "Availability is checked last, so a role-holder learns the service is down and a non-role-holder never does."
/// Rule (infra-client-requirements.md §10.1): "Evaluate in the order `wire-format.md` §11 gives"
///
/// Given: Host H with resource R owned by O and a stopped package, and six requesters: a stranger; a member lacking a SubtreeAck; a member with an ack and no connect; a member with connect sending malformed HTTP; a member with connect sending a well-formed request; the same with the package running.
/// When: Each sends a ResourceRequest for R.
/// Then: The six responses carry codes 1, 4, 5, 3, 2 and 0 respectively, and only the last reaches the backend.
#[test]
#[ignore = "acceptance RSC-12: owed at milestone after-5"]
fn rsc_12_evaluate_a_resource_request_in_the_normative_ord() {
    todo!("RSC-12: Evaluate a resource request in the normative order and answer with the one code that step yields")
}

/// Answer a non-member with refused for everything, existing keyhash or not
///
/// Spec: infra-client-requirements.md §10.1; wire-format.md §11
/// Milestone: after-5.  Kind: negative.  Oracle: behaviour.
///
/// Rule (infra-client-requirements.md §10.1): "A non-member gets `refused` for everything"
/// Rule (wire-format.md §11): "a keyhash naming nothing returns the same code"
///
/// Given: A stranger S with a session to H, which serves R and nothing named Q.
/// When: S requests R, then Q.
/// Then: Both responses carry code 1 and nothing else, and no backend traffic follows.
#[test]
#[ignore = "acceptance RSC-13: owed at milestone after-5"]
fn rsc_13_answer_a_non_member_with_refused_for_everything() {
    todo!("RSC-13: Answer a non-member with refused for everything, existing keyhash or not")
}

/// Decide a request from the materialised row, and refuse to materialise a row wider than 64 roles
///
/// Spec: infra-client-requirements.md §10.2
/// Milestone: after-5.  Kind: positive.  Oracle: behaviour.
///
/// Rule (infra-client-requirements.md §10.2): "Authorisation at request time is a lookup, never a predicate evaluation"
/// Rule (infra-client-requirements.md §10.2): "refuse to materialise one wider"
///
/// Given: A predicate whose evaluation would now exclude member M, unevaluated since M's row granted connect; and an operator configuring a row of 65 roles.
/// When: M requests the resource; the operator saves the configuration.
/// Then: M's request is delivered on the strength of the row; the 65-role row is refused at configuration and no request ever yields a code for it.
#[test]
#[ignore = "acceptance RSC-14: owed at milestone after-5"]
fn rsc_14_decide_a_request_from_the_materialised_row_and_r() {
    todo!("RSC-14: Decide a request from the materialised row, and refuse to materialise a row wider than 64 roles")
}

/// Strip caller rhtn headers, insert your own, and mint one session identifier per resource
///
/// Spec: resource-requirements.md §3.1; resource-requirements.md §3; infra-client-requirements.md §10.2
/// Milestone: after-5.  Kind: positive.  Oracle: behaviour.
///
/// Rule (resource-requirements.md §3.1): "the node strips inbound `rhtn-*` headers"
/// Rule (resource-requirements.md §3): "It is also per resource."
/// Rule (resource-requirements.md §3): "`rhtn-roles` may be empty, and that is not an error."
/// Rule (infra-client-requirements.md §10.2): "Mint the session identifier per resource, not per connection."
///
/// Given: Member M with connect and no application roles on hosted resources R1 and R2, sending requests that carry a forged rhtn-roles header.
/// When: M requests R1 and R2 over one session.
/// Then: Each backend receives rhtn-principal, rhtn-audience naming itself, rhtn-session and an empty rhtn-roles, with the forged value absent; the two session identifiers differ.
#[test]
#[ignore = "acceptance RSC-15: owed at milestone after-5"]
fn rsc_15_strip_caller_rhtn_headers_insert_your_own_and_mi() {
    todo!("RSC-15: Strip caller rhtn headers, insert your own, and mint one session identifier per resource")
}

/// Parse and re-serialise, reject the ambiguous, and emit exactly one message
///
/// Spec: wire-format.md §11.2
/// Milestone: after-5.  Kind: negative.  Oracle: behaviour.
///
/// Rule (wire-format.md §11.2): "Emit exactly one message per `ResourceRequest`."
/// Rule (wire-format.md §11.2): "Reject rather than normalise anything ambiguous"
/// Rule (wire-format.md §11.2): "Reject anything asking for an exchange other than one request and one response"
///
/// Given: A member with connect sends, in turn, a request with conflicting Content-Length and Transfer-Encoding headers, one whose body encodes a second request line, and a CONNECT request.
/// When: H processes each.
/// Then: Each is answered code 3 and nothing reaches the backend.
#[test]
#[ignore = "acceptance RSC-16: owed at milestone after-5"]
fn rsc_16_parse_and_re_serialise_reject_the_ambiguous_and() {
    todo!("RSC-16: Parse and re-serialise, reject the ambiguous, and emit exactly one message")
}

/// Never retry a failed handoff on your own
///
/// Spec: wire-format.md §11
/// Milestone: after-5.  Kind: negative.  Oracle: behaviour.
///
/// Rule (wire-format.md §11): "the gateway NEVER retries on its own"
///
/// Given: The backend for R accepts a connection and fails mid-request.
/// When: A member with connect sends a request.
/// Then: Exactly one attempt reaches the backend and the response carries code 2.
#[test]
#[ignore = "acceptance RSC-17: owed at milestone after-5"]
fn rsc_17_never_retry_a_failed_handoff_on_your_own() {
    todo!("RSC-17: Never retry a failed handoff on your own")
}

/// End the resource-facing session on a role change, and leave the transport session alone
///
/// Spec: infra-client-requirements.md §10.5; infra-client-requirements.md §10.1
/// Milestone: after-5.  Kind: positive.  Oracle: behaviour.
///
/// Rule (infra-client-requirements.md §10.5): "the session dropped is the resource-facing one"
/// Rule (infra-client-requirements.md §10.5): "The transport session is untouched"
/// Rule (infra-client-requirements.md §10.1): "An in-flight request completes under the state it started with."
///
/// Given: Member M holds connect on R with a long-running request in flight.
/// When: The operator revokes M's grant during the request, then M sends another.
/// Then: The in-flight request completes and its response is delivered; the next request is answered code 5; M's QUIC session to H stays open throughout.
#[test]
#[ignore = "acceptance RSC-18: owed at milestone after-5"]
fn rsc_18_end_the_resource_facing_session_on_a_role_change() {
    todo!("RSC-18: End the resource-facing session on a role change, and leave the transport session alone")
}

/// Expose no network primitive to a hosted package
///
/// Spec: infra-client-requirements.md §9.2
/// Milestone: after-5.  Kind: negative.  Oracle: behaviour.
///
/// Rule (infra-client-requirements.md §9.2): "the hooks do not exist"
/// Rule (infra-client-requirements.md §9.2): "no topology, no liveness state, no queue contents, no prekey requests, no role-evaluation inputs"
///
/// Given: A package whose manifest imports a binding for topology, queue contents, prekeys or role inputs, on a host using the expected component-model sandbox.
/// When: The host instantiates it.
/// Then: Instantiation fails for want of the import, and the host's export list contains no such binding.
///
/// Interpretation: The sandbox mechanism is an implementation choice the requirement calls expected rather than mandated; the test assumes a capability-based component host.
#[test]
#[ignore = "acceptance RSC-19: owed at milestone after-5"]
fn rsc_19_expose_no_network_primitive_to_a_hosted_package() {
    todo!("RSC-19: Expose no network primitive to a hosted package")
}

/// Acknowledge a subtree automatically under policy, without prompting, and treat it as lapsed when the relationship ends
///
/// Spec: infra-client-requirements.md §10.1
/// Milestone: after-5.  Kind: positive.  Oracle: behaviour.
///
/// Rule (infra-client-requirements.md §10.1): "Issue it automatically, under a policy the operator set beforehand."
/// Rule (infra-client-requirements.md §10.1): "Do not prompt per adoption."
/// Rule (infra-client-requirements.md §10.1): "Treat it as lapsed when the relationship it describes ends"
///
/// Given: Host H with policy set to acknowledge every position, a prompt hook, and subordinate S who adopts a grand-subordinate G.
/// When: G's adoption reaches H; later S departs.
/// Then: A SubtreeAck for G is issued with no prompt recorded; after S's departure G's request for H's resource is answered code 4.
#[test]
#[ignore = "acceptance RSC-20: owed at milestone after-5"]
fn rsc_20_acknowledge_a_subtree_automatically_under_policy() {
    todo!("RSC-20: Acknowledge a subtree automatically under policy, without prompting, and treat it as lapsed when the relationship ends")
}

/// Accept a brokered registration with no local backend
///
/// Spec: wire-format.md §6.2
/// Milestone: after-5.  Kind: must-accept.  Oracle: behaviour.
///
/// Rule (wire-format.md §6.2): "A host refusing every entry that lacks a locally installed package refuses valid brokered registrations."
///
/// Given: Owner O submits an entry whose field 5 names an external endpoint and for which H hosts no package.
/// When: H processes it.
/// Then: The reply carries code 0. An implementation requiring a local package fails.
#[test]
#[ignore = "acceptance RSC-21: owed at milestone after-5"]
fn rsc_21_accept_a_brokered_registration_with_no_local_bac() {
    todo!("RSC-21: Accept a brokered registration with no local backend")
}

/// Store an abuse report only from the resource it names, and carry it nowhere
///
/// Spec: wire-format.md §6.3
/// Milestone: after-5.  Kind: positive.  Oracle: behaviour.
///
/// Rule (wire-format.md §6.3): "The signing key's ; keyhash MUST equal field 1"
/// Rule (wire-format.md §6.3): "An abuse report has no carriage, and needs none."
///
/// Given: Resource R hosted at owner O's node produces a report signed by R, and a forged one signed by another key naming R.
/// When: O's node processes both and the test watches its sessions.
/// Then: The first is stored for O; the second is rejected; no report bytes leave the node.
#[test]
#[ignore = "acceptance RSC-22: owed at milestone after-5"]
fn rsc_22_store_an_abuse_report_only_from_the_resource_it() {
    todo!("RSC-22: Store an abuse report only from the resource it names, and carry it nowhere")
}

/// Treat a repeated continuation as truncation, not another page
///
/// Spec: light-client-requirements.md §8; wire-format.md §6.4
/// Milestone: after-5.  Kind: positive.  Oracle: behaviour.
///
/// Rule (light-client-requirements.md §8): "A repeated continuation means truncation, not another page."
/// Rule (wire-format.md §6.4): "MUST NOT loop"
///
/// Given: A client sweeping H, which returns a full page with a continuation naming a type the client has already filtered on.
/// When: The client follows the sweep.
/// Then: The client asks H for that type at most once more, marks H's portion of its view truncated, and stops.
#[test]
#[ignore = "acceptance RSC-23: owed at milestone after-5"]
fn rsc_23_treat_a_repeated_continuation_as_truncation_not() {
    todo!("RSC-23: Treat a repeated continuation as truncation, not another page")
}

/// Route to a brokered service only when it matches the signed entry
///
/// Spec: light-client-requirements.md §8
/// Milestone: after-5.  Kind: positive.  Oracle: behaviour.
///
/// Rule (light-client-requirements.md §8): "Confirm a brokered service matches the signed `CatalogEntry`"
/// Rule (light-client-requirements.md §8): "Do not present resources the user cannot use."
///
/// Given: A client holding a signed entry for brokered resource R whose field 5 names endpoint X, and a broker presenting endpoint Y.
/// When: The user opens R.
/// Then: The client routes no traffic to Y, and shows the owner named in the entry; a resource the catalog page filtered out is not shown.
#[test]
#[ignore = "acceptance RSC-24: owed at milestone after-5"]
fn rsc_24_route_to_a_brokered_service_only_when_it_matches() {
    todo!("RSC-24: Route to a brokered service only when it matches the signed entry")
}
