//! GENERATED by tools/gen_stubs.py from acceptance.json.  Do not edit;
//! change the catalogue and regenerate.  Each stub is one acceptance test
//! still owed for this area.

/// Use a gossiped anchor entry as a starting point without authenticating the anchor
///
/// Spec: wire-format.md §7.2; design §12.2; design §12.3
/// Milestone: 4.  Kind: positive.  Oracle: behaviour.
///
/// Rule (wire-format.md §7.2): "Full keys are not fetched during resolution — they arrive from attaching, from a transaction naming the node, or not at all"
/// Rule (wire-format.md §7.2): "an anchor that refers you onward is never pinned at all"
///
/// Given: The node's anchor table holds an AnchorEntry for anchor A received by gossip: A's keyhash, one to eight NetworkPoints, subtree size, seqno and A's self-signature. The node holds no KeyMaterial for A and has never contacted A.
/// When: The node resolves a SignedLocator whose anchor is A and whose path leads to a subject beneath A.
/// Then: A ResolveRequest is sent to an endpoint taken from the entry; the ResolveReply's Referral is followed to the next hop; at no point is A's key material fetched or a pin for A created, and the resolution still completes at the serving node.
#[test]
#[ignore = "acceptance RES-01: owed at milestone 4"]
fn res_01_use_a_gossiped_anchor_entry_as_a_starting_point() {
    todo!("RES-01: Use a gossiped anchor entry as a starting point without authenticating the anchor")
}

/// Retain anchor entries only at or above the node's own caching threshold
///
/// Spec: design §12.7.3; design §12.2; wire-format.md §7.2
/// Milestone: 4.  Kind: positive.  Oracle: behaviour.
///
/// Rule (design §12.7.3): "each node sets its own threshold for which roots it caches. For example, ignoring roots with fewer than n subordinates"
/// Rule (wire-format.md §7.2): "Which anchors a node caches is per-node policy, never a protocol constant."
///
/// Given: The anchor caching threshold n is a parameter of the test, since design §21.1 leaves it unset; the node under test is configured with a chosen n. Two well-formed AnchorEntry objects arrive by gossip for roots R1 and R2, with subtree sizes n−1 and n.
/// When: The node ingests both entries.
/// Then: R2's entry is present in the anchor table and R1's is not; a locator anchored at R1 is reported unresolvable by this node while one anchored at R2 proceeds to a ResolveRequest.
///
/// Interpretation: The quantity compared against n is AnchorEntry field 3 (subtree size), which the test reads as design §12.7.3's count of subordinates.
#[test]
#[ignore = "acceptance RES-02: owed at milestone 4"]
fn res_02_retain_anchor_entries_only_at_or_above_the_node() {
    todo!("RES-02: Retain anchor entries only at or above the node's own caching threshold")
}

/// Send no request for a locator whose anchor is absent from the table
///
/// Spec: wire-format.md §7.7.3; design §12.2
/// Milestone: 4.  Kind: negative.  Oracle: behaviour.
///
/// Rule (wire-format.md §7.7.3): "A locator whose anchor is absent from the local table is not resolvable by this node. That is a caller-side condition, not a wire failure: no request is sent, because there is nowhere to send it."
///
/// Given: The node's anchor table holds no entry for anchor A, and no other source (an introduction, a cached entry, a peer's referral) has supplied an address for A.
/// When: The node is asked to resolve a valid SignedLocator anchored at A.
/// Then: No ResolveRequest is emitted on any connection; the resolution result is reported as a caller-side condition distinct from every wire failure code.
#[test]
#[ignore = "acceptance RES-03: owed at milestone 4"]
fn res_03_send_no_request_for_a_locator_whose_anchor_is_ab() {
    todo!("RES-03: Send no request for a locator whose anchor is absent from the table")
}

/// Accept a same-series counter jump as a valid supersession
///
/// Spec: wire-format.md §2.3; design §12.1
/// Milestone: 4.  Kind: must-accept.  Oracle: fixture.
///
/// Rule (wire-format.md §2.3): "Within one series a new counter must be strictly greater than the last one the verifier holds — not exactly previous+1, since a verifier may legitimately have missed intervening transactions"
///
/// Given: The holder has installed the primitives.md SignedLocator for alice with seqno [5, 42] as her current locator.
/// When: The primitives.md 'Same-series counter jump' SignedLocator for alice, seqno [5, 100], is presented.
/// Then: The [5, 100] locator is accepted and becomes the held locator for alice; the [5, 42] locator is no longer reported as current.
#[test]
#[ignore = "acceptance RES-04: owed at milestone 4"]
fn res_04_accept_a_same_series_counter_jump_as_a_valid_sup() {
    todo!("RES-04: Accept a same-series counter jump as a valid supersession")
}

/// Retain neither locator when equal seqnos carry different contents
///
/// Spec: wire-format.md §7.7.3; wire-format.md §2.3
/// Milestone: 4.  Kind: negative.  Oracle: behaviour.
///
/// Rule (wire-format.md §7.7.3): "malformed names the pair, the holder retains neither as current and re-resolves — kept-because-it-arrived-first is not a freshness rule"
///
/// Given: The holder has installed alice's [5, 100] counter-jump SignedLocator from primitives.md. Its conflict partner (V12), same subject, same [5, 100], different path, is validly signed.
/// When: The conflict partner is presented and the holder is then asked to reach alice.
/// Then: Neither locator is reported as alice's current locator, and the attempt to reach her produces a re-resolution rather than a dial to either path.
///
/// Interpretation: 'Re-resolves' is observed as the holder declining to dial either path and signalling that a fresh locator is required; the spec places the fresh locator's source in design §12.3 Case 3 or §12.4, outside this test.
#[test]
#[ignore = "acceptance RES-05: owed at milestone 4"]
fn res_05_retain_neither_locator_when_equal_seqnos_carry_d() {
    todo!("RES-05: Retain neither locator when equal seqnos carry different contents")
}

/// Do not rank two locators for one subject that lie in different series
///
/// Spec: wire-format.md §2.3; wire-format.md §7.7.3
/// Milestone: 4.  Kind: negative.  Oracle: behaviour.
///
/// Rule (wire-format.md §2.3): "Across series there is no order, and a reader MUST NOT invent one."
/// Rule (wire-format.md §7.7.3): "Two locators in different series do not rank, and a reader holding both has learned nothing about which is current — it either holds a §4.6 chain that says, or it re-resolves"
///
/// Given: The holder has alice's [5, 100] SignedLocator installed and holds no series-reissue chain for her.
/// When: A validly signed SignedLocator for alice with seqno [9, 3] and a different path is presented.
/// Then: The [9, 3] locator is not installed as fresher and the [5, 100] locator is not marked stale; the holder reports that it cannot determine which is current.
///
/// Interpretation: The spec says the reader 'has learned nothing'; the test reads this as the held locator left unchanged, the newcomer not installed, and the reader signalling indeterminacy rather than choosing.
#[test]
#[ignore = "acceptance RES-06: owed at milestone 4"]
fn res_06_do_not_rank_two_locators_for_one_subject_that_li() {
    todo!("RES-06: Do not rank two locators for one subject that lie in different series")
}

/// Route a light client's resolution through its serving node
///
/// Spec: wire-format.md §7.7.1; design §12.3
/// Milestone: 4.  Kind: positive.  Oracle: behaviour.
///
/// Rule (wire-format.md §7.7.1): "A light client sends ResolveRequest to its serving infra node, not to the anchor."
/// Rule (wire-format.md §7.7.1): "The serving node resolves on the client's behalf and returns the result."
///
/// Given: Light client L is attached to serving node S. L holds a SignedLocator for subject X anchored at A; S holds an anchor entry for A and L holds none.
/// When: L resolves X.
/// Then: L's only ResolveRequest is sent on its session with S; S sends a ResolveRequest to an endpoint of A and follows any referrals; L receives X's serving node and residual path from S and opens no connection to A.
#[test]
#[ignore = "acceptance RES-07: owed at milestone 4"]
fn res_07_route_a_light_client_s_resolution_through_its_se() {
    todo!("RES-07: Route a light client's resolution through its serving node")
}

/// Answer authoritatively with the residual suffix for a client attached past a light-client patron
///
/// Spec: wire-format.md §7.7.2; infra-client-requirements.md §4.1; design §12.6.1
/// Milestone: 4.  Kind: positive.  Oracle: behaviour.
///
/// Rule (wire-format.md §7.7.2): "The remaining path suffix is returned rather than traversed. The serving node uses it to identify which of its attached clients is meant."
/// Rule (infra-client-requirements.md §4.1): "You resolve their paths yourself; nothing routes through an intermediate light-client patron."
///
/// Given: Infra node S has light-client subordinate P, and P has adopted light client L, so L attaches to S at depth two beneath it.
/// When: S receives a ResolveRequest naming L, with the anchor and full anchor-relative path to L.
/// Then: The reply has field 2 = 0 and a ServingInfra whose field 1 is S's keyhash and whose path field is the non-empty suffix identifying L beneath S; no request is forwarded to P.
#[test]
#[ignore = "acceptance RES-08: owed at milestone 4"]
fn res_08_answer_authoritatively_with_the_residual_suffix() {
    todo!("RES-08: Answer authoritatively with the residual suffix for a client attached past a light-client patron")
}

/// Resolve a root's self-anchored locator to an empty residual path
///
/// Spec: design §12.6.1; design §12.1; wire-format.md §7.7.3
/// Milestone: 4.  Kind: must-accept.  Oracle: fixture.
///
/// Rule (design §12.6.1): "empty means the addressed party is the node itself, non-empty means the last hop forwards to an attached client"
/// Rule (design §12.1): "a root names itself, with an empty path"
///
/// Given: Root R is an infra node; the requester holds an anchor entry for R and R's self-anchored SignedLocator from primitives.md (anchor = R, empty path).
/// When: The requester sends R a ResolveRequest with subject R, anchor R and the empty path.
/// Then: The reply has field 2 = 0 and a ServingInfra naming R with an empty path field, and the requester treats R itself as the addressed party.
#[test]
#[ignore = "acceptance RES-09: owed at milestone 4"]
fn res_09_resolve_a_root_s_self_anchored_locator_to_an_emp() {
    todo!("RES-09: Resolve a root's self-anchored locator to an empty residual path")
}

/// Refer from an infra child's endpoint record before ever contacting the child
///
/// Spec: infra-client-requirements.md §4.4; infra-client-requirements.md §4.2; wire-format.md §7.6
/// Milestone: 4.  Kind: positive.  Oracle: behaviour.
///
/// Rule (infra-client-requirements.md §4.4): "Unverified does not mean unusable: refer from it."
/// Rule (infra-client-requirements.md §4.2): "Refer when it does not: the next hop's keyhash, its endpoints, and its KeyMaterial where the requester may lack it."
///
/// Given: Infra node S adopted infra node C. S has received C's EndpointRecord by topology push, holds no KeyMaterial for C and has never dialled C.
/// When: S receives a ResolveRequest whose path leads into C's subtree.
/// Then: The reply has field 2 = 2 and a Referral whose field 1 is C's keyhash, whose field 2 is the endpoint list from C's record, and whose field 3 is at least 1; S opens no connection to C before replying.
#[test]
#[ignore = "acceptance RES-10: owed at milestone 4"]
fn res_10_refer_from_an_infra_child_s_endpoint_record_befo() {
    todo!("RES-10: Refer from an infra child's endpoint record before ever contacting the child")
}

/// Reject a referral that advances nothing
///
/// Spec: wire-format.md §7.7.3
/// Milestone: 4.  Kind: negative.  Oracle: behaviour.
///
/// Rule (wire-format.md §7.7.3): "advances MUST be ≥ 1, and a referral advancing past the path's end is malformed"
///
/// Given: A requester is mid-resolution, having sent a ResolveRequest with a three-index path to node N.
/// When: N replies with field 2 = 2 and a Referral whose field 3 is 0.
/// Then: The named next hop is not dialled and the reply is rejected as malformed.
///
/// Interpretation: What the requester does after rejecting a malformed reply (retry at another endpoint of N, or report failure) is not stated; the test asserts only that the loop is not followed.
#[test]
#[ignore = "acceptance RES-11: owed at milestone 4"]
fn res_11_reject_a_referral_that_advances_nothing() {
    todo!("RES-11: Reject a referral that advances nothing")
}

/// Fail the handshake, not the identity, when an unsigned reply gives a wrong address
///
/// Spec: wire-format.md §9.1; wire-format.md §7.7.3; design §12.6.1
/// Milestone: 4.  Kind: negative.  Oracle: behaviour.
///
/// Rule (wire-format.md §7.7.3): "The reply is not signed."
/// Rule (wire-format.md §9.1): "The dialling party checks that key is the classical member of the KeyMaterial it has pinned for the keyhash it intended to reach."
/// Rule (wire-format.md §7.7.3): "A wrong or hostile reply causes a failed connection, not a false identity."
///
/// Given: The requester intends to reach subject X, whose serving node is S, and holds S's KeyMaterial pinned. A ResolveReply names S's keyhash in ServingInfra but lists the endpoint of a different node Y, which presents Y's own key.
/// When: The requester dials the listed endpoint.
/// Then: The handshake fails because the presented key is not the classical member of S's pinned KeyMaterial; no session, Attach or payload follows, and the result is reported as a failed contact with S, never as having reached S.
#[test]
#[ignore = "acceptance RES-12: owed at milestone 4"]
fn res_12_fail_the_handshake_not_the_identity_when_an_unsi() {
    todo!("RES-12: Fail the handshake, not the identity, when an unsigned reply gives a wrong address")
}

/// Try the remaining serving endpoints when the first fails
///
/// Spec: wire-format.md §7.7.3
/// Milestone: 4.  Kind: liveness.  Oracle: behaviour.
///
/// Rule (wire-format.md §7.7.3): "an implementation MUST treat the list as ; alternatives and try others on failure, or a ; single unreachable first entry becomes a ; permanent outage for that peer"
///
/// Given: A ServingInfra reply lists two NetworkPoints for serving node S in preference order; the first does not respond, the second is live and presents S's key.
/// When: The requester contacts S.
/// Then: After the first endpoint fails the second is dialled, the handshake completes against S's pinned key, and the contact is reported as successful.
#[test]
#[ignore = "acceptance RES-13: owed at milestone 4"]
fn res_13_try_the_remaining_serving_endpoints_when_the_fir() {
    todo!("RES-13: Try the remaining serving endpoints when the first fails")
}

/// Remove a departed infra child and fail, never redirect, for its old path
///
/// Spec: infra-client-requirements.md §4.3; infra-client-requirements.md §4.2; wire-format.md §7.7.3
/// Milestone: 4.  Kind: negative.  Oracle: behaviour.
///
/// Rule (infra-client-requirements.md §4.3): "Remove a child on departure or disavowal. A stale entry refers requesters to a node that will not answer for that path."
/// Rule (infra-client-requirements.md §4.2): "Keep nothing for a node that has left your subtree, and do not redirect on its behalf."
///
/// Given: Infra node S holds a child-table entry for infra child C at index i. C then departs (a departure transaction S stores) and is adopted by an unrelated patron, whose position S also learns from topology.
/// When: S receives a ResolveRequest whose path passes through index i beneath S.
/// Then: The reply has field 2 = 1 with failure code 0 or 1; no Referral naming C or C's new position is returned, and S's child table no longer lists C.
///
/// Interpretation: The spec requires failure rather than referral and names codes 0 and 1 as the stale-locator outcomes; which of the two S returns is the test's reading, and either is accepted.
#[test]
#[ignore = "acceptance RES-14: owed at milestone 4"]
fn res_14_remove_a_departed_infra_child_and_fail_never_red() {
    todo!("RES-14: Remove a departed infra child and fail, never redirect, for its old path")
}

/// Replace an infra child's endpoint list on a strictly greater counter, reordering included
///
/// Spec: wire-format.md §7.6; infra-client-requirements.md §4.4; wire-format.md §2.3
/// Milestone: 4.  Kind: positive.  Oracle: behaviour.
///
/// Rule (wire-format.md §7.6): "Publishing a changed endpoint list advances the counter — and the list is ordered, so reordering alone is a change"
/// Rule (wire-format.md §7.6): "Freshness by seqno, strictly greater counter to replace within a series"
///
/// Given: Infra node S holds infra child C's EndpointRecord with seqno [s, c] listing endpoints [E1, E2].
/// When: C publishes a record with seqno [s, c+1] listing [E2, E1], and S then receives a ResolveRequest into C's subtree.
/// Then: The Referral lists C's endpoints as [E2, E1], in the new record's order.
#[test]
#[ignore = "acceptance RES-15: owed at milestone 4"]
fn res_15_replace_an_infra_child_s_endpoint_list_on_a_stri() {
    todo!("RES-15: Replace an infra child's endpoint list on a strictly greater counter, reordering included")
}

/// Keep no record of who asked about whom after answering a resolution
///
/// Spec: infra-client-requirements.md §4.5; infra-client-requirements.md §1
/// Milestone: 4.  Kind: positive.  Oracle: behaviour.
///
/// Rule (infra-client-requirements.md §4.5): "answer the request, keep no record of who asked about whom"
///
/// Given: Infra node S has answered a ResolveRequest from authenticated requester Q about subject X, and the session with Q has closed.
/// When: S's persistent state and logs are inspected.
/// Then: No record pairs Q with X: neither the request nonce, nor the (requester, subject) pair, nor a query-log entry survives the answer.
///
/// Interpretation: The obligation is a commitment the protocol cannot enforce (design §1.1); the test checks the reference implementation's own storage and treats any retained pairing as a failure.
#[test]
#[ignore = "acceptance RES-16: owed at milestone 4"]
fn res_16_keep_no_record_of_who_asked_about_whom_after_ans() {
    todo!("RES-16: Keep no record of who asked about whom after answering a resolution")
}
