//! GENERATED by tools/gen_stubs.py from acceptance.json.  Do not edit;
//! change the catalogue and regenerate.  Each stub is one acceptance test
//! still owed for this area.

/// Report primary mode to a client attaching to its own serving node.
///
/// Spec: design §14.1.2; infra-client-requirements.md §1
/// Milestone: 2.  Kind: positive.  Oracle: behaviour.
///
/// Rule (infra-client-requirements.md §1): "Determine the attachment mode from local topology. A client not in this node's subtree is in failover, and report it."
/// Rule (design §14.1.2): "Light client dials out to its serving infra node. The nearest infrastructure node on its patron chain, which is not necessarily its patron"
///
/// Given: Infra node N holds an adoption of light client C directly under it, so N is C's nearest infrastructure ancestor. The heartbeat interval is unset (design §21.1) and is a test parameter: the node advertises the harness's chosen value I, in seconds within 1..3600, in AttachAck field 3.
/// When: C dials N and sends Attach with field 1 equal to its own keyhash.
/// Then: N answers with AttachAck whose field 1 (mode) is 0 and whose field 3 is I.
#[test]
#[ignore = "acceptance SES-01: owed at milestone 2"]
fn ses_01_report_primary_mode_to_a_client_attaching_to_its() {
    todo!("SES-01: Report primary mode to a client attaching to its own serving node.")
}

/// Accept a client whose patron is a light client, on the walk-up to infrastructure.
///
/// Spec: design §14.1.2; infra-client-requirements.md §1
/// Milestone: 2.  Kind: must-accept.  Oracle: behaviour.
///
/// Rule (infra-client-requirements.md §1): "Accept attachment from any node whose nearest infrastructure ancestor is this node, and from siblings' clients in failover"
/// Rule (design §14.1.2): "A light client whose patron is itself a light client (§3.3 permits this) walks up until it reaches infrastructure."
///
/// Given: Infra node N has adopted light client P; P has adopted light client C. C's nearest infrastructure ancestor is therefore N, which is not its patron. The heartbeat interval is unset (design §21.1) and is a test parameter: the node advertises the harness's chosen value I, in seconds within 1..3600, in AttachAck field 3.
/// When: C dials N and sends Attach.
/// Then: N does not close the connection with application close code 1; it answers with AttachAck whose field 1 (mode) is 0.
#[test]
#[ignore = "acceptance SES-02: owed at milestone 2"]
fn ses_02_accept_a_client_whose_patron_is_a_light_client_o() {
    todo!("SES-02: Accept a client whose patron is a light client, on the walk-up to infrastructure.")
}

/// Send the first heartbeat after one full interval, counter 0, then one per interval.
///
/// Spec: wire-format.md §8.2
/// Milestone: 2.  Kind: positive.  Oracle: behaviour.
///
/// Rule (wire-format.md §8.2): "Both sides send one Heartbeat per advertised interval, so liveness is bidirectional and the interval is the serving node's to set."
/// Rule (wire-format.md §8.2): "counter 0 is sent after one interval, not immediately"
///
/// Given: A session between C and N is established (AttachAck received). The heartbeat interval is unset (design §21.1) and is a test parameter: the node advertises the harness's chosen value I, in seconds within 1..3600, in AttachAck field 3. Stream 0 is observed in both directions from the moment AttachAck is sent.
/// When: Three intervals of I seconds elapse with no other traffic.
/// Then: Each side's first Heartbeat carries counter 0 and is sent no earlier than I seconds after AttachAck; each side's next two carry counters 1 and 2, one per interval.
#[test]
#[ignore = "acceptance SES-03: owed at milestone 2"]
fn ses_03_send_the_first_heartbeat_after_one_full_interval() {
    todo!("SES-03: Send the first heartbeat after one full interval, counter 0, then one per interval.")
}

/// Reset liveness on any valid beat with an unseen counter, so one lost beat does not fail over.
///
/// Spec: wire-format.md §8.2
/// Milestone: 2.  Kind: robustness.  Oracle: behaviour.
///
/// Rule (wire-format.md §8.2): "valid beat carrying a counter not yet seen resets"
/// Rule (wire-format.md §8.2): "Liveness rule: a peer is considered failed after 3 consecutive missed intervals"
///
/// Given: A session between C and N with interval I; the harness sits on the path and can drop individual frames. C holds a sibling list from AttachAck.
/// When: The harness drops N's Heartbeat with counter 1 and delivers counters 2, 3, 4 and onward on time, for at least six intervals.
/// Then: C stays in the session on N: it opens no connection to any sibling and continues sending its own Heartbeats to N throughout.
#[test]
#[ignore = "acceptance SES-04: owed at milestone 2"]
fn ses_04_reset_liveness_on_any_valid_beat_with_an_unseen() {
    todo!("SES-04: Reset liveness on any valid beat with an unseen counter, so one lost beat does not fail over.")
}

/// Count a malformed heartbeat as absence: no immediate close, three misses still govern.
///
/// Spec: wire-format.md §8.2
/// Milestone: 2.  Kind: negative.  Oracle: behaviour.
///
/// Rule (wire-format.md §8.2): "A malformed heartbeat counts as absence, not as a fault. It does not reset the detector and does not itself close the session; three missed intervals still govern."
///
/// Given: A session between C and N with interval I. The harness replaces every Heartbeat from C with a malformed frame carrying the Heartbeat frame type.
/// When: Three full intervals elapse with only malformed frames arriving from C.
/// Then: N does not close the session on receiving a malformed frame; after three full intervals N's inspectable reachability state for C reads unreachable, not before.
#[test]
#[ignore = "acceptance SES-05: owed at milestone 2"]
fn ses_05_count_a_malformed_heartbeat_as_absence_no_immedi() {
    todo!("SES-05: Count a malformed heartbeat as absence: no immediate close, three misses still govern.")
}

/// Fail over when only payload traffic arrives, since payload does not reset the detector.
///
/// Spec: wire-format.md §8.2; design §14.1.2
/// Milestone: 4.  Kind: negative.  Oracle: behaviour.
///
/// Rule (wire-format.md §8.2): "Unrelated payload or application traffic must not, since it would let incidental activity conceal failure of the very path the detector tests. Present encoding: only a Heartbeat resets the counter."
/// Rule (design §14.1.2): "after 3 consecutive missed intervals, the client attaches to another party in the same replication set as its serving node"
///
/// Given: C is in a session on N with interval I and holds sibling S's SiblingRef with KeyMaterial from AttachAck. N is scripted to keep sending payload frames on unidirectional streams while sending no Heartbeat.
/// When: Three full intervals elapse in which N sends payload but no Heartbeat.
/// Then: C dials S and receives an AttachAck from S with field 1 (mode) equal to 1.
#[test]
#[ignore = "acceptance SES-06: owed at milestone 4"]
fn ses_06_fail_over_when_only_payload_traffic_arrives_sinc() {
    todo!("SES-06: Fail over when only payload traffic arrives, since payload does not reset the detector.")
}

/// Count intervals that elapsed during a suspension on waking, not timer callbacks.
///
/// Spec: wire-format.md §8.2
/// Milestone: 4.  Kind: robustness.  Oracle: behaviour.
///
/// Rule (wire-format.md §8.2): "Misses are counted by elapsed full intervals on a local monotonic clock, not by delivered timer callbacks."
/// Rule (wire-format.md §8.2): "A mobile runtime suspended for three intervals has missed three on waking"
///
/// Given: C is in a session on N with interval I and holds sibling S's SiblingRef with KeyMaterial. N is stopped.
/// When: C's process is suspended for longer than three intervals and then resumed.
/// Then: On resuming, C dials S before another full interval elapses, and receives an AttachAck from S with field 1 equal to 1.
///
/// Interpretation: 'Has missed three on waking' is read as failover beginning on waking; the one-interval bound is the test's, since wire-format.md §8.2 leaves timeout and backoff to local policy.
#[test]
#[ignore = "acceptance SES-07: owed at milestone 4"]
fn ses_07_count_intervals_that_elapsed_during_a_suspension() {
    todo!("SES-07: Count intervals that elapsed during a suspension on waking, not timer callbacks.")
}

/// Attach to a sibling of the serving node after three missed intervals, and be told the session is degraded.
///
/// Spec: design §14.1.2; wire-format.md §8.2
/// Milestone: 4.  Kind: positive.  Oracle: behaviour.
///
/// Rule (design §14.1.2): "after 3 consecutive missed intervals, the client attaches to another party in the same replication set as its serving node, and the resulting session is degraded."
/// Rule (wire-format.md §8.2): "The serving node determines the mode; the client is told."
///
/// Given: Infra nodes N and S are siblings (design §3.4); C is adopted under N and attached to N with interval I; N's AttachAck listed S with KeyMaterial.
/// When: N stops sending Heartbeats and all other frames for three full intervals.
/// Then: C dials S; S answers with AttachAck whose field 1 (mode) is 1.
#[test]
#[ignore = "acceptance SES-08: owed at milestone 4"]
fn ses_08_attach_to_a_sibling_of_the_serving_node_after_th() {
    todo!("SES-08: Attach to a sibling of the serving node after three missed intervals, and be told the session is degraded.")
}

/// Accept a sibling's client that fails over from its persisted list when its serving node is unreachable at attach time.
///
/// Spec: wire-format.md §8.2; light-client-requirements.md §4; infra-client-requirements.md §1
/// Milestone: 4.  Kind: must-accept.  Oracle: behaviour.
///
/// Rule (wire-format.md §8.2): "a client whose serving node is unreachable at attach time uses its cached sibling list immediately."
/// Rule (light-client-requirements.md §4): "Persist the cached sibling list across restarts."
/// Rule (infra-client-requirements.md §1): "Accept attachment from any node whose nearest infrastructure ancestor is this node, and from siblings' clients in failover"
///
/// Given: C previously attached to N and received an AttachAck listing sibling S with KeyMaterial; C's process has since exited. N is unreachable (no route) at the time of the next attach.
/// When: C starts and performs a fresh attach.
/// Then: C dials S without first waiting three heartbeat intervals, and S accepts: it does not close with application close code 1 and returns AttachAck with field 1 equal to 1.
#[test]
#[ignore = "acceptance SES-09: owed at milestone 4"]
fn ses_09_accept_a_sibling_s_client_that_fails_over_from_i() {
    todo!("SES-09: Accept a sibling's client that fails over from its persisted list when its serving node is unreachable at attach time.")
}

/// Produce no countersignature in a degraded session.
///
/// Spec: design §14.1.2
/// Milestone: 4.  Kind: negative.  Oracle: model.
///
/// Rule (design §14.1.2): "That party holds the replicated state but not the authority to countersign."
/// Rule (design §14.1.2): "Payload flows; trust-bearing operations do not"
///
/// Given: N is both patron and serving node of C; N is dark and C holds a degraded session on N's sibling S (AttachAck field 1 equal to 1).
/// When: C submits a subnet-scoped transaction that requires its patron's countersignature on the degraded session, and also sends ordinary payload.
/// Then: No transaction countersigned by S comes into existence, at S or at C; the payload is carried.
///
/// Interpretation: How a countersignature request travels on a session and how its non-performance is signalled are not encoded; the test observes only the absence of a countersignature by S.
#[test]
#[ignore = "acceptance SES-10: owed at milestone 4"]
fn ses_10_produce_no_countersignature_in_a_degraded_sessio() {
    todo!("SES-10: Produce no countersignature in a degraded session.")
}

/// Stay on the sibling while the degraded session lasts, even after the serving node returns.
///
/// Spec: wire-format.md §8.2; design §14.1.2
/// Milestone: 4.  Kind: negative.  Oracle: behaviour.
///
/// Rule (wire-format.md §8.2): "A client on a sibling stays there until that session ends; the next fresh attach tries its actual serving node first."
/// Rule (design §14.1.2): "No automatic failback: the client stays on the sibling until that session ends, and the next fresh attach tries its actual serving node first."
///
/// Given: C holds a degraded session on S with interval I after N went dark.
/// When: N becomes reachable again and stays reachable for at least six intervals while the degraded session continues.
/// Then: C opens no connection to N during that time and keeps exchanging Heartbeats with S.
#[test]
#[ignore = "acceptance SES-11: owed at milestone 4"]
fn ses_11_stay_on_the_sibling_while_the_degraded_session_l() {
    todo!("SES-11: Stay on the sibling while the degraded session lasts, even after the serving node returns.")
}

/// Try the actual serving node first on the next fresh attach after a degraded session.
///
/// Spec: wire-format.md §8.2; design §14.1.2
/// Milestone: 4.  Kind: positive.  Oracle: behaviour.
///
/// Rule (wire-format.md §8.2): "A client on a sibling stays there until that session ends; the next fresh attach tries its actual serving node first."
/// Rule (design §14.1.2): "the next fresh attach tries its actual serving node first"
///
/// Given: C holds a degraded session on S; N has since become reachable again.
/// When: C's session on S ends (C closes it) and C performs a fresh attach.
/// Then: C's first dial is to N, and N answers with AttachAck whose field 1 (mode) is 0.
#[test]
#[ignore = "acceptance SES-12: owed at milestone 4"]
fn ses_12_try_the_actual_serving_node_first_on_the_next_fr() {
    todo!("SES-12: Try the actual serving node first on the next fresh attach after a degraded session.")
}

/// Mark a client unreachable when its heartbeats stop.
///
/// Spec: design §14.1.2; wire-format.md §8.2; infra-client-requirements.md §1
/// Milestone: 2.  Kind: positive.  Oracle: behaviour.
///
/// Rule (design §14.1.2): "the patron marks the client unreachable and begins queuing."
/// Rule (wire-format.md §8.2): "Liveness rule: a peer is considered failed after 3 consecutive missed intervals"
/// Rule (infra-client-requirements.md §1): "Store the resulting reachability state, not the update history"
///
/// Given: C is attached to N with interval I; N exposes its reachability state per client to the test.
/// When: The harness blackholes all packets from C to N for three full intervals.
/// Then: N's reachability state for C reads unreachable after the third full interval, and read reachable at every inspection before it.
#[test]
#[ignore = "acceptance SES-13: owed at milestone 2"]
fn ses_13_mark_a_client_unreachable_when_its_heartbeats_st() {
    todo!("SES-13: Mark a client unreachable when its heartbeats stop.")
}

/// Replicate a client's unreachable state to the serving node's siblings.
///
/// Spec: design §14.1.2; design §3.4
/// Milestone: 4.  Kind: positive.  Oracle: behaviour.
///
/// Rule (design §14.1.2): "This state replicates to siblings, or a sibling answering during failover has no idea of the client's status."
/// Rule (design §3.4): "Siblings replicate each other's traffic (up to f−1 = 9)."
///
/// Given: N and S are siblings; C is attached to N with interval I; both nodes expose their reachability state per client to the test. Replication between N and S is running.
/// When: The harness blackholes all packets from C to N for three full intervals, and replication is allowed to proceed.
/// Then: S's reachability state for C reads unreachable.
///
/// Interpretation: No wire object carrying the replicated reachability state is specified; the test observes S's state and does not check what carried it or how soon it arrived.
#[test]
#[ignore = "acceptance SES-14: owed at milestone 4"]
fn ses_14_replicate_a_client_s_unreachable_state_to_the_se() {
    todo!("SES-14: Replicate a client's unreachable state to the serving node's siblings.")
}

/// Bind a 0-RTT reattach only after the handshake completes, and still complete it.
///
/// Spec: wire-format.md §8.2; design §14.1.3
/// Milestone: 2.  Kind: positive.  Oracle: model.
///
/// Rule (wire-format.md §8.2): "A server MUST NOT process an Attach received in TLS 1.3 0-RTT early data — reject it or defer it until handshake completion."
/// Rule (design §14.1.3): "0-RTT resumption makes frequent reattachment cheap, which permits a lazy heartbeat and saves battery."
///
/// Given: C completed an earlier session with N and holds a TLS 1.3 resumption ticket from it. The harness observes the connection and knows when its handshake completes.
/// When: C reconnects with 0-RTT and sends Attach in early data.
/// Then: No AttachAck is sent before the handshake of that connection completes; after completion an AttachAck arrives, either for the deferred early Attach or for an Attach C sends after the handshake if the early one was rejected.
#[test]
#[ignore = "acceptance SES-15: owed at milestone 2"]
fn ses_15_bind_a_0_rtt_reattach_only_after_the_handshake_c() {
    todo!("SES-15: Bind a 0-RTT reattach only after the handshake completes, and still complete it.")
}
