//! GENERATED by tools/gen_stubs.py from acceptance.json.  Do not edit;
//! change the catalogue and regenerate.  Each stub is one acceptance test
//! still owed for this area.

/// Fail over when only payload traffic arrives, since payload does not reset the detector.
///
/// Spec: wire-format.md §8.2; design §14.1.2
/// Milestone: 4.  Kind: negative.  Oracle: behaviour.
///
/// Rule (wire-format.md §8.2): "Unrelated payload or application traffic must not, since it would let incidental activity conceal failure of the very path the detector tests. Present encoding: only a Heartbeat resets the counter."
/// Rule (design §14.1.2): "after 3 consecutive missed intervals, the client attaches to another party in the same replication set as its serving node"
///
/// Given: C is in a session on N with interval I and holds sibling S's SiblingRef with KeyMaterial from AttachAck. N is scripted to keep sending payload frames on unidirectional streams while sending no Heartbeat.
/// When: Three full intervals elapse in which N sends payload but no Heartbeat.
/// Then: C dials S and receives an AttachAck from S with field 1 (mode) equal to 1.
#[test]
#[ignore = "acceptance SES-06: owed at milestone 4"]
fn ses_06_fail_over_when_only_payload_traffic_arrives_sinc() {
    todo!("SES-06: Fail over when only payload traffic arrives, since payload does not reset the detector.")
}

/// Count intervals that elapsed during a suspension on waking, not timer callbacks.
///
/// Spec: wire-format.md §8.2
/// Milestone: 4.  Kind: robustness.  Oracle: behaviour.
///
/// Rule (wire-format.md §8.2): "Misses are counted by elapsed full intervals on a local monotonic clock, not by delivered timer callbacks."
/// Rule (wire-format.md §8.2): "A mobile runtime suspended for three intervals has missed three on waking"
///
/// Given: C is in a session on N with interval I and holds sibling S's SiblingRef with KeyMaterial. N is stopped.
/// When: C's process is suspended for longer than three intervals and then resumed.
/// Then: On resuming, C dials S before another full interval elapses, and receives an AttachAck from S with field 1 equal to 1.
///
/// Interpretation: 'Has missed three on waking' is read as failover beginning on waking; the one-interval bound is the test's, since wire-format.md §8.2 leaves timeout and backoff to local policy.
#[test]
#[ignore = "acceptance SES-07: owed at milestone 4"]
fn ses_07_count_intervals_that_elapsed_during_a_suspension() {
    todo!("SES-07: Count intervals that elapsed during a suspension on waking, not timer callbacks.")
}

/// Attach to a sibling of the serving node after three missed intervals, and be told the session is degraded.
///
/// Spec: design §14.1.2; wire-format.md §8.2
/// Milestone: 4.  Kind: positive.  Oracle: behaviour.
///
/// Rule (design §14.1.2): "after 3 consecutive missed intervals, the client attaches to another party in the same replication set as its serving node, and the resulting session is degraded."
/// Rule (wire-format.md §8.2): "The serving node determines the mode; the client is told."
///
/// Given: Infra nodes N and S are siblings (design §3.4); C is adopted under N and attached to N with interval I; N's AttachAck listed S with KeyMaterial.
/// When: N stops sending Heartbeats and all other frames for three full intervals.
/// Then: C dials S; S answers with AttachAck whose field 1 (mode) is 1.
#[test]
#[ignore = "acceptance SES-08: owed at milestone 4"]
fn ses_08_attach_to_a_sibling_of_the_serving_node_after_th() {
    todo!("SES-08: Attach to a sibling of the serving node after three missed intervals, and be told the session is degraded.")
}

/// Accept a sibling's client that fails over from its persisted list when its serving node is unreachable at attach time.
///
/// Spec: wire-format.md §8.2; light-client-requirements.md §4; infra-client-requirements.md §1
/// Milestone: 4.  Kind: must-accept.  Oracle: behaviour.
///
/// Rule (wire-format.md §8.2): "a client whose serving node is unreachable at attach time uses its cached sibling list immediately."
/// Rule (light-client-requirements.md §4): "Persist the cached sibling list across restarts."
/// Rule (infra-client-requirements.md §1): "Accept attachment from any node whose nearest infrastructure ancestor is this node, and from siblings' clients in failover"
///
/// Given: C previously attached to N and received an AttachAck listing sibling S with KeyMaterial; C's process has since exited. N is unreachable (no route) at the time of the next attach.
/// When: C starts and performs a fresh attach.
/// Then: C dials S without first waiting three heartbeat intervals, and S accepts: it does not close with application close code 1 and returns AttachAck with field 1 equal to 1.
#[test]
#[ignore = "acceptance SES-09: owed at milestone 4"]
fn ses_09_accept_a_sibling_s_client_that_fails_over_from_i() {
    todo!("SES-09: Accept a sibling's client that fails over from its persisted list when its serving node is unreachable at attach time.")
}

/// Produce no countersignature in a degraded session.
///
/// Spec: design §14.1.2
/// Milestone: 4.  Kind: negative.  Oracle: model.
///
/// Rule (design §14.1.2): "That party holds the replicated state but not the authority to countersign."
/// Rule (design §14.1.2): "Payload flows; trust-bearing operations do not"
///
/// Given: N is both patron and serving node of C; N is dark and C holds a degraded session on N's sibling S (AttachAck field 1 equal to 1).
/// When: C submits a subnet-scoped transaction that requires its patron's countersignature on the degraded session, and also sends ordinary payload.
/// Then: No transaction countersigned by S comes into existence, at S or at C; the payload is carried.
///
/// Interpretation: How a countersignature request travels on a session and how its non-performance is signalled are not encoded; the test observes only the absence of a countersignature by S.
#[test]
#[ignore = "acceptance SES-10: owed at milestone 4"]
fn ses_10_produce_no_countersignature_in_a_degraded_sessio() {
    todo!("SES-10: Produce no countersignature in a degraded session.")
}

/// Stay on the sibling while the degraded session lasts, even after the serving node returns.
///
/// Spec: wire-format.md §8.2; design §14.1.2
/// Milestone: 4.  Kind: negative.  Oracle: behaviour.
///
/// Rule (wire-format.md §8.2): "A client on a sibling stays there until that session ends; the next fresh attach tries its actual serving node first."
/// Rule (design §14.1.2): "No automatic failback: the client stays on the sibling until that session ends, and the next fresh attach tries its actual serving node first."
///
/// Given: C holds a degraded session on S with interval I after N went dark.
/// When: N becomes reachable again and stays reachable for at least six intervals while the degraded session continues.
/// Then: C opens no connection to N during that time and keeps exchanging Heartbeats with S.
#[test]
#[ignore = "acceptance SES-11: owed at milestone 4"]
fn ses_11_stay_on_the_sibling_while_the_degraded_session_l() {
    todo!("SES-11: Stay on the sibling while the degraded session lasts, even after the serving node returns.")
}

/// Try the actual serving node first on the next fresh attach after a degraded session.
///
/// Spec: wire-format.md §8.2; design §14.1.2
/// Milestone: 4.  Kind: positive.  Oracle: behaviour.
///
/// Rule (wire-format.md §8.2): "A client on a sibling stays there until that session ends; the next fresh attach tries its actual serving node first."
/// Rule (design §14.1.2): "the next fresh attach tries its actual serving node first"
///
/// Given: C holds a degraded session on S; N has since become reachable again.
/// When: C's session on S ends (C closes it) and C performs a fresh attach.
/// Then: C's first dial is to N, and N answers with AttachAck whose field 1 (mode) is 0.
#[test]
#[ignore = "acceptance SES-12: owed at milestone 4"]
fn ses_12_try_the_actual_serving_node_first_on_the_next_fr() {
    todo!("SES-12: Try the actual serving node first on the next fresh attach after a degraded session.")
}

/// Replicate a client's unreachable state to the serving node's siblings.
///
/// Spec: design §14.1.2; design §3.4
/// Milestone: 4.  Kind: positive.  Oracle: behaviour.
///
/// Rule (design §14.1.2): "This state replicates to siblings, or a sibling answering during failover has no idea of the client's status."
/// Rule (design §3.4): "Siblings replicate each other's topology and trust-bearing transaction history (up to f−1 = 9)."
///
/// Given: N and S are siblings; C is attached to N with interval I; both nodes expose their reachability state per client to the test. Replication between N and S is running.
/// When: The harness blackholes all packets from C to N for three full intervals, and replication is allowed to proceed.
/// Then: S's reachability state for C reads unreachable.
///
/// Interpretation: No wire object carrying the replicated reachability state is specified; the test observes S's state and does not check what carried it or how soon it arrived.
#[test]
#[ignore = "acceptance SES-14: owed at milestone 4"]
fn ses_14_replicate_a_client_s_unreachable_state_to_the_se() {
    todo!("SES-14: Replicate a client's unreachable state to the serving node's siblings.")
}

/// Bind a 0-RTT reattach only after the handshake completes, and still complete it.
///
/// Spec: wire-format.md §8.2; design §14.1.3
/// Milestone: 2.  Kind: positive.  Oracle: model.
///
/// Rule (wire-format.md §8.2): "A server MUST NOT process an Attach received in TLS 1.3 0-RTT early data — reject it or defer it until handshake completion."
/// Rule (design §14.1.3): "0-RTT resumption makes frequent reattachment cheap, which permits a lazy heartbeat and saves battery."
///
/// Given: C completed an earlier session with N and holds a TLS 1.3 resumption ticket from it. The harness observes the connection and knows when its handshake completes.
/// When: C reconnects with 0-RTT and sends Attach in early data.
/// Then: No AttachAck is sent before the handshake of that connection completes; after completion an AttachAck arrives, either for the deferred early Attach or for an Attach C sends after the handshake if the early one was rejected.
#[test]
#[ignore = "acceptance SES-15: owed at milestone 2"]
fn ses_15_bind_a_0_rtt_reattach_only_after_the_handshake_c() {
    todo!("SES-15: Bind a 0-RTT reattach only after the handshake completes, and still complete it.")
}
