//! GENERATED by tools/gen_stubs.py from acceptance.json.  Do not edit;
//! change the catalogue and regenerate.  Each stub is one acceptance test
//! still owed for this area.

/// Serve a light client whose patron is a light client: it attaches to the nearest infrastructure ancestor as primary
///
/// Spec: infra-client-requirements.md §4.1; infra-client-requirements.md §1; design §14.1.2; wire-format.md §8.2
/// Milestone: 3.  Kind: positive.  Oracle: behaviour.
///
/// Rule (infra-client-requirements.md §4.1): "Every light client beneath you attaches to you — not only your direct subordinates, since design §14.1.2 has a client walk up past light-client patrons to the nearest infrastructure."
/// Rule (infra-client-requirements.md §1): "Accept attachment from any node whose nearest infrastructure ancestor is this node"
///
/// Given: Infra node I whose table holds light client A under I and light client B under A; B's client holds the same topology.
/// When: B dials its serving node and attaches.
/// Then: B's dial goes to I, not to A; I accepts and its AttachAck field 1 is 0, primary; I's table lists B among its attached light clients by path, beneath A.
#[test]
#[ignore = "acceptance TOP-13: owed at milestone 3"]
fn top_13_serve_a_light_client_whose_patron_is_a_light_cli() {
    todo!("TOP-13: Serve a light client whose patron is a light client: it attaches to the nearest infrastructure ancestor as primary")
}
