//! GENERATED by tools/gen_stubs.py from acceptance.json.  Do not edit;
//! change the catalogue and regenerate.  Each stub is one acceptance test
//! still owed for this area.

/// Add a subordinate and its sibling relationships to the table on a verified adoption
///
/// Spec: design §6.1; design §3.4; design §3.1
/// Milestone: 3.  Kind: positive.  Oracle: behaviour.
///
/// Rule (design §6.1): "Patron accepts a new subordinate. Also implicitly authorises sibling peering among that patron's children."
/// Rule (design §3.4): "Authorised implicitly by the patron's adoption transaction, with no separate agreement."
///
/// Given: Observer O's table, fed verified transactions directly since propagation is out of scope, holding patron P with one subordinate C; a proof-of-presence record between P and N.
/// When: O verifies an adoption of N under P whose field 8 names that record.
/// Then: O's table answers: N's patrons include P; P's subordinates are {C, N}; C's siblings include N and N's siblings include C.
#[test]
#[ignore = "acceptance TOP-01: owed at milestone 3"]
fn top_01_add_a_subordinate_and_its_sibling_relationships() {
    todo!("TOP-01: Add a subordinate and its sibling relationships to the table on a verified adoption")
}

/// Hold a second adoption beside the first: adopting elsewhere leaves the old binding in view
///
/// Spec: design §6.2.1; design §6.2; wire-format.md §4.2
/// Milestone: 3.  Kind: must-accept.  Oracle: model.
///
/// Rule (design §6.2.1): "Without it, a node that adopts elsewhere remains in the old subtree's view indefinitely, since adoption says nothing about existing bindings."
/// Rule (design §6.2): "the protocol has no concept of a node's set of patrons"
///
/// Given: O's table holding N adopted under P1, series s1. An adoption of N under P2 carrying either P1's countersignature as former patron or a proof of presence between N and P2, opening series s2.
/// When: O verifies the second adoption, with no departure from P1 signed.
/// Then: O's table answers N's patrons = {P1, P2}; N remains among P1's subordinates; the second adoption is accepted rather than rejected as a duplicate binding, and it does not replace the first.
#[test]
#[ignore = "acceptance TOP-02: owed at milestone 3"]
fn top_02_hold_a_second_adoption_beside_the_first_adopting() {
    todo!("TOP-02: Hold a second adoption beside the first: adopting elsewhere leaves the old binding in view")
}

/// End only the named relationship on a departure
///
/// Spec: wire-format.md §4.2; design §6.2; design §6.2.1
/// Milestone: 3.  Kind: positive.  Oracle: model.
///
/// Rule (wire-format.md §4.2): "Single signature: the departing node."
/// Rule (design §6.2): "Moving between patrons remains adopt at the destination, depart the origin, in either order, with no requirement to do both"
///
/// Given: O's table holding N under P1 and under P2, as TOP-02 leaves it.
/// When: O verifies a departure signed by N alone with field 2 = P1.
/// Then: O's table answers N's patrons = {P2}; N is no longer among P1's subordinates and no longer a sibling of P1's other children; N's binding under P2 is unchanged.
#[test]
#[ignore = "acceptance TOP-03: owed at milestone 3"]
fn top_03_end_only_the_named_relationship_on_a_departure() {
    todo!("TOP-03: End only the named relationship on a departure")
}

/// Leave a departed node in the table as a root when it has no other binding
///
/// Spec: design §6.2.1; design §3.1; wire-format.md §4.2
/// Milestone: 3.  Kind: positive.  Oracle: model.
///
/// Rule (design §6.2.1): "Required for a node to become a root by its own action."
/// Rule (design §3.1): "Roots have none, which is an ordinary state rather than an error"
///
/// Given: O's table holding N under P and under nobody else.
/// When: O verifies N's departure from P.
/// Then: O's table answers N's patrons = {} and still lists N as a node; N is removed from P's subordinates; no error is raised for a patronless node.
#[test]
#[ignore = "acceptance TOP-04: owed at milestone 3"]
fn top_04_leave_a_departed_node_in_the_table_as_a_root_whe() {
    todo!("TOP-04: Leave a departed node in the table as a root when it has no other binding")
}

/// End one relationship and nothing else on a disavowal
///
/// Spec: design §6.2.2; wire-format.md §4.3
/// Milestone: 3.  Kind: positive.  Oracle: behaviour.
///
/// Rule (design §6.2.2): "Disavowal is positional: it ends one patron-subordinate relationship and nothing else. The node remains in the tree and may be adopted elsewhere within the same subnet"
///
/// Given: O's table holding N under P and under Q, and M under N.
/// When: O verifies a disavowal signed by P alone with field 2 = N and reason code 0.
/// Then: O's table answers N's patrons = {Q}; N is removed from P's subordinates; M's patrons still include N; N remains a node in the table.
#[test]
#[ignore = "acceptance TOP-05: owed at milestone 3"]
fn top_05_end_one_relationship_and_nothing_else_on_a_disav() {
    todo!("TOP-05: End one relationship and nothing else on a disavowal")
}

/// Apply a disavowal on verification regardless of its timestamp
///
/// Spec: wire-format.md §4.3; design §6.2.2
/// Milestone: 3.  Kind: must-accept.  Oracle: behaviour.
///
/// Rule (wire-format.md §4.3): "There is no notice period. A disavowal takes effect when signed"
/// Rule (design §6.2.2): "A disavowal takes effect when it is signed."
///
/// Given: O's table holding N under P; O's clock reads t_now.
/// When: O verifies a disavowal of N by P whose timestamp is t_now plus seven days and not earlier than the effective time of P's predecessor record.
/// Then: O's table removes N from P's subordinates on verification; the relationship is not held open until the timestamp, and the record is not rejected for its timestamp.
#[test]
#[ignore = "acceptance TOP-06: owed at milestone 3"]
fn top_06_apply_a_disavowal_on_verification_regardless_of() {
    todo!("TOP-06: Apply a disavowal on verification regardless of its timestamp")
}

/// Issue a subtree acknowledgement under standing policy without operator interaction
///
/// Spec: wire-format.md §7.5; infra-client-requirements.md §10.1; design §11.2.1
/// Milestone: 3.  Kind: positive.  Oracle: behaviour.
///
/// Rule (wire-format.md §7.5): "Issued by the grandpatron's node, not by its operator."
/// Rule (infra-client-requirements.md §10.1): "Issue it automatically, under a policy the operator set beforehand."
///
/// Given: Infra node G with subordinate P and an acknowledgement policy, set beforehand, that acknowledges every adoption under P; no operator session is open.
/// When: G's node verifies an adoption of N under P with txid a.
/// Then: G's node emits a SubtreeAck with field 1 = a, field 2 = G, field 3 = N, and field 5 a signature by G that verifies over fields 1 to 4 with external_aad rhtn/1:subtree-ack; no prompt and no operator input occurs between verification and emission.
#[test]
#[ignore = "acceptance TOP-07: owed at milestone 3"]
fn top_07_issue_a_subtree_acknowledgement_under_standing_p() {
    todo!("TOP-07: Issue a subtree acknowledgement under standing policy without operator interaction")
}

/// Enter an adoption in the table whether or not the grandpatron acknowledges it
///
/// Spec: design §11.2.1; wire-format.md §7.5
/// Milestone: 3.  Kind: must-accept.  Oracle: behaviour.
///
/// Rule (design §11.2.1): "It does not gate the adoption. The adoption is complete and valid with the node and patron signatures (wire-format.md §4.1); it is signed and propagated whether or not the grandpatron acknowledges it."
///
/// Given: Tables at P and at P's sibling S holding P under G; G's node is offline, or its policy acknowledges nobody.
/// When: P and N sign an adoption of N under P and S verifies it, with no SubtreeAck ever arriving.
/// Then: S's table answers N's patrons = {P} and lists N under P; S holds no acknowledgement for N; the adoption is neither held pending nor rejected for the missing acknowledgement.
#[test]
#[ignore = "acceptance TOP-08: owed at milestone 3"]
fn top_08_enter_an_adoption_in_the_table_whether_or_not_th() {
    todo!("TOP-08: Enter an adoption in the table whether or not the grandpatron acknowledges it")
}

/// Discard a subtree acknowledgement when the relationship it describes ends
///
/// Spec: wire-format.md §7.5; infra-client-requirements.md §10.1; design §11.2.1
/// Milestone: 3.  Kind: positive.  Oracle: behaviour.
///
/// Rule (wire-format.md §7.5): "It lapses when the acknowledged relationship ends. If the grandpatron disavows the patron, or the patron departs, the acknowledgement describes a subtree the node is no longer in and confers nothing."
/// Rule (wire-format.md §7.5): "Discard it when it lapses"
///
/// Given: A holder H, G's sibling, whose table holds P under G and N under P, and who holds G's SubtreeAck for N.
/// When: H verifies P's departure from G; in a second run, G's disavowal of P.
/// Then: In both runs H's list of held acknowledgements no longer contains the acknowledgement for N, no revocation object having been received; N's binding under P is still in H's table.
#[test]
#[ignore = "acceptance TOP-09: owed at milestone 3"]
fn top_09_discard_a_subtree_acknowledgement_when_the_relat() {
    todo!("TOP-09: Discard a subtree acknowledgement when the relationship it describes ends")
}

/// Create no binding from a subtree acknowledgement whose adoption is not held
///
/// Spec: wire-format.md §7.5; infra-client-requirements.md §10.1
/// Milestone: 3.  Kind: negative.  Oracle: behaviour.
///
/// Rule (wire-format.md §7.5): "It attests membership of a subtree, not identity. The adoption's own signatures carry identity."
/// Rule (infra-client-requirements.md §10.1): "It says nothing about identity. The adoption's signatures carry that. Do not let a SubtreeAck stand in for evidence about who someone is."
///
/// Given: A holder H whose table holds P under G and no adoption of N, and who holds G's key material.
/// When: H receives a well-formed SubtreeAck signed by G naming an adoption txid a and node N, with a not held by H.
/// Then: H's table answers N's patrons = {} and does not list N under P; the acknowledgement's signature verifies, and no table entry for N results from it.
///
/// Interpretation: The sections quoted say an acknowledgement carries no identity evidence; the test reads that as an acknowledgement alone never creating a binding, which no sentence states directly.
#[test]
#[ignore = "acceptance TOP-10: owed at milestone 3"]
fn top_10_create_no_binding_from_a_subtree_acknowledgement() {
    todo!("TOP-10: Create no binding from a subtree acknowledgement whose adoption is not held")
}

/// Form a subnet from two Genesis identities: a formation record, then one adopts the other as first root
///
/// Spec: design §13.1; design §12.7.1; wire-format.md §3.2
/// Milestone: 3.  Kind: positive.  Oracle: behaviour.
///
/// Rule (design §13.1): "One adopts the other and becomes the subnet's first root."
/// Rule (design §13.1): "They perform a proof-of-presence ceremony with no witnesses and no verifiers."
///
/// Given: Two fresh keys A and B with empty archives and empty tables; A runs an infra instance, its static address outside the test's scope.
/// When: A and B sign a formation presence record, subtype 1 with no witnesses, no verifier responses and genesis back-pointers, then an adoption of B under A whose field 8 names that record; both tables verify both.
/// Then: Both tables answer: A's patrons = {}, A's subordinates = {B}, B's patrons = {A}. Each archive holds the formation record as its first transaction and the adoption as its second, the adoption's back-pointer for each signer naming the formation record.
#[test]
#[ignore = "acceptance TOP-11: owed at milestone 3"]
fn top_11_form_a_subnet_from_two_genesis_identities_a_form() {
    todo!("TOP-11: Form a subnet from two Genesis identities: a formation record, then one adopts the other as first root")
}

/// Do not apply an adoption whose named presence record is not between these two parties
///
/// Spec: wire-format.md §3.4; design §6.1.1
/// Milestone: 3.  Kind: negative.  Oracle: behaviour.
///
/// Rule (wire-format.md §3.4): "The check is that the record exists and names these two parties, both of which are body fields."
/// Rule (wire-format.md §3.4): "That is an evaluation step, not a structural one"
///
/// Given: O's table holding P; a presence record between P and a third party Z held by O; a structurally valid adoption of N under P whose field 8 names that record.
/// When: O verifies the adoption structurally, then evaluates it, dereferencing field 8, before applying it to the table.
/// Then: Structural verification reports valid. Evaluation reports the presence reference unsatisfied, the record naming P and Z rather than P and N, and O's table does not gain N under P.
///
/// Interpretation: Whether a failed evaluation keeps the adoption out of the table is not stated; wire-format.md §3.4 makes taking effect a separate question from validity, and the test reads the evaluation step as the gate on applying the binding.
#[test]
#[ignore = "acceptance TOP-12: owed at milestone 3"]
fn top_12_do_not_apply_an_adoption_whose_named_presence_re() {
    todo!("TOP-12: Do not apply an adoption whose named presence record is not between these two parties")
}

/// Serve a light client whose patron is a light client: it attaches to the nearest infrastructure ancestor as primary
///
/// Spec: infra-client-requirements.md §4.1; infra-client-requirements.md §1; design §14.1.2; wire-format.md §8.2
/// Milestone: 3.  Kind: positive.  Oracle: behaviour.
///
/// Rule (infra-client-requirements.md §4.1): "Every light client beneath you attaches to you — not only your direct subordinates, since design §14.1.2 has a client walk up past light-client patrons to the nearest infrastructure."
/// Rule (infra-client-requirements.md §1): "Accept attachment from any node whose nearest infrastructure ancestor is this node"
///
/// Given: Infra node I whose table holds light client A under I and light client B under A; B's client holds the same topology.
/// When: B dials its serving node and attaches.
/// Then: B's dial goes to I, not to A; I accepts and its AttachAck field 1 is 0, primary; I's table lists B among its attached light clients by path, beneath A.
#[test]
#[ignore = "acceptance TOP-13: owed at milestone 3"]
fn top_13_serve_a_light_client_whose_patron_is_a_light_cli() {
    todo!("TOP-13: Serve a light client whose patron is a light client: it attaches to the nearest infrastructure ancestor as primary")
}

/// Refuse a proposed patron only when the table places it in the node's own down-line
///
/// Spec: design §6.2.5; design §3.1
/// Milestone: 3.  Kind: negative.  Oracle: behaviour.
///
/// Rule (design §6.2.5): "Rejection is on positive knowledge only: reject where local topology establishes that the proposed patron is at or below the node, and never for absence of knowledge."
///
/// Given: Node N's table holding M under N and M2 under M, and holding nothing about a node X.
/// When: N's client is asked to adopt under M2, and separately to adopt under X, ceremony evidence being supplied in both cases.
/// Then: The proposal to adopt under M2 is refused by the local check, which reports that M2 lies below N, and no adoption is signed. The proposal to adopt under X is not refused by the check, and an adoption of N under X is signed.
#[test]
#[ignore = "acceptance TOP-14: owed at milestone 3"]
fn top_14_refuse_a_proposed_patron_only_when_the_table_pla() {
    todo!("TOP-14: Refuse a proposed patron only when the table places it in the node's own down-line")
}

/// Replace the old key with the successor on a recovery adoption inside the horizon
///
/// Spec: design §9.0.2; wire-format.md §4.1
/// Milestone: 3.  Kind: positive.  Oracle: behaviour.
///
/// Rule (design §9.0.2): "members holding the old key remove it from their records and overwrite it with the new one"
///
/// Given: O's table holding identity K_old under P. A recovery adoption of K_new under P carrying a Recovery block with prior_key = K_old, structurally valid and passing the evidence gate; the evidence is supplied by fixture, its generation being out of scope.
/// When: O verifies and applies the recovery adoption.
/// Then: O's table answers K_new's patrons = {P}; K_old is no longer listed under P and is not a current key in O's table; O holds exactly one current key for the identity.
#[test]
#[ignore = "acceptance TOP-15: owed at milestone 3"]
fn top_15_replace_the_old_key_with_the_successor_on_a_reco() {
    todo!("TOP-15: Replace the old key with the successor on a recovery adoption inside the horizon")
}

/// Hold one current key per identity when two recovery adoptions compete for the same prior key
///
/// Spec: design §9.0.2
/// Milestone: 3.  Kind: positive.  Oracle: behaviour.
///
/// Rule (design §9.0.2): "a member receiving two competing recovery adoptions for the same prior_key does not hold both as current — it resolves to one, by which patron it trusts"
///
/// Given: O's table holding K_old under P; two recovery adoptions, K_a under P_a and K_b under P_b, each with prior_key = K_old and each passing the evidence gate; which of P_a and P_b O trusts more is O's own policy, fixed by no document, and the test sets it as a parameter.
/// When: O verifies and applies both adoptions, in each of the two orders.
/// Then: O's table holds exactly one current key for the identity, K_a when O prefers P_a and K_b otherwise, the same one in both orders; both K_a and K_b are present as nodes under their own patrons.
///
/// Interpretation: Independence from arrival order follows from resolving by patron trust rather than by arrival; no sentence states it.
#[test]
#[ignore = "acceptance TOP-16: owed at milestone 3"]
fn top_16_hold_one_current_key_per_identity_when_two_recov() {
    todo!("TOP-16: Hold one current key per identity when two recovery adoptions compete for the same prior key")
}

/// Order a disavowal within the patron's own slot by the patron's timestamp
///
/// Spec: design §6.2.2; wire-format.md §4.3
/// Milestone: 3.  Kind: positive.  Oracle: behaviour.
///
/// Rule (design §6.2.2): "A disavowal is ordered by the patron's own clock."
/// Rule (wire-format.md §4.3): "Field 3 orders the disavowal within the patron's own slot"
///
/// Given: Patron P's table holds N in slot k from an adoption stamped t1; P signs a disavowal of N stamped t2 > t1, then re-adopts N with an adoption stamped t3 > t2 that opens a fresh series.
/// When: P's records are read after the three, in any arrival order.
/// Then: P's slot k shows N present from t1, empty from t2, and N present again from t3 under the new series; the relationship's status at any time is decided from P's own timestamps and nothing another party signed.
#[test]
#[ignore = "acceptance TOP-17: owed at milestone 3"]
fn top_17_order_a_disavowal_within_the_patron_s_own_slot_b() {
    todo!("TOP-17: Order a disavowal within the patron's own slot by the patron's timestamp")
}
