//! GENERATED by tools/gen_stubs.py from acceptance.json.  Do not edit;
//! change the catalogue and regenerate.  Each stub is one acceptance test
//! still owed for this area.

/// Offer only X25519MLKEM768 as the key-exchange group.
///
/// Spec: wire-format.md §9.1
/// Milestone: 2.  Kind: positive.  Oracle: behaviour.
///
/// Rule (wire-format.md §9.1): "QUIC with TLS 1.3, key exchange group X25519MLKEM768."
/// Rule (wire-format.md §9.1): "offering only X25519MLKEM768 is what leaves nothing weaker to fall back to."
///
/// Given: The implementation acts as the dialling party toward a test endpoint that records the TLS ClientHello carried in the QUIC Initial packets (readable with the Initial keys).
/// When: The implementation opens a connection to that endpoint.
/// Then: The ClientHello's supported_groups extension lists exactly one group, X25519MLKEM768, and its key_share extension carries no share for any other group.
#[test]
#[ignore = "acceptance TRN-01: owed at milestone 2"]
fn trn_01_offer_only_x25519mlkem768_as_the_key_exchange_gr() {
    todo!("TRN-01: Offer only X25519MLKEM768 as the key-exchange group.")
}

/// Complete no handshake with a peer that offers only weaker groups.
///
/// Spec: wire-format.md §9.1
/// Milestone: 2.  Kind: negative.  Oracle: behaviour.
///
/// Rule (wire-format.md §9.1): "That nothing can be negotiated below the named group is this profile's doing, not TLS's"
/// Rule (wire-format.md §9.1): "offering only X25519MLKEM768 is what leaves nothing weaker to fall back to."
///
/// Given: The implementation acts as the serving node. A test client presents a valid raw public key and ALPN rhtn/1, but its ClientHello supported_groups extension lists only classical groups (X25519 and secp256r1) and no X25519MLKEM768.
/// When: The test client attempts the handshake.
/// Then: No handshake completes: the connection ends during the handshake, no session is established, and no AttachAck can be obtained on it.
#[test]
#[ignore = "acceptance TRN-02: owed at milestone 2"]
fn trn_02_complete_no_handshake_with_a_peer_that_offers_on() {
    todo!("TRN-02: Complete no handshake with a peer that offers only weaker groups.")
}

/// Abort the dial when the presented raw public key is not the pinned classical member.
///
/// Spec: wire-format.md §9.1; wire-format.md §2.2
/// Milestone: 2.  Kind: negative.  Oracle: model.
///
/// Rule (wire-format.md §9.1): "The dialling party checks that key is the classical member of the KeyMaterial it has pinned for the keyhash it intended to reach."
/// Rule (wire-format.md §9.1): "a wrong address produces a failed handshake rather than a false identity."
/// Rule (wire-format.md §2.2): "KeyMaterial = [ COSE_Key, COSE_Key ]   ; [classical, post-quantum]"
///
/// Given: The implementation, as dialling party, holds a validated pin for keyhash K: a KeyMaterial that hashes to K. A test endpoint advertised for K completes the TLS handshake with an RFC 7250 raw public key whose SubjectPublicKeyInfo is a valid Ed25519 key that is not the first entry of that KeyMaterial.
/// When: The implementation dials the endpoint intending to reach K.
/// Then: The handshake does not complete from the implementation's side: the connection is abandoned before any control frame is sent, no Attach frame appears on stream 0, and the dial is reported as a failed handshake rather than as a session with K.
#[test]
#[ignore = "acceptance TRN-03: owed at milestone 2"]
fn trn_03_abort_the_dial_when_the_presented_raw_public_key() {
    todo!("TRN-03: Abort the dial when the presented raw public key is not the pinned classical member.")
}

/// Reject an Attach whose field 1 is not the transport-authenticated identity.
///
/// Spec: wire-format.md §9.1; wire-format.md §8.2
/// Milestone: 2.  Kind: negative.  Oracle: model.
///
/// Rule (wire-format.md §9.1): "Authentication is mutual. The serving node authenticates the client the same way, and MUST bind the identity for which session state and queued data are requested to the identity the transport authenticated, rejecting any mismatch."
/// Rule (wire-format.md §9.1): "Present encoding: Attach field 1 must equal the connection-authenticated identity."
/// Rule (wire-format.md §8.2): "There is no AttachNack, and refusal is carried as a QUIC close code."
///
/// Given: The implementation acts as serving node S and holds queued items for keyhash B, inspectable by the test. A test client holding keypair A completes a mutual raw-public-key handshake presenting A's classical component, so the connection-authenticated identity is A.
/// When: The test client sends a well-formed Attach whose field 1 is B, with a Capabilities map in field 3.
/// Then: No AttachAck is issued on the connection, nothing queued for B is delivered on it, and S's queue for B is unchanged. No AttachNack or other refusal frame appears on stream 0.
#[test]
#[ignore = "acceptance TRN-04: owed at milestone 2"]
fn trn_04_reject_an_attach_whose_field_1_is_not_the_transp() {
    todo!("TRN-04: Reject an Attach whose field 1 is not the transport-authenticated identity.")
}

/// Negotiate the application protocol rhtn/1.
///
/// Spec: wire-format.md §9.2
/// Milestone: 2.  Kind: positive.  Oracle: behaviour.
///
/// Rule (wire-format.md §9.2): "ALPN: rhtn/1"
///
/// Given: The implementation is exercised in both roles: as dialling party toward a test serving node that records the ClientHello, and as serving node receiving a ClientHello whose ALPN list contains rhtn/1.
/// When: A handshake is run in each role.
/// Then: As dialling party, the ClientHello's ALPN extension carries rhtn/1. As serving node, the negotiated application protocol is rhtn/1 and the handshake completes.
#[test]
#[ignore = "acceptance TRN-05: owed at milestone 2"]
fn trn_05_negotiate_the_application_protocol_rhtn_1() {
    todo!("TRN-05: Negotiate the application protocol rhtn/1.")
}

/// Frame every stream-0 control message as a big-endian length over a typed CBOR array.
///
/// Spec: wire-format.md §8.0; wire-format.md §9.2
/// Milestone: 2.  Kind: positive.  Oracle: fixture.
///
/// Rule (wire-format.md §8.0): "Stream 0 carries length-delimited, type-tagged frames."
/// Rule (wire-format.md §8.0): "frame = u32-be length || deterministic CBOR of [ uint frame_type, body ]"
/// Rule (wire-format.md §9.2): "the control frames of §8.0 — session control (attach, heartbeat, sibling updates) and topology propagation (push, memo)"
///
/// Given: The implementation attaches as client with the identity, attestation and named capabilities of the corpus's Attach fixture, and answers as serving node with the inputs of the corpus's AttachAck fixture; the heartbeat interval in the ack is a test-chosen value in 1..=3600 seconds, since design §21.1 leaves it unset.
/// When: The client attaches.
/// Then: The first bytes the client sends on stream 0 are a 4-byte big-endian length N followed by exactly N bytes of deterministic CBOR decoding to a two-element array [1, Attach], whose body with any greased capability entry removed equals the corpus fixture body. The serving node's reply on stream 0 is likewise a length prefix followed by CBOR decoding to [2, AttachAck]. Neither frame appears on any other stream.
#[test]
#[ignore = "acceptance TRN-06: owed at milestone 2"]
fn trn_06_frame_every_stream_0_control_message_as_a_big_en() {
    todo!("TRN-06: Frame every stream-0 control message as a big-endian length over a typed CBOR array.")
}

/// Skip an unknown control frame sized at the bound, even before the AttachAck.
///
/// Spec: wire-format.md §8.0; wire-format.md §8.2
/// Milestone: 2.  Kind: must-accept.  Oracle: fixture.
///
/// Rule (wire-format.md §8.0): "Unknown frame types MUST be skipped, not rejected."
/// Rule (wire-format.md §8.0): "length counts the CBOR bytes that follow it, and is bounded at 64 KB — exactly 65,536 bytes"
/// Rule (wire-format.md §8.2): "Unknown control frames may precede AttachAck and are skipped as always"
///
/// Given: The implementation, as client, has completed the handshake and sent Attach to a test serving node. Separately, the implementation as serving node has an attached session with a test client. The AttachAck's heartbeat interval is a test-chosen value in 1..=3600 seconds (design §21.1 leaves it unset).
/// When: The test serving node sends on stream 0 a frame whose type is 99 and whose CBOR payload [99, bstr] is exactly 65,536 bytes, so the length prefix reads 65,536, followed by a valid AttachAck. In the other role, the test client sends the same 65,536-byte unknown frame mid-session.
/// Then: In neither role is the connection closed. As client, the AttachAck that follows is accepted and the session is attached in the mode the ack states. As serving node, a request opened on a bidirectional stream after the unknown frame is answered.
#[test]
#[ignore = "acceptance TRN-07: owed at milestone 2"]
fn trn_07_skip_an_unknown_control_frame_sized_at_the_bound() {
    todo!("TRN-07: Skip an unknown control frame sized at the bound, even before the AttachAck.")
}

/// End the session on a declared control-frame length above 65,536.
///
/// Spec: wire-format.md §8.0
/// Milestone: 2.  Kind: negative.  Oracle: fixture.
///
/// Rule (wire-format.md §8.0): "A declared length above the bound is a protocol error, and it ends the session"
///
/// Given: An attached session between the implementation and a test peer, exercised with the implementation in each role.
/// When: The test peer sends on stream 0 a 4-byte length prefix reading 65,537, followed by bytes.
/// Then: The implementation closes the connection: a CONNECTION_CLOSE is observed, and no frame sent on that session after the oversized prefix is acted on. The close code is not stated by the profile and is not checked.
#[test]
#[ignore = "acceptance TRN-08: owed at milestone 2"]
fn trn_08_end_the_session_on_a_declared_control_frame_leng() {
    todo!("TRN-08: End the session on a declared control-frame length above 65,536.")
}

/// Discard a malformed control frame of a known type whole and keep the session.
///
/// Spec: wire-format.md §8.0; wire-format.md §8.2
/// Milestone: 2.  Kind: robustness.  Oracle: fixture.
///
/// Rule (wire-format.md §8.0): "A malformed control frame of a known type is discarded whole, and the session survives"
/// Rule (wire-format.md §8.0): "a malformed SiblingUpdate is ignored whole with the previous list standing"
/// Rule (wire-format.md §8.2): "replaces the client's cached list ENTIRELY."
///
/// Given: The implementation, as client, is attached to a test serving node and holds cached sibling list L from the AttachAck; the ack's heartbeat interval is a test-chosen value in 1..=3600 seconds (design §21.1 leaves it unset).
/// When: The test serving node sends on stream 0 a frame [4, body] within the length bound whose body is not a well-formed SiblingUpdate (a text string), then a valid SiblingUpdate carrying list L2.
/// Then: After the malformed frame the connection remains open and the cached sibling list is still L. After the valid update the cached sibling list is L2.
#[test]
#[ignore = "acceptance TRN-09: owed at milestone 2"]
fn trn_09_discard_a_malformed_control_frame_of_a_known_typ() {
    todo!("TRN-09: Discard a malformed control frame of a known type whole and keep the session.")
}

/// Tolerate a capability parameter whose id is not recognised.
///
/// Spec: wire-format.md §8.1; wire-format.md §8.1.1; design §14.1.1
/// Milestone: 2.  Kind: must-accept.  Oracle: fixture.
///
/// Rule (wire-format.md §8.1.1): "Every implementation MUST tolerate receiving parameters whose ids it does not recognise. That is checkable by anyone: send one and observe whether the session continues."
/// Rule (wire-format.md §8.1): "Unknown parameters MUST be ignored, never rejected."
/// Rule (design §14.1.1): "Tolerating unknown parameters is mandatory and checkable; sending greased ones is self-interested rather than obligatory."
///
/// Given: A test peer builds a Capabilities map holding one entry whose id is a random 64-bit value derived from no name the implementation knows, with an 8-byte value. As serving node the implementation receives it in Attach field 3; as client it receives it in AttachAck field 5, with a test-chosen heartbeat interval in 1..=3600 seconds (design §21.1 leaves it unset).
/// When: The frame carrying the unrecognised parameter arrives.
/// Then: The session continues in both roles: the serving node answers with an AttachAck, the client attaches on the ack it receives, and no close and no error frame follows the unrecognised parameter.
#[test]
#[ignore = "acceptance TRN-10: owed at milestone 2"]
fn trn_10_tolerate_a_capability_parameter_whose_id_is_not() {
    todo!("TRN-10: Tolerate a capability parameter whose id is not recognised.")
}

/// Attach when the peer advertises no capabilities and greases nothing.
///
/// Spec: wire-format.md §8.1; wire-format.md §8.1.1; wire-format.md §1.2
/// Milestone: 2.  Kind: must-accept.  Oracle: behaviour.
///
/// Rule (wire-format.md §8.1): "Absence of a capability is never a connection failure. Parameters set limits; they do not gate the session."
/// Rule (wire-format.md §8.1.1): "Sending is not a MUST, because nothing could check it."
/// Rule (wire-format.md §1.2): "A required map with no entries is encoded as an empty map — Capabilities in Attach and AttachAck is the case in point, since a peer advertising nothing must still send the field."
///
/// Given: A test peer sends a Capabilities map with no entries, the empty map: it advertises none of the capabilities the implementation itself supports and carries no greased parameter. As serving node the implementation receives it in Attach; as client, in an AttachAck whose heartbeat interval is a test-chosen value in 1..=3600 seconds (design §21.1 leaves it unset).
/// When: The frame carrying the empty Capabilities map arrives.
/// Then: The session is established in both roles: the serving node sends an AttachAck, the client attaches on the ack, and the connection is not closed. No absent capability and no absent greased parameter is reported as an error.
#[test]
#[ignore = "acceptance TRN-11: owed at milestone 2"]
fn trn_11_attach_when_the_peer_advertises_no_capabilities() {
    todo!("TRN-11: Attach when the peer advertises no capabilities and greases nothing.")
}

/// Send a greased capability parameter in every session.
///
/// Spec: wire-format.md §8.1.1
/// Milestone: 2.  Kind: positive.  Oracle: behaviour.
///
/// Rule (wire-format.md §8.1.1): "The reference implementation sends one greased parameter per session: a random 64-bit id and a value of 8 random bytes."
///
/// Given: The reference implementation, in both roles, with the list of capability names it publishes and the ids derived from them.
/// When: Two sessions are opened, and the Attach it sends as client and the AttachAck it sends as serving node are captured in each.
/// Then: Each captured Capabilities map contains an entry whose id is the id of no published name and whose value is 8 bytes long, and the id of that entry differs between the two sessions.
#[test]
#[ignore = "acceptance TRN-12: owed at milestone 2"]
fn trn_12_send_a_greased_capability_parameter_in_every_ses() {
    todo!("TRN-12: Send a greased capability parameter in every session.")
}

/// Refuse an attach with application close code 1 and no frame in reply.
///
/// Spec: wire-format.md §8.2
/// Milestone: 2.  Kind: positive.  Oracle: behaviour.
///
/// Rule (wire-format.md §8.2): "There is no AttachNack, and refusal is carried as a QUIC close code."
/// Rule (wire-format.md §8.2): "A node refusing an attach by policy closes the connection with application close code 1 (refused) in CONNECTION_CLOSE."
/// Rule (wire-format.md §8.2): "Code 0 is not used for refusal, since it is the conventional no-error close."
///
/// Given: The implementation acts as serving node S with a local attach policy that refuses client C; the policy itself is local and unspecified by the design, so the test supplies one. C completes a mutual raw-public-key handshake.
/// When: C sends a well-formed Attach whose field 1 is C.
/// Then: S closes the connection with a CONNECTION_CLOSE carrying application close code 1, not 0, and sends no frame of any type on stream 0 in reply: no AttachAck and no refusal frame.
#[test]
#[ignore = "acceptance TRN-13: owed at milestone 2"]
fn trn_13_refuse_an_attach_with_application_close_code_1_a() {
    todo!("TRN-13: Refuse an attach with application close code 1 and no frame in reply.")
}

/// Treat close code 1 as the node's answer, not the endpoint's.
///
/// Spec: wire-format.md §8.2; light-client-requirements.md §4
/// Milestone: 2.  Kind: positive.  Oracle: fixture.
///
/// Rule (wire-format.md §8.2): "A client seeing it MUST treat the refusal as that node's answer, not that endpoint's — its other addresses will say the same"
/// Rule (wire-format.md §8.2): "a primary's refusal does not open sibling failover"
/// Rule (light-client-requirements.md §4): "treat a policy refusal as that node's answer rather than that endpoint's — trying its other addresses will not change it."
///
/// Given: The implementation, as client C, knows its serving node S by two NetworkPoints and holds a cached sibling list from an earlier session. Retry timing and backoff are local policy and are parameterised by the test.
/// When: C dials S's first endpoint, completes the handshake, sends Attach, and receives a CONNECTION_CLOSE with application close code 1.
/// Then: Within the test's observation window C makes no connection attempt to S's second endpoint and dials no cached sibling; the attach attempt ends as refused.
#[test]
#[ignore = "acceptance TRN-14: owed at milestone 2"]
fn trn_14_treat_close_code_1_as_the_node_s_answer_not_the() {
    todo!("TRN-14: Treat close code 1 as the node's answer, not the endpoint's.")
}

/// Keep the session across a client address change without a new attach.
///
/// Spec: wire-format.md §9.2; design §14.1.3
/// Milestone: 2.  Kind: liveness.  Oracle: behaviour.
///
/// Rule (wire-format.md §9.2): "Connection migration relied upon for mobile IP change"
/// Rule (design §14.1.3): "Mobile clients change IP constantly, and QUIC's connection migration survives that natively where ordinary single-path TCP does not"
///
/// Given: An attached session between the implementation as client C and the implementation as serving node S, with a test-chosen heartbeat interval in 1..=3600 seconds (design §21.1 leaves it unset). The test can enqueue an item at S for C.
/// When: C's UDP source address and port change mid-session (a new local socket, or a simulated NAT rebinding) and C continues the same QUIC connection from the new address; the test then enqueues an item for C.
/// Then: No new Attach or AttachAck is exchanged, heartbeats continue in both directions on the same connection from the new address, and the item enqueued after the change is delivered to C over that same connection.
///
/// Interpretation: The serving node is taken to permit client-initiated migration, which RFC 9000 lets a server disable; the documents state that migration is relied upon and place no obligation on the operator in infra-client-requirements.md §7.
#[test]
#[ignore = "acceptance TRN-15: owed at milestone 2"]
fn trn_15_keep_the_session_across_a_client_address_change() {
    todo!("TRN-15: Keep the session across a client address change without a new attach.")
}

/// Process an Attach carried in 0-RTT early data only after that connection's handshake completes.
///
/// Spec: wire-format.md §8.2; wire-format.md §9.2
/// Milestone: 2.  Kind: negative.  Oracle: model.
///
/// Rule (wire-format.md §8.2): "A server MUST NOT process an Attach received in TLS 1.3 0-RTT early data — reject it or defer it until handshake completion."
/// Rule (wire-format.md §8.2): "Early data is replayable, and a replayed Attach re-binds session state"
/// Rule (wire-format.md §9.2): "§8.2's rule for Attach is this rule's other instance, on the other stream class."
///
/// Given: Client C holds a resumption ticket from a completed session with the implementation as serving node S, and S holds a queued item for C. The AttachAck's heartbeat interval is a test-chosen value in 1..=3600 seconds (design §21.1 leaves it unset).
/// When: C opens connection A and sends Attach with field 1 = C as 0-RTT early data. The test captures A's early-data packets and replays them as a second connection B whose handshake it never completes. A's handshake then completes.
/// Then: On A, no AttachAck and no queued delivery is observed before A's handshake completes; afterwards either an AttachAck follows or none is ever sent for that Attach. On B, no AttachAck is ever sent and the queued item is not delivered: it remains queued at S or is delivered on A alone.
///
/// Interpretation: Handshake completion is read as completion of the handshake of the connection that carried the early data, as the compliant Tamarin theory states it; the wire says only 'until handshake completion', and a completed handshake on A is taken not to admit B's replay.
#[test]
#[ignore = "acceptance TRN-16: owed at milestone 2"]
fn trn_16_process_an_attach_carried_in_0_rtt_early_data_on() {
    todo!("TRN-16: Process an Attach carried in 0-RTT early data only after that connection's handshake completes.")
}
