//! GENERATED by tools/gen_stubs.py from acceptance.json.  Do not edit;
//! change the catalogue and regenerate.  Each stub is one acceptance test
//! still owed for this area.

/// Process an Attach carried in 0-RTT early data only after that connection's handshake completes.
///
/// Spec: wire-format.md §8.2; wire-format.md §9.2
/// Milestone: 2.  Kind: negative.  Oracle: model.
///
/// Rule (wire-format.md §8.2): "A server MUST NOT process an Attach received in TLS 1.3 0-RTT early data — reject it or defer it until handshake completion."
/// Rule (wire-format.md §8.2): "Early data is replayable, and a replayed Attach re-binds session state"
/// Rule (wire-format.md §9.2): "§8.2's rule for Attach is this rule's other instance, on the other stream class."
///
/// Given: Client C holds a resumption ticket from a completed session with the implementation as serving node S, and S holds a queued item for C. The AttachAck's heartbeat interval is a test-chosen value in 1..=3600 seconds (design §21.1 leaves it unset).
/// When: C opens connection A and sends Attach with field 1 = C as 0-RTT early data. The test captures A's early-data packets and replays them as a second connection B whose handshake it never completes. A's handshake then completes.
/// Then: On A, no AttachAck and no queued delivery is observed before A's handshake completes; afterwards either an AttachAck follows or none is ever sent for that Attach. On B, no AttachAck is ever sent and the queued item is not delivered: it remains queued at S or is delivered on A alone.
///
/// Interpretation: Handshake completion is read as completion of the handshake of the connection that carried the early data, as the compliant Tamarin theory states it; the wire says only 'until handshake completion', and a completed handshake on A is taken not to admit B's replay.
#[test]
#[ignore = "acceptance TRN-16: owed at milestone 2"]
fn trn_16_process_an_attach_carried_in_0_rtt_early_data_on() {
    todo!("TRN-16: Process an Attach carried in 0-RTT early data only after that connection's handshake completes.")
}
